const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.UNRULY_TEST_URL||'http://127.0.0.1:4173/unruly/';
const out=path.resolve(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});
const results=[];let browser;
async function saved(page){await page.waitForTimeout(550);await page.waitForFunction(()=>document.querySelector('#save').textContent.includes('Saved on this device'),null,{timeout:8000});}
async function records(page){return page.evaluate(()=>new Promise((resolve,reject)=>{const q=indexedDB.open('unruly-foundation',1);q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,t=db.transaction('boards','readonly'),r=t.objectStore('boards').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close();};}));}
async function writeRecord(page,record){await page.evaluate(record=>new Promise((resolve,reject)=>{const q=indexedDB.open('unruly-foundation',1);q.onsuccess=()=>{const db=q.result,t=db.transaction('boards','readwrite');t.objectStore('boards').put(record);t.oncomplete=()=>{db.close();resolve();};t.onerror=()=>reject(t.error);};q.onerror=()=>reject(q.error);}),record);}
async function ink(page,{type='pen',id=11,cancel=false,x=150,y=140}={}){
 await page.bringToFront();const box=await page.locator('#canvas').boundingBox(),cdp=await page.context().newCDPSession(page);
 if(type==='touch'){
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+x,y:box.y+y,id}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+x+30,y:box.y+y+20,id}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 }else{
  await page.evaluate(()=>{const c=document.querySelector('#canvas');c.addEventListener('pointerdown',e=>window.__qaPointerId=e.pointerId,{once:true});});
  await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:box.x+x,y:box.y+y,button:'left',buttons:1,pointerType:type,force:.1,clickCount:1});
  await page.locator('#canvas').evaluate(c=>c.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:999,pointerType:'pen',buttons:1,pressure:1,clientX:9999,clientY:9999})));await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:box.x+x+30,y:box.y+y+20,button:'left',buttons:1,pointerType:type,force:.8});
  if(cancel)await page.locator('#canvas').evaluate(c=>c.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true,pointerType:'pen',pointerId:window.__qaPointerId})));
  await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:box.x+x+50,y:box.y+y+30,button:'left',buttons:0,pointerType:type,force:0,clickCount:1});
 }
 await cdp.detach();
}

async function run(id,fn,viewport={width:1440,height:950}){const context=await browser.newContext({viewport,acceptDownloads:true});await context.tracing.start({screenshots:true,snapshots:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const external=[];page.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)external.push(r.url());});try{await page.goto(base);await saved(page);await fn(page,context);assert.deepEqual(errors,[],'uncaught browser errors');assert.deepEqual(external,[],'external runtime requests');await page.screenshot({path:path.join(out,id+'.png'),fullPage:true});results.push({id,status:'PASS',console_errors:errors});}catch(e){results.push({id,status:'FAIL',message:e.stack,console_errors:errors});await page.screenshot({path:path.join(out,id+'-failure.png'),fullPage:true}).catch(()=>{});await context.tracing.stop({path:path.join(out,id+'-trace.zip')});console.error(id,e.message);}finally{await context.tracing.stop().catch(()=>{});await context.close();}}
(async()=>{browser=await chromium.launch({headless:true});
await run('F01-desktop',async page=>{for(const name of ['New','Boards','Undo','Redo','Export','Pen','Eraser','Pan','Help'])assert(await page.getByRole('button',{name,exact:true}).isVisible(),name);assert(await page.locator('#canvas').isVisible());});
await run('F01-mobile',async page=>{for(const name of ['New','Boards','Export','Pen']){const b=page.getByRole('button',{name,exact:true});assert(await b.isVisible());const r=await b.boundingBox();assert(r.x>=0&&r.x+r.width<=360.5,name+' within viewport');}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal page overflow');},{width:360,height:800});
await run('F01-tablet',async page=>{assert(await page.locator('#canvas').isVisible());},{width:768,height:1024});
await run('F02-pen-lifecycle',async page=>{await ink(page);await saved(page);let all=await records(page);let b=all[0].current;assert.equal(b.strokes.length,1);assert(b.strokes[0].points.some(p=>Math.abs(p.pressure-.8)<1e-6),'synthetic pressure retained');const final=b.strokes[0].points.at(-1);assert.equal(final.x-b.strokes[0].points[0].x,50,'pointerup final point retained');await ink(page,{id:12});await saved(page);b=(await records(page))[0].current;assert.equal(b.strokes.length,2);assert.notEqual(b.strokes[0].id,b.strokes[1].id);await ink(page,{cancel:true});await page.waitForTimeout(500);assert.equal((await records(page))[0].current.strokes.length,2,'cancel no committed ink');await page.locator('#canvas').evaluate(c=>c.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerType:'pen',pointerId:44,buttons:0,pressure:0,clientX:300,clientY:200})));assert.equal((await records(page))[0].current.strokes.length,2,'hover no ink');const cdp=await page.context().newCDPSession(page),box=await page.locator('#canvas').boundingBox();await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:box.x+150,y:box.y+140,button:'left',buttons:1,pointerType:'pen',force:.2,clickCount:1});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+400,y:box.y+300,id:21}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+430,y:box.y+330,id:21}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:box.x+170,y:box.y+150,button:'left',buttons:0,pointerType:'pen',force:0,clickCount:1});await saved(page);let mixed=(await records(page))[0].current;assert(mixed.strokes.length===2||mixed.strokes.length===3,'touch cannot add independent stroke');assert(mixed.strokes.every(s=>s.points.every(p=>p.x<350)),'touch cannot append into pen stroke');const count=mixed.strokes.length;await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:box.x+150,y:box.y+140,button:'left',buttons:1,pointerType:'pen',force:.2,clickCount:1});await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:box.x+170,y:box.y+150,button:'left',buttons:0,pointerType:'pen',force:0,clickCount:1});await page.waitForTimeout(600);assert.equal((await records(page))[0].current.strokes.length,count,'focus cancellation drops unfinished ink');await cdp.detach();});
await run('F03-touch-mouse-navigation',async page=>{await ink(page,{type:'touch'});await page.waitForTimeout(300);assert.equal((await records(page))[0].current.strokes.length,0,'touch cannot ink');await ink(page,{type:'mouse'});await saved(page);let b=(await records(page))[0].current;assert(b.strokes[0].points.every(p=>p.pressure===null),'mouse pressure unavailable');const before=await page.locator('#zoom').textContent();await page.locator('#canvas').hover();await page.mouse.wheel(0,-200);await page.waitForTimeout(200);assert.notEqual(await page.locator('#zoom').textContent(),before,'wheel changes zoom');const cdp=await page.context().newCDPSession(page),box=await page.locator('#canvas').boundingBox();const z=await page.locator('#zoom').textContent();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+100,y:box.y+100,id:21},{x:box.x+200,y:box.y+100,id:22}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+70,y:box.y+100,id:21},{x:box.x+230,y:box.y+100,id:22}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(150);assert.notEqual(await page.locator('#zoom').textContent(),z,'two-finger pinch changes zoom');assert.equal((await records(page))[0].current.strokes.length,1,'pinch never inks');await page.getByRole('button',{name:'Reset view',exact:true}).click();await page.keyboard.down('Space');await page.mouse.move(box.x+200,box.y+200);await page.mouse.down();await page.mouse.move(box.x+260,box.y+200);await page.mouse.up();await page.keyboard.up('Space');await ink(page,{x:150,y:140});await saved(page);const moved=(await records(page))[0].current.strokes.at(-1).points[0];assert(Math.abs(moved.x-90)<2,'space-pan changes document mapping');await cdp.detach();});
await run('F04-history-tools',async page=>{await ink(page);await saved(page);await page.getByRole('button',{name:'Undo',exact:true}).click();await saved(page);assert.equal((await records(page))[0].current.strokes.length,0);await page.getByRole('button',{name:'Redo',exact:true}).click();await saved(page);assert.equal((await records(page))[0].current.strokes.length,1);await page.getByRole('button',{name:'Undo',exact:true}).click();await saved(page);await ink(page,{id:12});await saved(page);assert(await page.getByRole('button',{name:'Redo',exact:true}).isDisabled());await page.getByRole('button',{name:'Eraser',exact:true}).click();await ink(page);await saved(page);assert.equal((await records(page))[0].current.strokes.length,0,'whole stroke erase');await page.getByRole('button',{name:'Undo',exact:true}).click();await saved(page);assert.equal((await records(page))[0].current.strokes.length,1,'erase undo');await page.keyboard.press('Control+z');await saved(page);assert.equal((await records(page))[0].current.strokes.length,0,'keyboard undo');await page.keyboard.press('Control+Shift+z');await saved(page);assert.equal((await records(page))[0].current.strokes.length,1,'keyboard redo');});
await run('F05-reopen-new-export',async page=>{await ink(page);await saved(page);const original=(await records(page))[0].current;await page.reload();await saved(page);assert.equal((await records(page))[0].current.strokes.length,1);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();const file=await download;const location=await file.path();const exported=JSON.parse(fs.readFileSync(location,'utf8'));assert.equal(exported.id,original.id);assert.equal(exported.strokes.length,1);await page.getByRole('button',{name:'New',exact:true}).click();await saved(page);const all=await records(page);assert.equal(all.length,2);assert(all.some(r=>r.current.id===original.id&&r.current.strokes.length===1),'new preserves original');await page.getByRole('button',{name:'Boards',exact:true}).click();await page.getByRole('dialog').waitFor({state:'visible',timeout:5000});assert(await page.getByRole('dialog').isVisible());assert(await page.locator('#board-list').textContent());const title='<img src=x onerror=window.__injected=1>';page.once('dialog',d=>d.accept(title));const originalIndex=all.findIndex(r=>r.id===original.id);await page.locator('.board-row').nth(originalIndex).getByRole('button',{name:/^Rename /}).click();await saved(page);assert.equal(await page.evaluate(()=>window.__injected),undefined,'title inert');assert((await records(page)).some(r=>r.current.title===title),'rename persisted');await page.reload();await saved(page);assert.notEqual((await page.locator('#title').textContent()),title,'inactive rename does not select board');await page.getByRole('button',{name:'Boards',exact:true}).click();await page.getByRole('button',{name:title,exact:true}).click();await saved(page);assert.equal(await page.locator('#title').textContent(),title,'renamed board opens');assert.equal((await records(page)).find(r=>r.id===original.id).current.strokes.length,1,'open preserves original ink');});
await run('F06-corrupt-recovery',async page=>{await ink(page);await saved(page);await ink(page,{id:12});await saved(page);const record=(await records(page))[0];assert(record.previous,'last good exists');const prior=structuredClone(record.previous);record.current={...record.current,strokes:'CORRUPT'};await writeRecord(page,record);await page.reload();await page.waitForFunction(()=>!document.querySelector('#save').textContent.includes('Opening'));const status=await page.locator('#save').textContent();const notices=await page.locator('body').textContent();assert(/recover|last.good/i.test(status+' '+notices),'visible recovery notice');const stored=(await records(page))[0];assert(stored.current.strokes==='CORRUPT'||JSON.stringify(stored.current.strokes)===JSON.stringify(prior.strokes),'corrupt not silently blank overwritten');stored.current={bad:true};stored.previous={bad:true};await writeRecord(page,stored);page.once('dialog',d=>d.accept());await page.reload();await page.waitForTimeout(700);assert(/damaged|recovery error/i.test(await page.locator('#save').textContent()),'unrecoverable damage visible');const still=(await records(page))[0];assert.deepEqual(still.current,{bad:true},'unrecoverable content not silently replaced');});
await run('F07-write-failure-recovery',async page=>{await ink(page);await saved(page);const before=(await records(page))[0].current;await page.evaluate(()=>{window.__qaOriginalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('QA injected quota fault','QuotaExceededError');};});await ink(page,{id:12});await page.waitForFunction(()=>/fail|quota|export/i.test(document.querySelector('#save').textContent));assert.equal((await records(page))[0].current.strokes.length,before.strokes.length,'prior committed revision retained');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();const dl=await pending;const exportBoard=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert.equal(exportBoard.strokes.length,2,'export in-memory recovery');const currentTitle=await page.locator('#title').textContent();await page.getByRole('button',{name:'New',exact:true}).click();await page.waitForTimeout(600);assert.equal(await page.locator('#title').textContent(),currentTitle,'failed New leaves current board');assert.equal((await records(page)).length,1,'failed New does not insert blank');});
await run('F08-concurrent-tabs',async(page,context)=>{const second=await context.newPage();await second.goto(base);await second.waitForTimeout(300);await ink(page);await saved(page);const after=(await records(page))[0].current;await ink(second,{id:12});await second.waitForTimeout(700);const final=(await records(page))[0].current;assert.equal(final.strokes.length,after.strokes.length,'stale second tab cannot overwrite committed edit');assert(/conflict|another|tab|read.only|changed|fail/i.test(await second.locator('body').textContent()),'conflict/single-writer visible');});
await run('F09-offline-reload',async(page,context)=>{await ink(page);await saved(page);await page.evaluate(()=>navigator.serviceWorker.ready);if(!await page.evaluate(()=>Boolean(navigator.serviceWorker.controller))){await page.reload();await saved(page);}await page.waitForFunction(()=>navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await saved(page);assert(await page.locator('#canvas').isVisible());assert.equal((await records(page))[0].current.strokes.length,1);});
await run('F10-worker-update-safety',async page=>{await page.evaluate(()=>navigator.serviceWorker.ready);if(!await page.evaluate(()=>Boolean(navigator.serviceWorker.controller))){await page.reload();await saved(page);}await page.waitForFunction(()=>navigator.serviceWorker.controller);await page.request.post(new URL('/__qa/update',base).href);await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await page.waitForFunction(async()=>Boolean((await navigator.serviceWorker.getRegistration())?.waiting),null,{timeout:12000});assert(await page.locator('#update').isVisible(),'pending worker explicit update');const cdp=await page.context().newCDPSession(page),box=await page.locator('#canvas').boundingBox();await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:box.x+150,y:box.y+140,button:'left',buttons:1,pointerType:'pen',force:.2,clickCount:1});await page.locator('#update').evaluate(b=>b.click());assert(/Finish your stroke/i.test(await page.locator('#save').textContent()),'active contact refuses update');assert(await page.evaluate(async()=>Boolean((await navigator.serviceWorker.getRegistration())?.waiting)),'worker waits during contact');await page.evaluate(()=>{window.__qaOriginalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('QA update quota fault','QuotaExceededError');};});await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:box.x+200,y:box.y+170,button:'left',buttons:0,pointerType:'pen',force:0,clickCount:1});await cdp.detach();await page.locator('#update').click();await page.waitForFunction(()=>document.querySelector('#save').textContent.includes('Save failed'));assert(await page.evaluate(async()=>Boolean((await navigator.serviceWorker.getRegistration())?.waiting)),'save failure refuses worker activation');await page.evaluate(()=>IDBObjectStore.prototype.put=window.__qaOriginalPut);const nav=page.waitForEvent('load');await page.locator('#update').click();await nav;await saved(page);assert.equal((await records(page))[0].current.strokes.length,1,'update retains durable board');});
fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({browser:browser.version(),synthetic_input:true,physical_pen:'NOT_VERIFIED',results},null,2));await browser.close();console.log(JSON.stringify(results.map(r=>({id:r.id,status:r.status}))));process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
