import {limits,validateBoard,createBoard,createHistory,addStroke,eraseStroke,undo,redo,toDocument,zoomAt} from './model.js';
const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d');
let db,h,expected=0,saved=-1,saveTimer,saveChain=Promise.resolve(),tool='pen',view={x:0,y:0,scale:1},active=null,space=false,frame=0,waitingWorker=null,requestedUpdate=false,transitionBusy=false;
const contacts=new Map();
const status=t=>$('save').textContent=t;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('unruly-foundation',1);r.onupgradeneeded=()=>{r.result.createObjectStore('boards',{keyPath:'id'});r.result.createObjectStore('meta');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Storage is busy in another tab'));});}
function read(store,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store),r=tx.objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function allBoards(){return new Promise((resolve,reject)=>{const r=db.transaction('boards').objectStore('boards').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function persist(snapshot,version,isNew=false,select=true){return new Promise((resolve,reject)=>{
 const tx=db.transaction(['boards','meta'],'readwrite'),store=tx.objectStore('boards');let problem;
 const fail=e=>{problem=e;try{tx.abort();}catch{reject(e);}};
 tx.oncomplete=()=>resolve(version+1);tx.onabort=()=>reject(problem||tx.error||Error('Save aborted'));tx.onerror=()=>{};
 const r=store.get(snapshot.id);r.onsuccess=()=>{try{const old=r.result;if((old?old.dbRevision:0)!==version || isNew&&old){fail(Error('Conflict: another tab saved this board. Export your work before reopening.'));return;}
 const put=()=>{try{let previous=null;if(old){try{previous=validateBoard(old.current);}catch{try{previous=validateBoard(old.previous);}catch{}}}store.put({id:snapshot.id,dbRevision:version+1,current:snapshot,previous});if(select)tx.objectStore('meta').put(snapshot.id,'lastBoard');}catch(e){fail(e);}};
 if(!old){const count=store.count();count.onsuccess=()=>{try{if(count.result>=limits.boards)fail(Error('Board limit reached'));else put();}catch(e){fail(e);}};}else put();}catch(e){fail(e);}};
 });}
function saveNow(){clearTimeout(saveTimer);if(!h)return Promise.resolve(false);const snapshot=structuredClone(h.board);
 saveChain=saveChain.catch(()=>false).then(async()=>{if(saved===snapshot.revision)return true;status('Saving…');try{if(!db)throw Error('Local storage unavailable');expected=await persist(snapshot,expected);saved=snapshot.revision;status(saved===h.board.revision?'Saved on this device':'Unsaved changes');return true;}catch(e){status('Save failed · '+e.message);return false;}});return saveChain;}
function changed(next){if(transitionBusy||next===h)return;h=next;status('Unsaved changes');clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,500);refresh();}
function refresh(){if(!h)return;$('title').textContent=h.board.title;$('undo').disabled=!h.past.length;$('redo').disabled=!h.future.length;$('hint').hidden=!!h.board.strokes.length||!!active;$('zoom').textContent=Math.round(view.scale*100)+'%';if(!frame)frame=requestAnimationFrame(paint);}
function stroke(s){ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineCap='round';ctx.lineJoin='round';const width=p=>s.size*(p.pressure===null?1:.15+.85*p.pressure);const a=s.points[0];ctx.beginPath();ctx.arc(a.x,a.y,width(a)/2,0,Math.PI*2);ctx.fill();for(let i=1;i<s.points.length;i++){const p=s.points[i-1],q=s.points[i];ctx.lineWidth=(width(p)+width(q))/2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}
function paint(){frame=0;const d=Math.min(devicePixelRatio||1,3),r=canvas.getBoundingClientRect();const w=Math.round(r.width*d),he=Math.round(r.height*d);if(canvas.width!==w||canvas.height!==he){canvas.width=w;canvas.height=he;}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);ctx.translate(view.x,view.y);ctx.scale(view.scale,view.scale);if(h)for(const s of h.board.strokes)stroke(s);if(active?.stroke)stroke(active.stroke);}
function pos(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
function point(e){const p=pos(e);return {...toDocument(p.x,p.y,view),pressure:e.pointerType==='pen'?Math.max(0,Math.min(1,e.pressure)):null};}
function report(e){$('input').textContent=e.pointerType==='pen'?`Pen · reported pressure ${e.pressure.toFixed(2)}`:e.pointerType==='touch'?'Touch · navigation only':'Mouse · pressure unavailable';}
function segmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);}
function eraseAt(p){for(const s of [...h.board.strokes].reverse()){const radius=s.size/2+8/view.scale;if(s.points.some((q,i)=>i?segmentDistance(p,s.points[i-1],q)<=radius:Math.hypot(p.x-q.x,p.y-q.y)<=radius)){changed(eraseStroke(h,s.id));break;}}}
canvas.addEventListener('pointerdown',e=>{if(!h||transitionBusy||e.button!==0)return;canvas.focus();report(e);canvas.setPointerCapture(e.pointerId);const p=pos(e);contacts.set(e.pointerId,p);if(e.pointerType==='touch')return;if(active)return;if(tool==='pan'||space){active={id:e.pointerId,pan:p};return;}if(tool==='eraser'){eraseAt(point(e));return;}active={id:e.pointerId,stroke:{id:crypto.randomUUID(),color:$('color').value,size:Number($('size').value),points:[point(e)]}};refresh();});
canvas.addEventListener('pointermove',e=>{report(e);if(!contacts.has(e.pointerId))return;const old=contacts.get(e.pointerId),p=pos(e);if(e.pointerType==='touch'&&!active){const before=[...contacts.values()];contacts.set(e.pointerId,p);const after=[...contacts.values()];if(after.length===1){view.x+=p.x-old.x;view.y+=p.y-old.y;}else if(after.length===2){const center=a=>({x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2}),a=center(before),b=center(after),dist=a=>Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);view=zoomAt(view,a.x,a.y,Math.max(.01,dist(after))/Math.max(.01,dist(before)));view.x+=b.x-a.x;view.y+=b.y-a.y;}refresh();return;}contacts.set(e.pointerId,p);if(active?.id!==e.pointerId)return;if(active.pan){view.x+=p.x-active.pan.x;view.y+=p.y-active.pan.y;active.pan=p;}else{const samples=e.getCoalescedEvents?.()||[];for(const sample of samples.length?samples:[e]){if(active.stroke.points.length+h.board.strokes.reduce((n,s)=>n+s.points.length,0)>=limits.points){active=null;status('Point limit reached · unfinished stroke cancelled');break;}active.stroke.points.push(point(sample));}}refresh();});
function finish(e,cancel=false){contacts.delete(e.pointerId);if(active?.id!==e.pointerId)return;const s=active.stroke;active=null;if(s&&!cancel){try{const final=point(e),last=s.points.at(-1);if(final.x!==last.x||final.y!==last.y)s.points.push(final);changed(addStroke(h,s));}catch(err){status(err.message);}}refresh();}
canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,true));canvas.addEventListener('lostpointercapture',e=>finish(e,true));
canvas.addEventListener('wheel',e=>{e.preventDefault();if(active)return;const p=pos(e);view=zoomAt(view,p.x,p.y,Math.exp(Math.max(-2,Math.min(2,-e.deltaY*.001))));refresh();},{passive:false});
for(const name of ['pen','eraser','pan'])$(name).onclick=()=>{active=null;tool=name;for(const n of ['pen','eraser','pan'])$(n).setAttribute('aria-pressed',String(n===name));refresh();};
$('size').oninput=()=>$('size-value').textContent=$('size').value;
$('home').onclick=()=>{view={x:0,y:0,scale:1};refresh();};
$('undo').onclick=()=>{if(!active)changed(undo(h));};$('redo').onclick=()=>{if(!active)changed(redo(h));};
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')||document.querySelector('dialog[open]'))return;if(e.code==='Space'){space=true;e.preventDefault();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(!active)changed(e.shiftKey?redo(h):undo(h));}if(e.key==='Escape'){active=null;contacts.clear();refresh();}});
window.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;active=null;contacts.clear();refresh();});
$('export').onclick=()=>{if(!h)return;const content=JSON.stringify(validateBoard(h.board),null,2),url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='unruly-'+h.board.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function openBoard(record){if(!Number.isSafeInteger(record.dbRevision)||record.dbRevision<1)throw Error('Invalid stored revision; data preserved');let board,recovered=false;try{board=validateBoard(record.current);}catch(e){try{board=validateBoard(record.previous);recovered=true;}catch{throw Error('Board is damaged. Stored data was preserved; it was not replaced.');}}if(board.id!==record.id)throw Error('Stored board identity mismatch; data preserved');h=createHistory(structuredClone(board));expected=record.dbRevision;saved=recovered?-1:board.revision;active=null;view={x:0,y:0,scale:1};status(recovered?'Recovered previous version · Export before continuing':'Saved on this device');refresh();}
async function newBoard(){if(transitionBusy||active)return;transitionBusy=true;try{if(h&&!await saveNow())return;if(active)return;const board=createBoard(crypto.randomUUID());const v=await persist(board,0,true);h=createHistory(board);expected=v;saved=0;view={x:0,y:0,scale:1};status('Saved on this device');refresh();}catch(e){status('Save failed · '+e.message);}finally{transitionBusy=false;}}
$('new').onclick=newBoard;
$('boards').onclick=async()=>{if(!db){status('Local storage unavailable');return;}try{const list=$('board-list');list.replaceChildren();for(const r of await allBoards()){const row=document.createElement('div'),open=document.createElement('button'),rename=document.createElement('button');open.textContent=r.current?.title||'Damaged board';open.onclick=async()=>{if(active||transitionBusy)return;transitionBusy=true;try{if(!await saveNow()||active)return;await openBoard(await read('boards',r.id));$('gallery').close();}catch(e){status(e.message);}finally{transitionBusy=false;}};rename.textContent='Rename';rename.setAttribute('aria-label','Rename '+open.textContent);rename.onclick=async()=>{if(active||transitionBusy)return;transitionBusy=true;try{if(!await saveNow()||active)return;const title=prompt('Board name',r.current?.title||'');if(title===null)return;const record=await read('boards',r.id),board=structuredClone(validateBoard(record.current));board.title=title.trim()||'Untitled board';board.revision++;validateBoard(board);const v=await persist(board,record.dbRevision,false,h.board.id===board.id);if(h.board.id===board.id){h=createHistory(board);expected=v;saved=board.revision;refresh();}open.textContent=board.title;status('Saved on this device');}catch(e){status('Save failed · '+e.message);}finally{transitionBusy=false;}};row.className='board-row';open.className='open';row.append(open,rename);list.append(row);}$('gallery').showModal();}catch(e){status('Storage unavailable · '+e.message);}};
$('close-gallery').onclick=()=>$('gallery').close();$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();
new ResizeObserver(refresh).observe(canvas);
window.addEventListener('beforeunload',e=>{if(active||h&&saved!==h.board.revision){e.preventDefault();e.returnValue='';}});
async function startup(){try{db=await openDB();db.onversionchange=()=>{db.close();db=null;status('Storage changed · reopen this page');};const last=await read('meta','lastBoard');if(last){const record=await read('boards',last);if(!record)throw Error('Saved board is missing; stored records were preserved.');await openBoard(record);}else await newBoard();}catch(e){status('Storage/recovery error · '+e.message);if(!h){h=createHistory(createBoard(crypto.randomUUID(),'Recovery workspace'));saved=-1;refresh();}}}
async function offline(){if(!('serviceWorker'in navigator)){$('offline').textContent='Offline caching unavailable';return;}try{const r=await navigator.serviceWorker.register('./sw.js');const observe=w=>{if(w)w.addEventListener('statechange',()=>{if(w.state==='redundant')$('offline').textContent='Offline setup failed · stay online';});};observe(r.installing);r.addEventListener('updatefound',()=>observe(r.installing));await navigator.serviceWorker.ready;$('offline').textContent='Ready for offline use';const check=()=>{if(r.waiting){waitingWorker=r.waiting;$('update').hidden=false;}};check();r.addEventListener('updatefound',()=>r.installing?.addEventListener('statechange',check));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(requestedUpdate)location.reload();});}catch{$('offline').textContent='Offline setup failed · stay online';}}
$('update').onclick=async()=>{if(active||transitionBusy){status('Finish your stroke before updating');return;}transitionBusy=true;try{if(!await saveNow()||active||saved!==h.board.revision)return;if(waitingWorker){requestedUpdate=true;waitingWorker.postMessage({type:'ACTIVATE_UPDATE'});}}finally{transitionBusy=false;}};
startup();offline();
