import {createSmudgeSession} from './smudge.js';
import {initSmudgeUI} from './smudge-ui.js';
import {initRecipeUI} from './brush-recipe-ui.js';
import {initBrushComparison} from './brush-compare.js';
import {brushWidthFromPercent,brushPercentFromWidth} from './brush-size.js';
import {initPressureUI} from './pressure-ui.js';
import {readPenConfig,validateDynamics,resolveBrushDynamics,penAction} from './pen-input.js';
import {selectLasso,selectionBounds,copySelection,deleteSelection,moveSelection,pasteSelection,transformSelection} from './selection.js';
import {limits,createBoard,createHistory,command,addStroke,editable,layerCommand,undo,redo,eraseGesture,importDocument,toDocument,zoomAt} from './model.js';
import {createRenderer} from './render.js';
import {openStore} from './storage.js';
import {presetLabel} from './brushes.js';
import {initU2UI} from './u2.js';
import {createTouchTracker,createHistoryHold,twoFingerViewReset,threeFingerFocusToggle,threeFingerClipboardSwipe,fitArtworkView,TOUCH_LIMITS} from './gestures.js';
import {recognizeHeldShape,reshapeRecognized,editRecognized} from './shapes.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),renderer=createRenderer(canvas);
let store,h,expected=0,saved=-1,saveTimer,saveChain=Promise.resolve(),view={x:0,y:0,scale:1},tool='pen',settings={brush:'ink',preset:'ink-fineliner',size:3,opacity:1,color:'#203d48'},active=null,space=false,frame=0,busy=false,waitingWorker=null,requestedUpdate=false;
let selected=[],clipboard=null,opacityDraft=null,layerDrag=null,pending=null;
const penConfig=readPenConfig();penConfig.overrides=penConfig.overrides||{};settings.dynamics=resolveBrushDynamics(penConfig.dynamics,penConfig.overrides,settings.preset);let lassoAutoMove=false,penObserved={count:0,min:1,max:0,latest:null,buttons:0};
const touchTracker=createTouchTracker();let touchHoldTimer=null,touchPicked=null,touchBaseView=null;
let cancelLayerGesture=null,editDrag=null,touchAnchor=null,curveUI=null,gestureClipboardPending=false;
const fullscreenButton=$('fullscreen-toggle');
function syncFullscreenButton(){const active=!!document.fullscreenElement;fullscreenButton.setAttribute('aria-label',active?'Exit fullscreen':'Enter fullscreen');fullscreenButton.title=active?'Exit fullscreen':'Enter fullscreen (F11 on desktop)';fullscreenButton.setAttribute('aria-pressed',String(active));schedulePaint();}
fullscreenButton.addEventListener('click',async()=>{try{if(document.fullscreenElement){await document.exitFullscreen();}else if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();}else{status('Fullscreen is not supported here · try F11',true);}}catch{status('Browser blocked fullscreen · try F11 or Add to Home screen',true);}syncFullscreenButton();});
document.addEventListener('fullscreenchange',syncFullscreenButton);
const thumbnails=new Map();
const blocked=()=>!!active||busy||!!layerDrag||!!opacityDraft||!!pending||!!touchTracker.snapshot()||!!curveUI?.editing();
const contacts=new Map();
const status=(text,error=false)=>{$('save').textContent=text;$('save').dataset.error=String(error);};
function smudgePreview(owner){if(owner?.smudge?.changed){const board=structuredClone(owner.base);board.version=4;board.layers.find(l=>l.id===board.activeLayer).strokes=[owner.smudge.stroke()];owner.smudged=board;owner.smudgeDirty=false;}}
function paint(){frame=0;if(!h)return;try{if(active?.smudgeDirty)smudgePreview(active);const board=pending?.kind==='transform'?pending.preview.board:opacityDraft?.board||active?.moved?.board||active?.smudged||active?.erased||h.board;const live=pending?.kind==='shape'?pending.stroke:active?.stroke||null;renderer.render(board,view,live);}catch(e){status('Render limit · '+e.message,true);}}
function schedulePaint(){if(!frame)frame=requestAnimationFrame(paint);}
function refresh(){if(!h)return;selectionUI();geometryUI();$('undo').disabled=pending?!pending.localPast.length:!h.past.length;$('redo').disabled=pending?!pending.localFuture.length:!h.future.length;$('title').value=h.board.title;$('zoom').textContent=Math.round(view.scale*100)+'%';$('hint').hidden=h.board.layers.some(l=>l.strokes.length)||!!active;const l=h.board.layers.find(l=>l.id===h.board.activeLayer);$('clear-layer').disabled=l.locked||!l.strokes.length;$('layer-warning').textContent=l.locked||!l.visible?'Active layer is '+(l.locked?'locked':'hidden')+'. Select another layer to draw.':h.evicted?'Older undo states were released to keep memory bounded.':'';schedulePaint();}
function panels(){
 if(!h||active||opacityDraft||layerDrag)return;
 const b=h.board;$('paper').value=b.paper.kind;$('paper-color').value=b.paper.color;$('spacing').value=b.paper.spacing;
 const list=$('layer-list');list.replaceChildren();
 const retained=new Set(b.layers.map(l=>l.id));for(const id of thumbnails.keys())if(!retained.has(id))thumbnails.delete(id);
 for(const l of [...b.layers].reverse()){
  const row=document.createElement('div');row.className='layer';row.dataset.active=String(l.id===b.activeLayer);row.dataset.layerId=l.id;
  const top=document.createElement('div');top.className='layer-top';
  const grip=document.createElement('button');grip.className='layer-grip';grip.textContent='⋮';grip.setAttribute('aria-label','Drag to reorder '+l.name);top.append(grip);
  const select=document.createElement('button');select.className='layer-select';select.setAttribute('aria-label','Select '+l.name);select.setAttribute('aria-pressed',String(l.id===b.activeLayer));
  const img=document.createElement('img');img.alt='';img.width=80;img.height=48;
  const cached=thumbnails.get(l.id);if(cached?.layer===l)img.src=cached.src;else try{img.src=renderer.thumbnail(l);thumbnails.set(l.id,{layer:l,src:img.src});}catch(e){status('Thumbnail unavailable · '+e.message,true);}
  const name=document.createElement('span');name.className='layer-name';name.textContent=l.name+(l.locked?' · locked':'');select.append(img,name);select.onclick=()=>{if(row.dataset.suppressClick==='true'){delete row.dataset.suppressClick;return;}editLayer('select',l.id);};top.append(select);
  const blend=document.createElement('button');blend.className='layer-blend-button';blend.textContent=l.blend==='normal'?'N':l.blend.slice(0,1).toUpperCase();blend.title=l.blend;blend.setAttribute('aria-label','Blend properties '+l.name);blend.onclick=()=>{if(blocked())return;editLayer('select',l.id);$('layer-blend').focus();};top.append(blend);
  const visible=document.createElement('button');visible.className='layer-visibility';visible.setAttribute('aria-label',(l.visible?'Hide ':'Show ')+l.name);visible.setAttribute('aria-pressed',String(l.visible));visible.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12c4-7 16-7 20 0-4 7-16 7-20 0Z"/><circle cx="12" cy="12" r="3"/>'+(!l.visible?'<path d="M3 3l18 18"/>':'')+'</svg>';visible.onclick=()=>editLayer('visible',l.id,!l.visible);top.append(visible);
  const menu=document.createElement('button');menu.className='layer-menu';menu.textContent='…';menu.setAttribute('aria-label','Actions '+l.name);menu.setAttribute('aria-expanded','false');top.append(menu);row.append(top);
  const actions=document.createElement('div');actions.className='layer-actions';actions.hidden=true;const rename=document.createElement('input');rename.value=l.name;rename.maxLength=64;rename.setAttribute('aria-label','Layer name '+l.name);rename.onchange=()=>editLayer('name',l.id,rename.value);actions.append(rename);
  for(const [action,text,value] of [['locked',l.locked?'Unlock':'Lock',!l.locked],['duplicate','Duplicate'],['delete','Delete'],['up','Up'],['down','Down']]){const btn=document.createElement('button');btn.textContent=text;btn.setAttribute('aria-label',text+' '+l.name);btn.disabled=action==='delete'&&(l.locked||b.layers.length===1)||action==='up'&&l===b.layers.at(-1)||action==='down'&&l===b.layers[0];btn.onclick=()=>editLayer(action,l.id,value);actions.append(btn);}
  row.append(actions);menu.onclick=()=>{if(blocked())return;actions.hidden=!actions.hidden;menu.setAttribute('aria-expanded',String(!actions.hidden));};
  row.addEventListener('keydown',e=>{if(e.target.closest('input'))return;if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();editLayer(e.key==='ArrowUp'?'up':'down',l.id);[...$('layer-list').children].find(row=>row.dataset.layerId===l.id)?.querySelector('.layer-grip')?.focus();}});
  setupLayerGesture(row,grip,select,menu,l.id);list.append(row);
 }
 const l=b.layers.find(l=>l.id===b.activeLayer);$('layer-opacity').value=Math.round(l.opacity*100);$('layer-opacity-value').value=Math.round(l.opacity*100)+'%';$('layer-opacity').disabled=l.locked;$('layer-blend').value=l.blend;$('layer-blend').disabled=l.locked;$('layer-properties').dataset.layerId=l.id;$('add-layer').disabled=b.layers.length>=limits.layers;
}
function setupLayerGesture(row,grip,select,menu,id){
 let candidate=null;
 const detach=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',end,true);window.removeEventListener('pointercancel',abort,true);};
 function stop(cancelled=false){if(!candidate)return;clearTimeout(candidate.timer);const c=candidate;candidate=null;cancelLayerGesture=null;detach();if(layerDrag){layerDrag=null;row.removeAttribute('data-dragging');if(!cancelled){const rows=[...$('layer-list').querySelectorAll('[data-layer-id]')],index=rows.indexOf(row);editLayer('reorder',id,rows.length-1-index);}panels();}else if(!cancelled&&c.swipe){row.dataset.suppressClick='true';menu.click();}else if(!cancelled&&!c.grip){editLayer('select',id);}if(cancelled)panels();}
 function move(e){const c=candidate;if(!c||c.pointer!==e.pointerId)return;if(active||busy){stop(true);return;}const dx=e.clientX-c.x,dy=e.clientY-c.y;if(!layerDrag&&Math.abs(dx)>=48&&Math.abs(dy)<24&&!c.grip&&!c.ready){c.swipe=dx<0;return;}if(!layerDrag&&(c.grip||c.ready)&&Math.hypot(dx,dy)>=6){layerDrag={id};row.dataset.dragging='true';row.dataset.suppressClick='true';}if(!layerDrag)return;e.preventDefault();const list=$('layer-list'),r=list.getBoundingClientRect();if(e.clientY<r.top+24)list.scrollTop=Math.max(0,list.scrollTop-12);else if(e.clientY>r.bottom-24)list.scrollTop=Math.min(list.scrollHeight-list.clientHeight,list.scrollTop+12);for(const other of [...list.children]){if(other===row)continue;const box=other.getBoundingClientRect();if(e.clientY<box.top+box.height/2){list.insertBefore(row,other);break;}if(other===list.lastElementChild)list.append(row);}}
 function end(e){if(candidate?.pointer===e.pointerId)stop();}
 function abort(e){if(candidate?.pointer===e.pointerId)stop(true);}
 row.addEventListener('pointerdown',e=>{if(blocked()||e.button!==0||!e.target.closest('.layer-grip,.layer-select'))return;cancelLayerGesture=()=>stop(true);candidate={pointer:e.pointerId,x:e.clientX,y:e.clientY,grip:!!e.target.closest('.layer-grip'),swipe:false,ready:false};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',end,true);window.addEventListener('pointercancel',abort,true);try{row.setPointerCapture(e.pointerId);}catch{}candidate.timer=setTimeout(()=>{if(candidate)candidate.ready=true;},350);});
 row.addEventListener('lostpointercapture',e=>{if(candidate?.pointer===e.pointerId&&!layerDrag)stop(true);});
}
function cancelOpacity(){if(!opacityDraft)return;opacityDraft=null;panels();schedulePaint();}
$('layer-opacity').oninput=()=>{if(active||busy||layerDrag)return;const l=h.board.layers.find(l=>l.id===h.board.activeLayer);if(l.locked)return;if(!opacityDraft)opacityDraft={id:l.id,board:structuredClone(h.board)};const value=Number($('layer-opacity').value)/100;opacityDraft.board.layers.find(l=>l.id===opacityDraft.id).opacity=value;$('layer-opacity-value').value=Math.round(value*100)+'%';renderer.invalidate();schedulePaint();};
$('layer-opacity').onchange=()=>{if(!opacityDraft)return;const {id,board}=opacityDraft,value=board.layers.find(l=>l.id===id).opacity;opacityDraft=null;editLayer('opacity',id,value);panels();};
$('layer-opacity').addEventListener('pointercancel',cancelOpacity);window.addEventListener('blur',()=>{cancelOpacity();cancelLayerGesture?.();});$('layer-blend').onchange=()=>editLayer('blend',h.board.activeLayer,$('layer-blend').value);

function changed(next,updatePanels=false,keepSelection=false){if(next===h)return;if(!keepSelection)selected=[];h=next;status('Unsaved changes');clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,500);refresh();if(updatePanels)panels();}
function act(fn,updatePanels=true,keepSelection=false){if(blocked())return;try{changed(fn(),updatePanels,keepSelection);}catch(e){status(e.message,true);refresh();}}
const editLayer=(action,id,value)=>act(()=>layerCommand(h,action,id,value),true,action==='locked'&&id===h.board.activeLayer);
function saveNow(){clearTimeout(saveTimer);if(!h)return Promise.resolve(false);const snapshot=structuredClone(h.board);saveChain=saveChain.catch(()=>false).then(async()=>{if(saved===snapshot.revision)return true;status('Saving…');try{if(!store)throw Error('Local storage unavailable');expected=await store.save(snapshot,expected);saved=snapshot.revision;status(saved===h.board.revision?'Saved on this device':'Unsaved changes');return true;}catch(e){status('Save failed · '+e.message,true);return false;}});return saveChain;}
function sample(){try{$('sample').src=renderer.preview({id:'sample',...settings,points:[{x:16,y:30,pressure:.1},{x:45,y:15,pressure:.3},{x:80,y:35,pressure:1},{x:120,y:22,pressure:.6},{x:165,y:28,pressure:.15}]},Math.max(80,$('sample').clientWidth),56);}catch(e){status(e.message,true);}$('sample-label').textContent=settings.opacity===0?'Invisible ink (0%)':presetLabel(settings.preset)+' · '+brushPercentFromWidth(settings.size,settings.brush)+'% size · '+Math.round(settings.opacity*100)+'%';}
const smudgeUI=initSmudgeUI({$,blocked,status,onChange:()=>{if(tool==='smudge')syncToolModifiers();}});
const recipeUI=initRecipeUI({$,settings,blocked,sample,status});
const u2=initU2UI({settings,renderer,$,blocked,status,sample,onPresetChange:(id,reset)=>{recipeUI.select(id,reset);settings.dynamics=resolveBrushDynamics(penConfig.dynamics,penConfig.overrides,settings.preset);syncPenControls();curveUI?.sync();}});
function syncPenControls(){const overriding=Object.hasOwn(penConfig.overrides,settings.preset);$('pressure-brush-override').checked=overriding;$('pressure-scope-label').textContent=overriding?'Editing this brush only':'Editing global profile';const d=settings.dynamics;$('pressure-width').checked=d.size;$('pressure-opacity').checked=d.opacity;$('pressure-min-width').value=d.minWidth*100;$('pressure-min-opacity').value=d.minOpacity*100;$('pressure-curve').value=d.curve?'custom':d.exponent;$('pen-barrel-map').value=penConfig.mappings.barrel;$('pen-eraser-map').value=penConfig.mappings.eraser;$('global-pen-barrel-map').value=penConfig.mappings.barrel;$('global-pen-eraser-map').value=penConfig.mappings.eraser;}
function persistPen(){if(Object.hasOwn(penConfig.overrides,settings.preset))penConfig.overrides[settings.preset]=structuredClone(settings.dynamics);else penConfig.dynamics=structuredClone(settings.dynamics);try{localStorage.setItem('unruly-pen-ui-v1',JSON.stringify(penConfig));}catch{status('Pen settings cannot be saved on this device',true);}}
$('pressure-brush-override').addEventListener('change',()=>{if(blocked()){syncPenControls();return;}if($('pressure-brush-override').checked)penConfig.overrides[settings.preset]=structuredClone(settings.dynamics);else delete penConfig.overrides[settings.preset];settings.dynamics=resolveBrushDynamics(penConfig.dynamics,penConfig.overrides,settings.preset);persistPen();syncPenControls();curveUI?.sync();sample();});
for(const id of ['pressure-width','pressure-opacity','pressure-min-width','pressure-min-opacity','pressure-curve'])$(id).addEventListener('change',()=>{if(blocked()){syncPenControls();return;}try{const d={size:$('pressure-width').checked,opacity:$('pressure-opacity').checked,minWidth:Number($('pressure-min-width').value)/100,minOpacity:Number($('pressure-min-opacity').value)/100,exponent:$('pressure-curve').value==='custom'?settings.dynamics.exponent:Number($('pressure-curve').value)};if($('pressure-curve').value==='custom'&&settings.dynamics.curve)d.curve=[...settings.dynamics.curve];validateDynamics(d);settings.dynamics=d;persistPen();sample();curveUI?.sync();}catch(e){syncPenControls();status(e.message,true);}});
for(const [id,key] of [['pen-barrel-map','barrel'],['pen-eraser-map','eraser'],['global-pen-barrel-map','barrel'],['global-pen-eraser-map','eraser']])$(id).addEventListener('change',()=>{if(blocked()){syncPenControls();return;}if(['lasso','eraser','pan','none'].includes($(id).value)){penConfig.mappings[key]=$(id).value;persistPen();}syncPenControls();});syncPenControls();
const brushComparison=initBrushComparison({$,renderer,getSettings:()=>settings,getConfig:()=>penConfig,getRecipe:id=>recipeUI.snapshot(id),blocked});
curveUI=initPressureUI({$,onSamples:s=>brushComparison.samples(s),getDynamics:()=>settings.dynamics,blocked,status,onChange:d=>{validateDynamics(d);settings.dynamics=structuredClone(d);persistPen();syncPenControls();sample();}});
function insideSelection(p){try{const b=selectionBounds(h.board,selected);return b&&p.x>=b.minX&&p.x<=b.maxX&&p.y>=b.minY&&p.y<=b.maxY;}catch{return false;}}
function restorePenTool(done){if(done?.previousTool!==undefined){setTool(done.previousTool);lassoAutoMove=done.previousAutoMove;}}

for(const id of ['size','opacity'])for(const control of [id,id+'-number'])$(control).addEventListener(control===id?'input':'change',()=>{if(blocked())return;const value=Number($(control).value);if(!Number.isFinite(value)||value<0||value>100||$(control).value===''){status('Value must be 0 to 100%',true);$(control).value=id==='size'?brushPercentFromWidth(settings.size,settings.brush):Math.round(settings.opacity*100);if(tool==='smudge')syncToolModifiers();return;}if(tool==='smudge'){smudgeUI.set(id==='size'?'size':'strength',value);return;}if(id==='size')settings.size=brushWidthFromPercent(value,settings.brush);else settings.opacity=value/100;$(id).value=value;$(id+'-number').value=value;u2.syncPresetSettings();sample();});
function setTool(id){if(blocked())return;tool=id;lassoAutoMove=id==='lasso';canvas.style.cursor=id==='move'?'move':'';for(const name of ['pen','smudge','eraser','pan','lasso'])$(name).setAttribute('aria-pressed',String(name===id));$('move-selection').setAttribute('aria-pressed',String(id==='move'));syncToolModifiers();}
function syncToolModifiers(){const smudge=tool==='smudge',q=smudge?smudgeUI.snapshot():settings;document.querySelector('label[for=opacity]').textContent=smudge?'Strength':'Opacity';$('opacity-number').setAttribute('aria-label',smudge?'Smudge strength percent':'Brush opacity percent');$('size').value=$('size-number').value=brushPercentFromWidth(q.size,smudge?'airbrush':settings.brush);$('opacity').value=$('opacity-number').value=Math.round((smudge?q.strength:settings.opacity)*100);smudgeUI.sync();}
for(const id of ['pen','smudge','eraser','pan','lasso'])$(id).onclick=()=>{if(blocked())return;const same=tool===id;setTool(id);if(id==='pan'){closePopovers();return;}togglePopover(id==='pen'?'brush-popover':id==='smudge'?'smudge-popover':id==='eraser'?'eraser-popover':'selection-controls',id,same);};
let smudgeHold=null,smudgeHoldUsed=false;
$('smudge').addEventListener('pointerdown',e=>{if(blocked()||e.button!==0)return;smudgeHoldUsed=false;smudgeHold=setTimeout(()=>{smudgeHold=null;if(blocked())return;smudgeUI.transfer(settings);setTool('smudge');togglePopover('smudge-popover','smudge',false);smudgeHoldUsed=true;status('Paint brush copied to Smudge');},500);});
for(const name of ['pointerup','pointercancel','pointerleave'])$('smudge').addEventListener(name,()=>{clearTimeout(smudgeHold);smudgeHold=null;});
$('smudge').addEventListener('click',e=>{if(smudgeHoldUsed){smudgeHoldUsed=false;e.preventDefault();e.stopImmediatePropagation();}},true);
function selectionUI(){const n=selected.length;$('selection-count').textContent=n+' selected';let writable=true;try{editable(h.board);}catch{writable=false;}for(const id of ['move-selection','transform-selection','cut-selection','delete-selection'])$(id).disabled=!n||!writable||!!active||busy||!!pending;$('copy-selection').disabled=!n||!h.board.layers.find(l=>l.id===h.board.activeLayer).visible||blocked();$('clear-selection').disabled=!n||!!active||busy;$('paste-selection').disabled=!clipboard||!writable||!!active||busy;const box=$('selection-box'),line=$('lasso-path');try{const displayBoard=pending?.kind==='transform'?pending.preview.board:active?.moved?.board||h.board;const bounds=selected.length?selectionBounds(displayBoard,selected):null;box.toggleAttribute('hidden',!bounds);if(bounds){box.setAttribute('x',bounds.minX*view.scale+view.x);box.setAttribute('y',bounds.minY*view.scale+view.y);box.setAttribute('width',Math.max(1,bounds.width*view.scale));box.setAttribute('height',Math.max(1,bounds.height*view.scale));}}catch{box.setAttribute('hidden','');}line.toggleAttribute('hidden',!active?.lasso);if(active?.lasso)line.setAttribute('points',active.polygon.map(p=>(p.x*view.scale+view.x)+','+(p.y*view.scale+view.y)).join(' '));}
function openGestureClipboard(){if(!h||pending||busy)return;const activeLayer=h.board.layers.find(l=>l.id===h.board.activeLayer);const editableLayer=activeLayer&&!activeLayer.locked&&activeLayer.visible;$('gesture-copy').disabled=!selected.length||!activeLayer?.visible;$('gesture-cut').disabled=!selected.length||!editableLayer;$('gesture-paste').disabled=!clipboard||!editableLayer;$('gesture-clipboard').hidden=false;}
for(const kind of ['cut','copy','paste'])$('gesture-'+kind).addEventListener('click',()=>{selectionAction(kind);$('gesture-clipboard').hidden=true;});
$('gesture-clipboard-close').addEventListener('click',()=>{$('gesture-clipboard').hidden=true;});
function selectionAction(kind){if(blocked()||!h)return;try{if(kind==='copy'){clipboard=copySelection(h.board,selected);status('Copied '+selected.length+' strokes · page clipboard');}else if(kind==='cut'){const nextClipboard=copySelection(h.board,selected),next=deleteSelection(h,selected);changed(next);clipboard=nextClipboard;}else if(kind==='delete')changed(deleteSelection(h,selected));else if(kind==='paste'){const before=new Set(h.board.layers.flatMap(l=>l.strokes.map(s=>s.id))),r=canvas.getBoundingClientRect(),center=toDocument(r.width/2,r.height/2,view),next=pasteSelection(h,clipboard,center.x,center.y);selected=next.board.layers.find(l=>l.id===next.board.activeLayer).strokes.filter(s=>!before.has(s.id)).map(s=>s.id);changed(next,false,true);setTool('move');}else if(kind==='clear'){selected=[];}refresh();}catch(e){status(e.message,true);refresh();}}
$('move-selection').onclick=()=>{setTool('move');if(!blocked())closePopovers();};for(const [id,kind] of [['copy-selection','copy'],['cut-selection','cut'],['paste-selection','paste'],['delete-selection','delete'],['clear-selection','clear']])$(id).onclick=()=>selectionAction(kind);
function gesturePoint(e){const p=pos(e);return toDocument(p.x,p.y,active?.frozenView||view);}
function lassoPoint(e){const p=gesturePoint(e),last=active.polygon.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)>1e-7){if(active.polygon.length>=512)throw Error('Lasso limit reached · selection unchanged');active.polygon.push(p);}}
function movePreview(e){const p=gesturePoint(e);active.dx=p.x-active.start.x;active.dy=p.y-active.start.y;active.moved=moveSelection(active.baseHistory,active.ids,active.dx,active.dy);}

function geometryUI(){
 for(const id of ['transform-scale-handle','transform-rotate-handle','shape-handle-a','shape-handle-b'])$(id).setAttribute('hidden','');
 const css=p=>({x:p.x*view.scale+view.x,y:p.y*view.scale+view.y});
 if(pending?.kind==='transform')try{const b=selectionBounds(pending.preview.board,pending.ids);if(b){const s=css({x:b.maxX,y:b.maxY}),r=css({x:b.cx,y:b.minY-30/Math.max(view.scale,.001)});for(const [id,p]of [['transform-scale-handle',s],['transform-rotate-handle',r]]){$(id).setAttribute('cx',p.x);$(id).setAttribute('cy',p.y);$(id).removeAttribute('hidden');}}}catch{}
 if(pending?.kind==='shape'){const q=pending.recognized,a=q.kind==='line'?q.points[0]:q.center,b=q.kind==='line'?q.points[1]:{x:q.center.x+q.radius,y:q.center.y},aa=css(a),bb=css(b);for(const [id,p]of [['shape-handle-a',aa],['shape-handle-b',bb]]){$(id).setAttribute('cx',p.x);$(id).setAttribute('cy',p.y);$(id).removeAttribute('hidden');}}
}
const sameEdit=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const editState=()=>pending?.kind==='transform'?{...pending.params}:structuredClone(pending?.recognized);
function historyCapacity(states){if(states.length>limits.history||new TextEncoder().encode(states.map(x=>JSON.stringify(x)).join('')).length>limits.historyBytes){status('Edit history capacity reached · Apply or Cancel before continuing',true);return false;}return true;}
function localCapacity(before){return historyCapacity([...h.past,...h.future,...pending.localPast,before]);}
function localRecord(before,after=editState()){if(!pending||sameEdit(before,after))return true;if(!localCapacity(before))return false;pending.localPast.push(structuredClone(before));pending.localFuture=[];return true;}
function restoreEdit(before){if(!pending)return;if(pending.kind==='transform'){pending.params=before;pending.preview=transformSelection(pending.baseHistory,pending.ids,before);syncTransformInputs();}else{pending.recognized=before;pending.stroke={...pending.stroke,points:before.points.map(p=>({...p}))};syncShapeInputs();}refresh();}
function syncTransformInputs(){if(pending?.kind!=='transform')return;const p=pending.params;$('transform-x').value=p.dx;$('transform-y').value=p.dy;$('transform-scale').value=p.scale*100;$('transform-angle').value=p.angle;}
function updateTransform(next,record=false){if(pending?.kind!=='transform')return false;const before={...pending.params},p={...pending.params,...next};try{const preview=transformSelection(pending.baseHistory,pending.ids,p);if(record&&!localRecord(before,p))return false;pending.params=p;pending.preview=preview;syncTransformInputs();refresh();return true;}catch(e){syncTransformInputs();status(e.message,true);return false;}}
function beginTransform(){if(blocked()||!selected.length)return;try{editable(h.board);selectionBounds(h.board,selected);}catch(e){status(e.message,true);return;}closePopovers();pending={kind:'transform',baseHistory:h,ids:[...selected],params:{dx:0,dy:0,scale:1,angle:0},preview:h,localPast:[],localFuture:[]};$('transform-controls').hidden=false;syncTransformInputs();status('Transform preview · Apply or Cancel');refresh();}
function applyTransform(){if(pending?.kind!=='transform'||editDrag)return;const q=pending;pending=null;$('transform-controls').hidden=true;if(q.preview!==q.baseHistory)changed(q.preview,false,true);else refresh();status('Transform applied');}
function cancelTransform(){editDrag?.cancel();if(pending?.kind!=='transform')return;pending=null;$('transform-controls').hidden=true;status('Transform cancelled');refresh();}
function syncShapeInputs(){if(pending?.kind!=='shape')return;const q=pending.recognized;$('shape-kind').textContent=q.kind==='line'?'Line':'Circle';$('shape-line-fields').hidden=q.kind!=='line';$('shape-circle-fields').hidden=q.kind!=='circle';if(q.kind==='line'){const [a,b]=q.points;$('shape-x1').value=a.x;$('shape-y1').value=a.y;$('shape-x2').value=b.x;$('shape-y2').value=b.y;}else{$('shape-cx').value=q.center.x;$('shape-cy').value=q.center.y;$('shape-radius').value=q.radius;}}
function updateShape(next,record=false){if(pending?.kind!=='shape')return false;const before=structuredClone(pending.recognized);try{const q=editRecognized(pending.recognized,next);const stroke={...pending.stroke,points:q.points.map(p=>({...p}))};addStroke(pending.baseHistory,stroke);if(record&&!localRecord(before,q))return false;pending.recognized=q;pending.stroke={...pending.stroke,points:q.points.map(p=>({...p}))};syncShapeInputs();refresh();return true;}catch(e){syncShapeInputs();status(e.message,true);return false;}}
function beginShapeDraft(done){closePopovers();const q=done.recognized;pending={kind:'shape',baseHistory:h,recognized:q,stroke:{...done.stroke,points:q.points.map(p=>({...p}))},localPast:[],localFuture:[]};$('shape-controls').hidden=false;syncShapeInputs();status('Edit '+q.kind+' · Apply or Cancel');refresh();}
function applyShape(){if(pending?.kind!=='shape'||editDrag)return false;const q=pending;try{const next=addStroke(q.baseHistory,q.stroke);pending=null;$('shape-controls').hidden=true;changed(next);status('Shape applied');return true;}catch(e){status(e.message,true);refresh();return false;}}
function cancelShape(){editDrag?.cancel();if(pending?.kind!=='shape')return;pending=null;$('shape-controls').hidden=true;status('Shape cancelled');refresh();}
function localHistory(kind){if(!pending)return false;const from=kind==='undo'?pending.localPast:pending.localFuture,to=kind==='undo'?pending.localFuture:pending.localPast;if(!from.length){status('No '+kind+' in current edit');return true;}if(!historyCapacity([...h.past,...h.future,...from.slice(0,-1),...to,editState()]))return true;if(pending.kind==='transform'){to.push({...pending.params});pending.params=from.pop();pending.preview=transformSelection(pending.baseHistory,pending.ids,pending.params);syncTransformInputs();}else{to.push(structuredClone(pending.recognized));pending.recognized=from.pop();pending.stroke={...pending.stroke,points:pending.recognized.points.map(p=>({...p}))};syncShapeInputs();}refresh();return true;}
function historyAction(kind){if(active||busy||layerDrag||opacityDraft||editDrag||curveUI?.editing()||touchTracker.snapshot())return false;if(pending)return localHistory(kind);const next=kind==='undo'?undo(h):redo(h);if(next===h){status('No '+kind+' history');return true;}changed(next);status(kind==='undo'?'Undo':'Redo');return true;}
$('transform-selection').onclick=beginTransform;$('apply-transform').onclick=applyTransform;$('cancel-transform').onclick=cancelTransform;$('apply-shape').onclick=applyShape;$('cancel-shape').onclick=cancelShape;
for(const id of ['transform-x','transform-y','transform-scale','transform-angle'])$(id).addEventListener('change',()=>{if(pending?.kind!=='transform')return;updateTransform({dx:Number($('transform-x').value),dy:Number($('transform-y').value),scale:Number($('transform-scale').value)/100,angle:Number($('transform-angle').value)},true);});
for(const id of ['shape-x1','shape-y1','shape-x2','shape-y2','shape-cx','shape-cy','shape-radius'])$(id).addEventListener('change',()=>{if(pending?.kind!=='shape')return;const q=pending.recognized;updateShape(q.kind==='line'?{x1:Number($('shape-x1').value),y1:Number($('shape-y1').value),x2:Number($('shape-x2').value),y2:Number($('shape-y2').value)}:{cx:Number($('shape-cx').value),cy:Number($('shape-cy').value),radius:Number($('shape-radius').value)},true);});
function bindEditHandle(id,kind){const el=$(id);let drag=null;el.addEventListener('pointerdown',e=>{if(e.button!==0||editDrag)return;if(kind.startsWith('transform')&&pending?.kind!=='transform'||kind.startsWith('shape')&&pending?.kind!=='shape')return;e.preventDefault();e.stopPropagation();drag={id:e.pointerId,before:editState()};if(!localCapacity(drag.before)){drag=null;return;}editDrag={cancel:()=>finish({pointerId:drag?.id},true)};try{el.setPointerCapture(e.pointerId);}catch{}});el.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const p=toDocument(pos(e).x,pos(e).y,view);if(kind==='transform-scale'){const b=selectionBounds(pending.baseHistory.board,pending.ids),center={x:b.cx+pending.params.dx,y:b.cy+pending.params.dy},base=Math.hypot(b.maxX-b.cx,b.maxY-b.cy)||1;updateTransform({scale:Math.max(.05,Math.min(20,Math.hypot(p.x-center.x,p.y-center.y)/base))});}else if(kind==='transform-rotate'){const b=selectionBounds(pending.baseHistory.board,pending.ids),center={x:b.cx+pending.params.dx,y:b.cy+pending.params.dy};updateTransform({angle:Math.max(-360,Math.min(360,Math.atan2(p.y-center.y,p.x-center.x)*180/Math.PI+90))});}else if(kind==='shape-a'){const q=pending.recognized;if(q.kind==='line')updateShape({x1:p.x,y1:p.y});else updateShape({cx:p.x,cy:p.y});}else if(kind==='shape-b'){const q=pending.recognized;if(q.kind==='line')updateShape({x2:p.x,y2:p.y});else updateShape({radius:Math.hypot(p.x-q.center.x,p.y-q.center.y)});}});const finish=(e,cancelled=false)=>{if(!drag||drag.id!==e.pointerId)return;const before=drag.before;drag=null;editDrag=null;if(cancelled||!localRecord(before))restoreEdit(before);refresh();};el.addEventListener('pointerup',e=>finish(e));el.addEventListener('pointercancel',e=>finish(e,true));el.addEventListener('lostpointercapture',e=>finish(e,true));}
bindEditHandle('transform-scale-handle','transform-scale');bindEditHandle('transform-rotate-handle','transform-rotate');bindEditHandle('shape-handle-a','shape-a');bindEditHandle('shape-handle-b','shape-b');
const historyHold=createHistoryHold({step:kind=>{if(!h||!(kind==='undo'?(pending?pending.localPast.length:h.past.length):(pending?pending.localFuture.length:h.future.length)))return false;return historyAction(kind);}});
for(const kind of ['undo','redo']){const button=$(kind);let suppress=false;button.addEventListener('pointerdown',e=>{if(e.button!==0||button.disabled)return;historyHold.begin(e.pointerId,kind);});button.addEventListener('pointerup',e=>{suppress=historyHold.end(e.pointerId);});button.addEventListener('pointercancel',()=>historyHold.abort());button.addEventListener('pointerleave',()=>historyHold.abort());button.addEventListener('click',e=>{if(suppress){e.preventDefault();suppress=false;return;}historyAction(kind);});}
$('title').onchange=()=>act(()=>command(h,b=>b.title=$('title').value));$('add-layer').onclick=()=>editLayer('add');$('clear-layer').onclick=()=>{if(h)editLayer('clear',h.board.activeLayer);};
for(const id of ['paper','paper-color','spacing'])$(id).onchange=()=>act(()=>command(h,b=>{b.paper.kind=$('paper').value;b.paper.color=$('paper-color').value;b.paper.spacing=Number($('spacing').value);}));
const popovers=['actions-popover','pen-settings-popover','selection-controls','brush-popover','smudge-popover','eraser-popover','colour-popover','inspector'];
function closePopovers(){if(blocked())return;const penSettingsOpen=!$('pen-settings-popover').hidden;for(const id of popovers)$(id).hidden=true;$('inspector').dataset.open='false';for(const id of ['actions-toggle','pen-settings-toggle','pen','smudge','eraser','colour-toggle','layers-toggle','panels'])$(id).setAttribute('aria-expanded','false');if(penSettingsOpen)$('actions-toggle').focus();}
function togglePopover(id,trigger,allowClose=true){if(blocked())return;const opening=$(id).hidden||!allowClose;closePopovers();if(opening){$(id).hidden=false;$(trigger).setAttribute('aria-expanded','true');if(id==='inspector'){$('inspector').dataset.open='true';$('panels').setAttribute('aria-expanded','true');panels();}if(id==='brush-popover')sample();if(id==='pen-settings-popover')$('global-pen-barrel-map').focus();}}
$('actions-toggle').onclick=()=>togglePopover('actions-popover','actions-toggle');$('pen-settings-toggle').onclick=()=>togglePopover('pen-settings-popover','pen-settings-toggle');$('close-pen-settings').onclick=()=>{closePopovers();$('actions-toggle').focus();};$('colour-toggle').onclick=()=>togglePopover('colour-popover','colour-toggle');$('layers-toggle').onclick=()=>togglePopover('inspector','layers-toggle');$('panels').onclick=()=>togglePopover('inspector','layers-toggle');$('close-panels').onclick=()=>{closePopovers();$('layers-toggle').focus();};
$('modifiers-toggle').onclick=()=>{if(blocked())return;$('tools').hidden=!$('tools').hidden;$('modifiers-toggle').setAttribute('aria-expanded',String(!$('tools').hidden));};
document.addEventListener('keydown',e=>{if((active||busy||editDrag||touchTracker.snapshot()||curveUI?.editing())&&e.key!=='Escape'&&e.target.closest('button,input,select,summary,.layer')){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('pointerdown',e=>{if(e.target.closest('#canvas')){if(pending?.kind==='shape'&&!editDrag&&e.pointerType==='mouse'){applyShape();e.preventDefault();e.stopImmediatePropagation();return;}if(pending?.kind==='transform'&&e.pointerType!=='touch'){status('Apply or Cancel the current edit first');e.preventDefault();e.stopImmediatePropagation();return;}if(layerDrag||opacityDraft){e.preventDefault();e.stopImmediatePropagation();return;}if(!active&&!busy&&popovers.some(id=>!$(id).hidden)){closePopovers();e.preventDefault();e.stopImmediatePropagation();}return;}if((active||busy||editDrag||touchTracker.snapshot()||curveUI?.editing())&&e.target.closest('button,input,select,summary,.layer')){e.preventDefault();e.stopImmediatePropagation();}},true);

const pos=e=>{const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
const point=(e,released=false)=>({...toDocument(pos(e).x,pos(e).y,view),pressure:e.pointerType==='pen'?released&&active?.stroke?active.stroke.points.at(-1).pressure:Math.max(0,Math.min(1,e.pressure)):null});
function report(e){$('input').textContent=e.pointerType==='pen'?'Pen · reported pressure '+e.pressure.toFixed(2):e.pointerType==='touch'?(tool==='smudge'?'Touch · smudge':'Touch · navigation only'):'Mouse · pressure unavailable';if(e.pointerType!=='pen')return;penObserved.buttons=e.buttons;if(e.type!=='pointerup'&&e.type!=='pointercancel'&&(e.pressure>0||(e.buttons&1)!==0)){penObserved.count=Math.min(100000,penObserved.count+1);penObserved.latest=e.pressure;penObserved.min=Math.min(penObserved.min,e.pressure);penObserved.max=Math.max(penObserved.max,e.pressure);}const q=penObserved;$('pen-status').textContent=q.count?'Pen · latest '+q.latest.toFixed(2)+' · range '+q.min.toFixed(2)+'–'+q.max.toFixed(2)+' · '+(q.max-q.min>.01?'varying pressure observed':'constant report · hardware support unconfirmed')+' · buttons '+q.buttons:'Pen hover · buttons '+q.buttons+' · no contact pressure samples yet';}
function cancel(){const prior=active;editDrag?.cancel();touchPicked=null;touchBaseView=null;touchAnchor=null;if(active?.shapeTimer)clearTimeout(active.shapeTimer);if(active?.captureLostTimer)clearTimeout(active.captureLostTimer);if(active?.lasso)selected=active.prior;if(active?.erase)status('Eraser gesture cancelled');active=null;contacts.clear();touchTracker.cancel();gestureClipboardPending=false;$('gesture-clipboard').hidden=true;clearTouchHold();restorePenTool(prior);refresh();}
function sweep(p){try{active.sweeps.push({a:active.last,b:p});active.last=p;active.erased=eraseGesture(active.base,active.mode,active.sweeps,active.radius);refresh();}catch(e){cancel();status(e.message,true);}}
function beginSmudge(e){
 try{const l=editable(h.board),config=smudgeUI.snapshot();if(l.opacity===0||config.strength===0){status('Smudge strength or layer opacity is 0 · no change');return;}
 const first=point(e),snapshot=renderer.snapshotLayer(l,config.size,first);if(!snapshot){status('Draw on the active layer before smudging');return;}
 config.recipe=recipeUI.snapshot(config.brushPreset);config.dynamics={...structuredClone(penConfig.dynamics),opacity:true};active={id:e.pointerId,smudge:createSmudgeSession(snapshot,config,first),base:h.board,frozenView:{...view},finger:e.pointerType==='touch'};try{canvas.setPointerCapture(e.pointerId);}catch{}status('Smudging active layer · release to keep, Escape to cancel');refresh();
 }catch(err){active=null;contacts.delete(e.pointerId);status(err.message,true);}}
function smudgeMove(e){if(!active?.smudge)return;try{active.smudge.advance(point(e));if(active.smudge.changed)active.smudgeDirty=true;schedulePaint();}catch(err){cancel();status(err.message,true);}}
function smudgeFinish(e,cancelled=false){if(!active?.smudge||active.id!==e.pointerId)return;const done=active;if(!cancelled)smudgeMove(e);if(active!==done)return;if(!cancelled)smudgePreview(done);active=null;contacts.delete(e.pointerId);if(!cancelled&&done.smudged)try{changed(command(h,b=>{b.version=4;b.layers=done.smudged.layers;}),true);status('Smudged · layer converted to pixels · Undo restores strokes');}catch(err){status(err.message,true);}refresh();}
function clearTouchHold(){clearTimeout(touchHoldTimer);touchHoldTimer=null;}
function sampledHex(p){const r=canvas.getBoundingClientRect(),x=Math.max(0,Math.min(canvas.width-1,Math.floor(p.x*canvas.width/Math.max(1,r.width)))),y=Math.max(0,Math.min(canvas.height-1,Math.floor(p.y*canvas.height/Math.max(1,r.height)))),d=canvas.getContext('2d').getImageData(x,y,1,1).data;return '#'+[d[0],d[1],d[2]].map(v=>v.toString(16).padStart(2,'0')).join('');}
function armTouchHold(p){clearTouchHold();touchAnchor={...p};touchHoldTimer=setTimeout(()=>{const q=touchTracker.snapshot();if(!pending&&!active&&!busy&&!editDrag&&q?.maxCount===1&&q.active.length===1){touchPicked=sampledHex(q.active[0].current);status('Colour sampled '+touchPicked+' · release to use');}},TOUCH_LIMITS.holdMs);}
function touchDown(e){if(e.pointerType!=='touch')return;e.preventDefault();e.stopImmediatePropagation();canvas.focus();const p=pos(e);contacts.set(e.pointerId,p);report(e);
 if(busy||layerDrag||opacityDraft||editDrag)return;if(active?.smudge&&active.finger){active=null;touchBaseView={...view};for(const [id,q] of contacts)if(id!==e.pointerId)touchTracker.down(id,q.x,q.y,e.timeStamp);renderer.invalidate();status('Smudge cancelled · two fingers navigate');refresh();}if(!active&&tool==='smudge'&&!pending&&contacts.size===1&&!touchTracker.snapshot()&&!curveUI?.editing()){beginSmudge(e);return;}if(active){if(active.recognized&&!active.shapeModifier){active.shapeModifier=e.pointerId;status('Shape constraint active');}return;}
 if(!touchTracker.snapshot())touchBaseView={...view};const s=touchTracker.down(e.pointerId,p.x,p.y,e.timeStamp);touchPicked=null;clearTouchHold();if(s.maxCount===1&&!pending)armTouchHold(p);
}
function touchMove(e){if(e.pointerType!=='touch')return;e.preventDefault();e.stopImmediatePropagation();const p=pos(e);if(active?.smudge&&active.id===e.pointerId){contacts.set(e.pointerId,p);smudgeMove(e);return;}if(active){contacts.set(e.pointerId,p);return;}if(!contacts.has(e.pointerId))return;contacts.set(e.pointerId,p);const q=touchTracker.move(e.pointerId,p.x,p.y);const s=q.state;if(threeFingerClipboardSwipe(s))gestureClipboardPending=true;if(pending||editDrag){status('Apply or Cancel the current edit first');return;}if(touchPicked&&s?.maxCount===1){touchPicked=sampledHex(p);status('Colour sampled '+touchPicked+' · release to use');return;}if(s?.maxCount===1&&touchAnchor&&Math.hypot(p.x-touchAnchor.x,p.y-touchAnchor.y)>8)armTouchHold(p);if(!s?.moved||s.maxCount>2)return;const pts=s.active;if(pts.length===1){const a=pts[0];view={...touchBaseView,x:touchBaseView.x+a.current.x-a.start.x,y:touchBaseView.y+a.current.y-a.start.y};}
 else if(pts.length===2){const a=pts[0],b=pts[1],oldD=Math.hypot(a.start.x-b.start.x,a.start.y-b.start.y),newD=Math.hypot(a.current.x-b.current.x,a.current.y-b.current.y),oc={x:(a.start.x+b.start.x)/2,y:(a.start.y+b.start.y)/2},nc={x:(a.current.x+b.current.x)/2,y:(a.current.y+b.current.y)/2};let v=oldD>1?zoomAt(touchBaseView,oc.x,oc.y,touchBaseView.scale*newD/oldD):{...touchBaseView};v.x+=nc.x-oc.x;v.y+=nc.y-oc.y;view=v;}refresh();}
function setFocusMode(on){if(on)closePopovers();document.body.classList.toggle('focus-mode',on);$('focus-exit').hidden=!on;status(on?'Focus mode · three-finger hold to exit':'Editing controls restored');refresh();}
$('focus-exit').addEventListener('click',()=>setFocusMode(false));
function touchEnd(e,cancelled=false){if(e.pointerType!=='touch')return;e.preventDefault();e.stopImmediatePropagation();contacts.delete(e.pointerId);if(active?.smudge&&active.id===e.pointerId){smudgeFinish(e,cancelled);return;}if(active?.shapeModifier===e.pointerId){active.shapeModifier=null;status('Shape constraint released');return;}if(active)return;clearTouchHold();if(cancelled){touchTracker.cancel();touchPicked=null;touchBaseView=null;touchAnchor=null;gestureClipboardPending=false;return;}const r=touchTracker.up(e.pointerId,e.timeStamp);if(r.finished){if(gestureClipboardPending){gestureClipboardPending=false;openGestureClipboard();}else if(touchPicked&&r.ended?.count===1){touchPicked=sampledHex(pos(e));u2.setColour(touchPicked,true);status('Colour '+touchPicked+' selected');sample();}else if(threeFingerFocusToggle(r.ended,TOUCH_LIMITS.holdMs)){if(!pending&&!busy){setFocusMode(!document.body.classList.contains('focus-mode'));}}else if(twoFingerViewReset(r.ended,TOUCH_LIMITS.holdMs)){if(!pending&&!busy){view=fitArtworkView(h.board,canvas.clientWidth,canvas.clientHeight);status('Fit artwork · two-finger hold');}}else if(r.action)historyAction(r.action);else if(pending?.kind==='shape'&&r.ended?.count===1&&r.ended.candidate&&r.ended.duration<=TOUCH_LIMITS.durationMs)applyShape();touchPicked=null;touchBaseView=null;touchAnchor=null;}refresh();}
canvas.addEventListener('pointerdown',touchDown,true);canvas.addEventListener('pointermove',touchMove,true);canvas.addEventListener('pointerup',e=>touchEnd(e),true);canvas.addEventListener('pointercancel',e=>touchEnd(e,true),true);canvas.addEventListener('lostpointercapture',e=>{if(active?.smudge&&active.finger&&active.id===e.pointerId)smudgeFinish(e,true);else if(touchTracker.snapshot()?.active.some(c=>c.id===e.pointerId))touchEnd(e,true);},true);
function armShapeHoldAt(cssPoint){if(!active?.stroke||active.recognized)return;if(active.shapeTimer)clearTimeout(active.shapeTimer);active.shapeAnchor={...cssPoint};active.shapeTimer=setTimeout(()=>{if(!active?.stroke||active.recognized)return;const q=recognizeHeldShape(active.stroke.points,active.frozenView?.scale||view.scale);if(!q)return;active.recognized=q;active.stroke={...active.stroke,points:q.points.map(p=>({...p}))};status(q.kind==='line'?'Line recognized · release to edit':'Circle recognized · release to edit');schedulePaint();},650);}
function startPointer(e){
 if(!h||busy||opacityDraft||layerDrag||editDrag||touchTracker.snapshot()||active||curveUI?.editing())return;
 const mapped=penAction(e,penConfig.mappings);if(e.pointerType==='touch'||e.pointerType!=='pen'&&e.button!==0||e.pointerType==='pen'&&e.button!==0&&!mapped)return;
 if(e.pointerType==='pen'&&e.pressure===0&&!(e.buttons&1))return;
 if(pending){if(pending.kind==='shape'&&e.pointerType==='pen'){if(!applyShape())return;}else{status('Apply or Cancel the current edit first');return;}}
 canvas.focus();report(e);try{canvas.setPointerCapture(e.pointerId);}catch{}const p=pos(e);contacts.set(e.pointerId,p);
 let operation=mapped||tool;const previousTool=tool,previousAutoMove=lassoAutoMove;if(operation==='lasso'&&insideSelection(point(e)))operation='move';
 if(mapped)setTool(operation);const owned=a=>mapped?{...a,previousTool,previousAutoMove,moveAdmitted:e.type==='pointermove'}:a;
 if(operation==='pan'||space){active=owned({id:e.pointerId,pan:p});return;}
 try{editable(h.board);}catch(err){if(mapped)restorePenTool({previousTool,previousAutoMove});status(err.message,true);return;}
 if(operation==='lasso'){active=owned({id:e.pointerId,lasso:true,polygon:[point(e)],prior:[...selected],frozenView:{...view}});refresh();return;}
 if(operation==='move'){const q=point(e);if(!insideSelection(q)){status('Drag inside the selected box to move');if(mapped)restorePenTool({previousTool,previousAutoMove});return;}active=owned({id:e.pointerId,move:true,baseHistory:h,ids:[...selected],start:q,frozenView:{...view},dx:0,dy:0});refresh();return;}
 if(operation==='smudge'){beginSmudge(e);return;}
 if(operation==='eraser'){active=owned({id:e.pointerId,erase:true,mode:$('erase-mode').value,radius:settings.size/2,base:h.board,sweeps:[],last:point(e),erased:h.board});sweep(point(e));return;}
 if(settings.opacity===0){status('Invisible ink (0%) · no stroke added');return;}
 active={id:e.pointerId,stroke:{id:crypto.randomUUID(),...structuredClone(settings),dynamics:structuredClone(settings.dynamics),points:[point(e)]},frozenView:{...view},shapeAnchor:p,shapeTimer:null,recognized:null,shapeModifier:null};armShapeHoldAt(p);refresh();
}
canvas.addEventListener('pointerdown',startPointer);
for(const el of [canvas,$('selection-overlay')])el.addEventListener('contextmenu',e=>{e.preventDefault();});
canvas.addEventListener('pointermove',e=>{report(e);const p=pos(e);if(active?.id===e.pointerId&&active.captureLost){if(e.pointerType==='pen'&&e.buttons===0&&e.pressure===0)finish(e);else cancel();return;}if(e.pointerType==='pen'&&!active&&!pending&&!blocked()){if(lassoAutoMove&&(tool==='lasso'||tool==='move')){const inside=insideSelection(point(e));setTool(inside?'move':'lasso');lassoAutoMove=true;canvas.style.cursor=inside?'move':'';}if(penAction(e,penConfig.mappings)&&(e.pressure>0||(e.buttons&1)!==0))startPointer(e);}if(e.pointerType==='pen'&&active?.id===e.pointerId&&e.pressure===0&&!(e.buttons&1)){finish(e);return;}if(e.pointerType==='touch'){if(!contacts.has(e.pointerId))return;const before=[...contacts.entries()],old=contacts.get(e.pointerId);contacts.set(e.pointerId,p);if(active)return;if(contacts.size===1){view.x+=p.x-old.x;view.y+=p.y-old.y;}else if(contacts.size===2){const a=before[0][1],b=before[1][1],now=[...contacts.values()],oldD=Math.hypot(a.x-b.x,a.y-b.y),newD=Math.hypot(now[0].x-now[1].x,now[0].y-now[1].y),center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(oldD>1)view=zoomAt(view,center.x,center.y,view.scale*newD/oldD);view.x+=(now[0].x+now[1].x)/2-center.x;view.y+=(now[0].y+now[1].y)/2-center.y;}refresh();return;}if(!active||active.id!==e.pointerId)return;if(active.smudge){smudgeMove(e);return;}if(active.pan){view.x+=p.x-active.pan.x;view.y+=p.y-active.pan.y;active.pan=p;}else if(active.erase)sweep(point(e));else if(active.lasso||active.move){try{if(active.lasso)lassoPoint(e);else movePreview(e);}catch(err){cancel();status(err.message,true);}}else if(active.recognized){const pt=gesturePoint(e);active.recognized=reshapeRecognized(active.recognized,pt,{snap15:!!active.shapeModifier});active.stroke={...active.stroke,points:active.recognized.points.map(p=>({...p}))};}else{const events=e.getCoalescedEvents?.()||[e];for(const q of events.length?events:[e]){const pt=point(q);if(active.stroke.points.length>=limits.points){cancel();status('Stroke point limit reached; gesture cancelled',true);break;}active.stroke.points.push(pt);}if(active?.stroke&&Math.hypot(p.x-active.shapeAnchor.x,p.y-active.shapeAnchor.y)>8)armShapeHoldAt(p);}if(active?.stroke)schedulePaint();else refresh();});
function finish(e,cancelled=false){if(active?.smudge){smudgeFinish(e,cancelled);return;}contacts.delete(e.pointerId);if(!active||active.id!==e.pointerId)return;if(!cancelled){if(active.lasso||active.move){try{if(active.lasso)lassoPoint(e);else movePreview(e);}catch(err){cancel();status(err.message,true);return;}}else if(active.erase)sweep(point(e));else if(active.stroke){if(active.recognized){active.recognized=reshapeRecognized(active.recognized,gesturePoint(e),{snap15:!!active.shapeModifier});active.stroke={...active.stroke,points:active.recognized.points.map(p=>({...p}))};}else{const p=point(e,true),last=active.stroke.points.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)>1e-7)active.stroke.points.push(p);}}}if(!active)return;if(active.shapeTimer)clearTimeout(active.shapeTimer);if(active.captureLostTimer)clearTimeout(active.captureLostTimer);const done=active;active=null;restorePenTool(done);if(cancelled&&done.lasso)selected=done.prior;if(!cancelled){try{if(done.lasso){selected=selectLasso(h.board,done.polygon);status(selected.length+' strokes selected');}if(done.move&&done.moved)changed(done.moved,false,true);if(done.stroke&&done.recognized)beginShapeDraft(done);else if(done.stroke)changed(addStroke(h,done.stroke));if(done.erase&&done.erased!==done.base)changed(command(h,b=>{b.layers=done.erased.layers;}));}catch(err){if(done.lasso)selected=done.prior;status(err.message,true);}}refresh();if(!$('inspector').hidden)panels();}
canvas.addEventListener('pointerup',e=>finish(e,!!active?.captureLost));canvas.addEventListener('pointercancel',e=>finish(e,true));canvas.addEventListener('lostpointercapture',e=>{if(active?.id===e.pointerId&&active.moveAdmitted&&e.pointerType==='pen'&&e.buttons===0&&e.pressure===0){const owner=active;owner.captureLost=true;owner.captureLostTimer=setTimeout(()=>{if(active===owner)cancel();},0);return;}finish(e,true);});window.addEventListener('blur',cancel);
canvas.addEventListener('wheel',e=>{e.preventDefault();if(blocked()){if(pending)status('Apply or Cancel the current edit first');return;}const p=pos(e);view=zoomAt(view,p.x,p.y,view.scale*Math.exp(-e.deltaY*.002));refresh();},{passive:false});$('reset-view').onclick=()=>{if(blocked()){if(pending)status('Apply or Cancel the current edit first');return;}view={x:0,y:0,scale:1};refresh();};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelLayerGesture?.();cancelOpacity();if(pending?.kind==='shape')cancelShape();else if(pending?.kind==='transform')cancelTransform();else{cancel();closePopovers();}return;}if(e.key==='Enter'&&pending&&!editDrag){e.preventDefault();if(e.target.closest('input'))e.target.blur();if(pending?.kind==='shape')applyShape();else applyTransform();return;}if(e.target.closest('input,select,textarea,dialog'))return;if(e.code==='Space'){e.preventDefault();space=true;}if((e.ctrlKey||e.metaKey)&&['c','x','v'].includes(e.key.toLowerCase())){e.preventDefault();selectionAction({c:'copy',x:'cut',v:'paste'}[e.key.toLowerCase()]);return;}if((e.key==='t'||e.key==='T'||e.key==='v'||e.key==='V')&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();beginTransform();return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();selectionAction('delete');}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();historyAction(e.shiftKey?'redo':'undo');}});window.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});
async function transition(fn){if(pending){status('Apply or Cancel the current edit first');return;}if(blocked())return;busy=true;try{if(!await saveNow())return;await fn();}catch(e){status(e.message,true);}finally{busy=false;refresh();}}
async function openBoard(id){const r=await store.load(id);await store.select(id);selected=[];h=createHistory(r.board);expected=r.dbRevision;saved=r.recovered?-1:h.board.revision;view={x:0,y:0,scale:1};status(r.recovered?'Recovered previous version · Export before continuing':'Saved on this device');refresh();panels();}
async function newBoard(){const b=createBoard();expected=await store.save(b,0);selected=[];h=createHistory(b);saved=0;view={x:0,y:0,scale:1};status('Saved on this device');refresh();panels();}
$('new').onclick=()=>transition(newBoard);$('boards').onclick=async()=>{if(blocked()||!store)return;try{const records=await store.list();$('board-list').replaceChildren();for(const r of records){const row=document.createElement('div');row.className='board-row';const btn=document.createElement('button');btn.textContent=r.current?.title||'Damaged board';btn.onclick=()=>transition(async()=>{await openBoard(r.id);$('gallery').close();});row.append(btn);$('board-list').append(row);}$('gallery').showModal();}catch(e){status(e.message,true);}};$('close-gallery').onclick=()=>{if(!blocked())$('gallery').close();};
$('export').onclick=()=>{if(blocked()||!h)return;const url=URL.createObjectURL(new Blob([JSON.stringify(h.board)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=h.board.title.replace(/[^a-z0-9_-]/gi,'_')+'.unruly.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>{if(blocked())return;$('import-file').click();};$('import-file').onchange=async()=>{const file=$('import-file').files[0];$('import-file').value='';if(!file)return;try{if(file.size>limits.bytes)throw Error('Import exceeds 8 MiB');const board=importDocument(await file.text());await transition(async()=>{const revision=await store.save(board,0);selected=[];h=createHistory(board);expected=revision;saved=0;view={x:0,y:0,scale:1};status('Imported as a new board · Saved on this device');refresh();panels();});}catch(e){status('Import rejected · '+e.message,true);}};
new ResizeObserver(()=>{refresh();sample();}).observe(canvas);window.addEventListener('beforeunload',e=>{if(active||pending||h&&saved!==h.board.revision){e.preventDefault();e.returnValue='';}});
async function startup(){try{store=await openStore();store.db.onversionchange=()=>{store.close();store=null;status('Storage changed · reopen page',true);};const migration=await store.migrateLegacy();let last=await store.last();if(!last){const records=await store.list();last=records[0]?.id;}if(last)await openBoard(last);else if(migration.hadSources&&migration.errors.length){h=createHistory(createBoard(undefined,'Recovery workspace'));expected=0;saved=-1;refresh();panels();status('Old boards need recovery · originals intact. Export any recovered work before continuing.',true);}else await newBoard();if(migration.errors.length)status('Some old boards could not be copied; originals preserved. '+migration.errors[0].message,true);else if(migration.warnings?.length)status('Recovery warning · '+migration.warnings[0].message,true);else if(migration.copied)status('Copied '+migration.copied+' old boards · originals preserved');navigator.storage?.persist?.().catch(()=>{});}catch(e){status('Storage/recovery error · '+e.message,true);if(!h){h=createHistory(createBoard(undefined,'Recovery workspace'));refresh();panels();}}}
async function offline(){if(!('serviceWorker'in navigator)){$('offline').textContent='Offline caching unavailable';return;}try{const r=await navigator.serviceWorker.register('./sw.js');const observe=w=>w?.addEventListener('statechange',()=>{if(w.state==='redundant')$('offline').textContent='Offline setup failed · stay online';});observe(r.installing);r.addEventListener('updatefound',()=>observe(r.installing));await navigator.serviceWorker.ready;$('offline').textContent='Ready for offline use';const check=()=>{if(r.waiting){waitingWorker=r.waiting;$('update').hidden=false;}};check();r.addEventListener('updatefound',()=>r.installing?.addEventListener('statechange',check));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(requestedUpdate)location.reload();});}catch{$('offline').textContent='Offline setup failed · stay online';}}
$('update').onclick=async()=>{if(blocked()||contacts.size){status('Finish your stroke or selection gesture before updating');return;}await transition(async()=>{if(saved!==h.board.revision)return;if(waitingWorker){requestedUpdate=true;waitingWorker.postMessage({type:'ACTIVATE_UPDATE'});}});};
startup();offline();

