import {limits,createBoard,createHistory,command,addStroke,editable,layerCommand,undo,redo,eraseGesture,importDocument,toDocument,zoomAt} from './model.js';
import {createRenderer} from './render.js';
import {openStore} from './storage.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),renderer=createRenderer(canvas),sampleRenderer=createRenderer($('sample'));
let store,h,expected=0,saved=-1,saveTimer,saveChain=Promise.resolve(),view={x:0,y:0,scale:1},tool='pen',settings={brush:'ink',size:5,opacity:1,color:'#203d48'},active=null,space=false,frame=0,busy=false,waitingWorker=null,requestedUpdate=false;
const contacts=new Map();
const status=(text,error=false)=>{$('save').textContent=text;$('save').dataset.error=String(error);};
function paint(){frame=0;if(!h)return;try{renderer.render(active?.erased||h.board,view,active?.stroke||null);}catch(e){status('Render limit · '+e.message,true);}}
function refresh(){if(!h)return;$('undo').disabled=!h.past.length;$('redo').disabled=!h.future.length;$('title').value=h.board.title;$('zoom').textContent=Math.round(view.scale*100)+'%';$('hint').hidden=h.board.layers.some(l=>l.strokes.length)||!!active;const l=h.board.layers.find(l=>l.id===h.board.activeLayer);$('layer-warning').textContent=l.locked||!l.visible?'Active layer is '+(l.locked?'locked':'hidden')+'. Select another layer to draw.':h.evicted?'Older undo states were released to keep memory bounded.':'';if(!frame)frame=requestAnimationFrame(paint);}
function panels(){const b=h.board;$('paper').value=b.paper.kind;$('paper-color').value=b.paper.color;$('spacing').value=b.paper.spacing;const list=$('layer-list');list.replaceChildren();for(const l of b.layers){const row=document.createElement('div');row.className='layer';row.dataset.active=String(l.id===b.activeLayer);row.dataset.layerId=l.id;const top=document.createElement('div');top.className='layer-top';const select=document.createElement('button');select.textContent=l.id===b.activeLayer?'Active':'Select';select.setAttribute('aria-label','Select '+l.name);select.onclick=()=>editLayer('select',l.id);const name=document.createElement('input');name.value=l.name;name.maxLength=64;name.setAttribute('aria-label','Layer name '+l.name);name.onchange=()=>editLayer('name',l.id,name.value);top.append(select,name);row.append(top);const actions=document.createElement('div');actions.className='layer-actions';for(const [action,text,value] of [['visible',l.visible?'Hide':'Show',!l.visible],['locked',l.locked?'Unlock':'Lock',!l.locked],['up','Up'],['down','Down'],['delete','Delete']]){const btn=document.createElement('button');btn.textContent=text;btn.setAttribute('aria-label',text+' '+l.name);btn.onclick=()=>editLayer(action,l.id,value);actions.append(btn);}row.append(actions);const label=document.createElement('label');label.textContent='Layer opacity · '+Math.round(l.opacity*100)+'%';const opacity=document.createElement('input');opacity.type='range';opacity.min=0;opacity.max=100;opacity.value=l.opacity*100;opacity.setAttribute('aria-label','Opacity '+l.name);opacity.oninput=()=>{label.textContent='Layer opacity · '+opacity.value+'%';};opacity.onchange=()=>editLayer('opacity',l.id,Number(opacity.value)/100);row.append(label,opacity);list.append(row);}}
function changed(next,updatePanels=false){if(next===h)return;h=next;status('Unsaved changes');clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,500);refresh();if(updatePanels)panels();}
function act(fn,updatePanels=true){if(active||busy)return;try{changed(fn(),updatePanels);}catch(e){status(e.message,true);refresh();}}
const editLayer=(action,id,value)=>act(()=>layerCommand(h,action,id,value));
function saveNow(){clearTimeout(saveTimer);if(!h)return Promise.resolve(false);const snapshot=structuredClone(h.board);saveChain=saveChain.catch(()=>false).then(async()=>{if(saved===snapshot.revision)return true;status('Saving…');try{if(!store)throw Error('Local storage unavailable');expected=await store.save(snapshot,expected);saved=snapshot.revision;status(saved===h.board.revision?'Saved on this device':'Unsaved changes');return true;}catch(e){status('Save failed · '+e.message,true);return false;}});return saveChain;}
function sample(){const b=createBoard('preview','Sample');b.paper.color='#f4f3ef';b.layers[0].strokes=[{id:'sample',...settings,points:[{x:16,y:30,pressure:null},{x:45,y:15,pressure:null},{x:80,y:35,pressure:null},{x:120,y:22,pressure:null},{x:165,y:28,pressure:null}]}];try{sampleRenderer.render(b,{x:0,y:0,scale:Math.min(1,$('sample').clientWidth/180)});}catch{}$('sample-label').textContent=settings.opacity===0?'Invisible ink (0%)':settings.brush[0].toUpperCase()+settings.brush.slice(1)+' · '+settings.size+' · '+Math.round(settings.opacity*100)+'%';}
function hexToHsl(hex){const [r,g,b]=hex.slice(1).match(/../g).map(s=>parseInt(s,16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min,l=(max+min)/2;let hue=0,s=0;if(delta){s=delta/(1-Math.abs(2*l-1));hue=max===r?((g-b)/delta)%6:max===g?(b-r)/delta+2:(r-g)/delta+4;hue=(hue*60+360)%360;}return [hue,s*100,l*100];}
function hslToHex(h,s,l){s/=100;l/=100;const a=s*Math.min(l,1-l);return '#'+[0,8,4].map(n=>{const k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0');}).join('');}
function setColor(value){if(!/^#[0-9a-f]{6}$/i.test(value)){status('Use a six-digit hex colour, for example #203d48',true);$('color').value=settings.color;return;}settings.color=value.toLowerCase();$('color').value=settings.color;const [a,b,c]=hexToHsl(value);$('hue').value=Math.round(a);$('saturation').value=Math.round(b);$('lightness').value=Math.round(c);$('hue-value').value=Math.round(a)+'°';for(const sw of $('swatches').children)sw.setAttribute('aria-pressed',String(sw.dataset.color===settings.color));sample();}
for(const c of ['#203d48','#171c24','#c14f43','#d69b28','#517a58','#4877a3','#8a63a2','#f2eee3']){const b=document.createElement('button');b.style.background=c;b.dataset.color=c;b.setAttribute('aria-label','Colour '+c);b.setAttribute('aria-pressed','false');b.onclick=()=>setColor(c);$('swatches').append(b);}
$('color').onchange=()=>setColor($('color').value);for(const id of ['hue','saturation','lightness'])$(id).oninput=()=>{settings.color=hslToHex(Number($('hue').value),Number($('saturation').value),Number($('lightness').value));$('color').value=settings.color;$('hue-value').value=$('hue').value+'°';for(const sw of $('swatches').children)sw.setAttribute('aria-pressed',String(sw.dataset.color===settings.color));sample();};
for(const [id,min,max,key,divisor] of [['size',1,40,'size',1],['opacity',0,100,'opacity',100]])for(const control of [id,id+'-number'])$(control).addEventListener(control===id?'input':'change',()=>{const value=Number($(control).value);if(!Number.isFinite(value)||value<min||value>max||$(control).value===''){status('Value must be '+min+' to '+max,true);$(control).value=settings[key]*divisor;return;}settings[key]=value/divisor;$(id).value=value;$(id+'-number').value=value;sample();});
$('brush').onchange=()=>{settings.brush=$('brush').value;sample();};for(const id of ['pen','eraser','pan'])$(id).onclick=()=>{if(active)return;tool=id;for(const name of ['pen','eraser','pan'])$(name).setAttribute('aria-pressed',String(name===id));$('brush-controls').hidden=id==='eraser';$('eraser-controls').hidden=id!=='eraser';};
$('undo').onclick=()=>act(()=>undo(h));$('redo').onclick=()=>act(()=>redo(h));$('title').onchange=()=>act(()=>command(h,b=>b.title=$('title').value));$('add-layer').onclick=()=>editLayer('add');
for(const id of ['paper','paper-color','spacing'])$(id).onchange=()=>act(()=>command(h,b=>{b.paper.kind=$('paper').value;b.paper.color=$('paper-color').value;b.paper.spacing=Number($('spacing').value);}));
$('panels').onclick=()=>{const open=$('inspector').dataset.open!=='true';$('inspector').dataset.open=String(open);$('panels').setAttribute('aria-expanded',String(open));};$('close-panels').onclick=()=>{$('inspector').dataset.open='false';$('panels').setAttribute('aria-expanded','false');};
const pos=e=>{const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
const point=e=>({...toDocument(pos(e).x,pos(e).y,view),pressure:e.pointerType==='pen'?Math.max(0,Math.min(1,e.pressure)):null});
function report(e){$('input').textContent=e.pointerType==='pen'?'Pen · reported pressure '+e.pressure.toFixed(2):e.pointerType==='touch'?'Touch · navigation only':'Mouse · pressure unavailable';}
function cancel(){if(active?.erase)status('Eraser gesture cancelled');active=null;contacts.clear();refresh();}
function sweep(p){try{active.sweeps.push({a:active.last,b:p});active.last=p;active.erased=eraseGesture(active.base,$('erase-mode').value,active.sweeps,settings.size/2);refresh();}catch(e){active=null;status(e.message,true);refresh();}}
canvas.addEventListener('pointerdown',e=>{if(!h||busy||e.button!==0)return;canvas.focus();report(e);try{canvas.setPointerCapture(e.pointerId);}catch{}const p=pos(e);contacts.set(e.pointerId,p);if(e.pointerType==='touch')return;if(active)return;if(tool==='pan'||space){active={id:e.pointerId,pan:p};return;}try{editable(h.board);}catch(err){status(err.message,true);return;}if(tool==='eraser'){active={id:e.pointerId,erase:true,base:h.board,sweeps:[],last:point(e),erased:h.board};sweep(point(e));return;}if(settings.opacity===0){status('Invisible ink (0%) · no stroke added');return;}active={id:e.pointerId,stroke:{id:crypto.randomUUID(),...settings,points:[point(e)]}};refresh();});
canvas.addEventListener('pointermove',e=>{report(e);const p=pos(e);if(e.pointerType==='touch'){if(!contacts.has(e.pointerId))return;const before=[...contacts.entries()],old=contacts.get(e.pointerId);contacts.set(e.pointerId,p);if(active)return;if(contacts.size===1){view.x+=p.x-old.x;view.y+=p.y-old.y;}else if(contacts.size===2){const a=before[0][1],b=before[1][1],now=[...contacts.values()],oldD=Math.hypot(a.x-b.x,a.y-b.y),newD=Math.hypot(now[0].x-now[1].x,now[0].y-now[1].y),center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(oldD>1)view=zoomAt(view,center.x,center.y,view.scale*newD/oldD);view.x+=(now[0].x+now[1].x)/2-center.x;view.y+=(now[0].y+now[1].y)/2-center.y;}refresh();return;}if(!active||active.id!==e.pointerId)return;if(active.pan){view.x+=p.x-active.pan.x;view.y+=p.y-active.pan.y;active.pan=p;}else if(active.erase)sweep(point(e));else{const events=e.getCoalescedEvents?.()||[e];for(const q of events.length?events:[e]){const pt=point(q);if(active.stroke.points.length>=limits.points){cancel();status('Stroke point limit reached; gesture cancelled',true);break;}active.stroke.points.push(pt);}}refresh();});
function finish(e,cancelled=false){contacts.delete(e.pointerId);if(!active||active.id!==e.pointerId)return;const done=active;active=null;if(!cancelled){try{if(done.stroke)changed(addStroke(h,done.stroke));if(done.erase&&done.erased!==done.base)changed(command(h,b=>{b.layers=done.erased.layers;}));}catch(err){status(err.message,true);}}refresh();}
canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,true));canvas.addEventListener('lostpointercapture',e=>finish(e,true));window.addEventListener('blur',cancel);
canvas.addEventListener('wheel',e=>{e.preventDefault();if(active)return;const p=pos(e);view=zoomAt(view,p.x,p.y,view.scale*Math.exp(-e.deltaY*.002));refresh();},{passive:false});$('reset-view').onclick=()=>{if(active)return;view={x:0,y:0,scale:1};refresh();};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){cancel();$('close-panels').click();return;}if(e.target.closest('input,select,textarea,dialog'))return;if(e.code==='Space'){e.preventDefault();space=true;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();act(()=>e.shiftKey?redo(h):undo(h));}});window.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});
async function transition(fn){if(active||busy)return;busy=true;try{if(!await saveNow())return;await fn();}catch(e){status(e.message,true);}finally{busy=false;}}
async function openBoard(id){const r=await store.load(id);h=createHistory(r.board);expected=r.dbRevision;saved=r.recovered?-1:h.board.revision;view={x:0,y:0,scale:1};status(r.recovered?'Recovered previous version · Export before continuing':'Saved on this device');refresh();panels();}
async function newBoard(){const b=createBoard();expected=await store.save(b,0);h=createHistory(b);saved=0;view={x:0,y:0,scale:1};status('Saved on this device');refresh();panels();}
$('new').onclick=()=>transition(newBoard);$('boards').onclick=async()=>{if(!store)return;try{const records=await store.list();$('board-list').replaceChildren();for(const r of records){const row=document.createElement('div');row.className='board-row';const btn=document.createElement('button');btn.textContent=r.current?.title||'Damaged board';btn.onclick=()=>transition(async()=>{await openBoard(r.id);$('gallery').close();});row.append(btn);$('board-list').append(row);}$('gallery').showModal();}catch(e){status(e.message,true);}};$('close-gallery').onclick=()=>$('gallery').close();
$('export').onclick=()=>{if(!h)return;const url=URL.createObjectURL(new Blob([JSON.stringify(h.board,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=h.board.title.replace(/[^a-z0-9_-]/gi,'_')+'.unruly.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>{if(active||busy)return;$('import-file').click();};$('import-file').onchange=async()=>{const file=$('import-file').files[0];$('import-file').value='';if(!file)return;try{if(file.size>limits.bytes)throw Error('Import exceeds 8 MiB');const board=importDocument(await file.text());await transition(async()=>{const revision=await store.save(board,0);h=createHistory(board);expected=revision;saved=0;view={x:0,y:0,scale:1};status('Imported as a new board · Saved on this device');refresh();panels();});}catch(e){status('Import rejected · '+e.message,true);}};
new ResizeObserver(()=>{refresh();sample();}).observe(canvas);window.addEventListener('beforeunload',e=>{if(active||h&&saved!==h.board.revision){e.preventDefault();e.returnValue='';}});
async function startup(){try{store=await openStore();store.db.onversionchange=()=>{store.close();store=null;status('Storage changed · reopen page',true);};const migration=await store.migrateLegacy();let last=await store.last();if(!last){const records=await store.list();last=records[0]?.id;}if(last)await openBoard(last);else await newBoard();if(migration.errors.length)status('Some old boards could not be copied; originals preserved. '+migration.errors[0].message,true);else if(migration.copied)status('Copied '+migration.copied+' old boards · originals preserved');navigator.storage?.persist?.().catch(()=>{});}catch(e){status('Storage/recovery error · '+e.message,true);if(!h){h=createHistory(createBoard(undefined,'Recovery workspace'));refresh();panels();}}}
async function offline(){if(!('serviceWorker'in navigator)){$('offline').textContent='Offline caching unavailable';return;}try{const r=await navigator.serviceWorker.register('./sw.js');const observe=w=>w?.addEventListener('statechange',()=>{if(w.state==='redundant')$('offline').textContent='Offline setup failed · stay online';});observe(r.installing);r.addEventListener('updatefound',()=>observe(r.installing));await navigator.serviceWorker.ready;$('offline').textContent='Ready for offline use';const check=()=>{if(r.waiting){waitingWorker=r.waiting;$('update').hidden=false;}};check();r.addEventListener('updatefound',()=>r.installing?.addEventListener('statechange',check));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(requestedUpdate)location.reload();});}catch{$('offline').textContent='Offline setup failed · stay online';}}
$('update').onclick=async()=>{if(active||busy){status('Finish your stroke before updating');return;}await transition(async()=>{if(saved!==h.board.revision)return;if(waitingWorker){requestedUpdate=true;waitingWorker.postMessage({type:'ACTIVATE_UPDATE'});}});};
setColor(settings.color);startup();offline();
