import {selectLasso,selectionBounds,copySelection,deleteSelection,moveSelection,pasteSelection,transformSelection} from './selection.js';
import {limits,createBoard,createHistory,command,addStroke,editable,layerCommand,undo,redo,eraseGesture,importDocument,toDocument,zoomAt} from './model.js';
import {createRenderer} from './render.js';
import {openStore} from './storage.js';
import {presetLabel} from './brushes.js';
import {initU2UI} from './u2.js';
import {createTouchTracker,TOUCH_LIMITS} from './gestures.js';
import {recognizeHeldShape,reshapeRecognized,editRecognized} from './shapes.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),renderer=createRenderer(canvas);
let store,h,expected=0,saved=-1,saveTimer,saveChain=Promise.resolve(),view={x:0,y:0,scale:1},tool='pen',settings={brush:'ink',preset:'ink-fineliner',size:3,opacity:1,color:'#203d48'},active=null,space=false,frame=0,busy=false,waitingWorker=null,requestedUpdate=false;
let selected=[],clipboard=null,opacityDraft=null,layerDrag=null,pending=null;
const touchTracker=createTouchTracker();let touchHoldTimer=null,touchPicked=null,touchBaseView=null;
let cancelLayerGesture=null;
const thumbnails=new Map();
const blocked=()=>!!active||busy||!!layerDrag||!!opacityDraft||!!pending;
const contacts=new Map();
const status=(text,error=false)=>{$('save').textContent=text;$('save').dataset.error=String(error);};
function paint(){frame=0;if(!h)return;try{const board=pending?.kind==='transform'?pending.preview.board:opacityDraft?.board||active?.moved?.board||active?.erased||h.board;const live=pending?.kind==='shape'?pending.stroke:active?.stroke||null;renderer.render(board,view,live);}catch(e){status('Render limit · '+e.message,true);}}
function schedulePaint(){if(!frame)frame=requestAnimationFrame(paint);}
function refresh(){if(!h)return;selectionUI();geometryUI();$('undo').disabled=!h.past.length;$('redo').disabled=!h.future.length;$('title').value=h.board.title;$('zoom').textContent=Math.round(view.scale*100)+'%';$('hint').hidden=h.board.layers.some(l=>l.strokes.length)||!!active;const l=h.board.layers.find(l=>l.id===h.board.activeLayer);$('layer-warning').textContent=l.locked||!l.visible?'Active layer is '+(l.locked?'locked':'hidden')+'. Select another layer to draw.':h.evicted?'Older undo states were released to keep memory bounded.':'';schedulePaint();}
function panels(){
 if(!h||active||opacityDraft||layerDrag)return;
 const b=h.board;$('paper').value=b.paper.kind;$('paper-color').value=b.paper.color;$('spacing').value=b.paper.spacing;
 const list=$('layer-list');list.replaceChildren();
 const retained=new Set(b.layers.map(l=>l.id));for(const id of thumbnails.keys())if(!retained.has(id))thumbnails.delete(id);
 for(const l of [...b.layers].reverse()){
  const row=document.createElement('div');row.className='layer';row.dataset.active=String(l.id===b.activeLayer);row.dataset.layerId=l.id;
  const top=document.createElement('div');top.className='layer-top';
  const grip=document.createElement('button');grip.className='layer-grip';grip.textContent='⋮';grip.setAttribute('aria-label','Drag to reorder '+l.name);top.append(grip);
  const select=document.createElement('button');select.className='layer-select';select.setAttribute('aria-label','Select '+l.name);select.setAttribute('aria-pressed',String(l.id===b.activeLayer));
  const img=document.createElement('img');img.alt='';img.width=80;img.height=48;
  const cached=thumbnails.get(l.id);if(cached?.layer===l)img.src=cached.src;else try{img.src=renderer.thumbnail(l);thumbnails.set(l.id,{layer:l,src:img.src});}catch(e){status('Thumbnail unavailable · '+e.message,true);}
  const name=document.createElement('span');name.className='layer-name';name.textContent=l.name+(l.locked?' · locked':'');select.append(img,name);select.onclick=()=>{if(row.dataset.suppressClick==='true'){delete row.dataset.suppressClick;return;}editLayer('select',l.id);};top.append(select);
  const blend=document.createElement('button');blend.className='layer-blend-button';blend.textContent=l.blend==='normal'?'N':l.blend.slice(0,1).toUpperCase();blend.title=l.blend;blend.setAttribute('aria-label','Blend properties '+l.name);blend.onclick=()=>{if(blocked())return;editLayer('select',l.id);$('layer-blend').focus();};top.append(blend);
  const visible=document.createElement('button');visible.className='layer-visibility';visible.setAttribute('aria-label',(l.visible?'Hide ':'Show ')+l.name);visible.setAttribute('aria-pressed',String(l.visible));visible.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12c4-7 16-7 20 0-4 7-16 7-20 0Z"/><circle cx="12" cy="12" r="3"/>'+(!l.visible?'<path d="M3 3l18 18"/>':'')+'</svg>';visible.onclick=()=>editLayer('visible',l.id,!l.visible);top.append(visible);
  const menu=document.createElement('button');menu.className='layer-menu';menu.textContent='…';menu.setAttribute('aria-label','Actions '+l.name);menu.setAttribute('aria-expanded','false');top.append(menu);row.append(top);
  const actions=document.createElement('div');actions.className='layer-actions';actions.hidden=true;const rename=document.createElement('input');rename.value=l.name;rename.maxLength=64;rename.setAttribute('aria-label','Layer name '+l.name);rename.onchange=()=>editLayer('name',l.id,rename.value);actions.append(rename);
  for(const [action,text,value] of [['locked',l.locked?'Unlock':'Lock',!l.locked],['duplicate','Duplicate'],['delete','Delete'],['up','Up'],['down','Down']]){const btn=document.createElement('button');btn.textContent=text;btn.setAttribute('aria-label',text+' '+l.name);btn.disabled=action==='delete'&&(l.locked||b.layers.length===1)||action==='up'&&l===b.layers.at(-1)||action==='down'&&l===b.layers[0];btn.onclick=()=>editLayer(action,l.id,value);actions.append(btn);}
  row.append(actions);menu.onclick=()=>{if(blocked())return;actions.hidden=!actions.hidden;menu.setAttribute('aria-expanded',String(!actions.hidden));};
  row.addEventListener('keydown',e=>{if(e.target.closest('input'))return;if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();editLayer(e.key==='ArrowUp'?'up':'down',l.id);[...$('layer-list').children].find(row=>row.dataset.layerId===l.id)?.querySelector('.layer-grip')?.focus();}});
  setupLayerGesture(row,grip,select,menu,l.id);list.append(row);
 }
 const l=b.layers.find(l=>l.id===b.activeLayer);$('layer-opacity').value=Math.round(l.opacity*100);$('layer-opacity-value').value=Math.round(l.opacity*100)+'%';$('layer-opacity').disabled=l.locked;$('layer-blend').value=l.blend;$('layer-blend').disabled=l.locked;$('layer-properties').dataset.layerId=l.id;$('add-layer').disabled=b.layers.length>=limits.layers;
}
function setupLayerGesture(row,grip,select,menu,id){
 let candidate=null;
 const detach=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',end,true);window.removeEventListener('pointercancel',abort,true);};
 function stop(cancelled=false){if(!candidate)return;clearTimeout(candidate.timer);const c=candidate;candidate=null;cancelLayerGesture=null;detach();if(layerDrag){layerDrag=null;row.removeAttribute('data-dragging');if(!cancelled){const rows=[...$('layer-list').querySelectorAll('[data-layer-id]')],index=rows.indexOf(row);editLayer('reorder',id,rows.length-1-index);}panels();}else if(!cancelled&&c.swipe){row.dataset.suppressClick='true';menu.click();}else if(!cancelled&&!c.grip){editLayer('select',id);}if(cancelled)panels();}
 function move(e){const c=candidate;if(!c||c.pointer!==e.pointerId)return;if(active||busy){stop(true);return;}const dx=e.clientX-c.x,dy=e.clientY-c.y;if(!layerDrag&&Math.abs(dx)>=48&&Math.abs(dy)<24&&!c.grip&&!c.ready){c.swipe=dx<0;return;}if(!layerDrag&&(c.grip||c.ready)&&Math.hypot(dx,dy)>=6){layerDrag={id};row.dataset.dragging='true';row.dataset.suppressClick='true';}if(!layerDrag)return;e.preventDefault();const list=$('layer-list'),r=list.getBoundingClientRect();if(e.clientY<r.top+24)list.scrollTop=Math.max(0,list.scrollTop-12);else if(e.clientY>r.bottom-24)list.scrollTop=Math.min(list.scrollHeight-list.clientHeight,list.scrollTop+12);for(const other of [...list.children]){if(other===row)continue;const box=other.getBoundingClientRect();if(e.clientY<box.top+box.height/2){list.insertBefore(row,other);break;}if(other===list.lastElementChild)list.append(row);}}
 function end(e){if(candidate?.pointer===e.pointerId)stop();}
 function abort(e){if(candidate?.pointer===e.pointerId)stop(true);}
 row.addEventListener('pointerdown',e=>{if(blocked()||e.button!==0||!e.target.closest('.layer-grip,.layer-select'))return;cancelLayerGesture=()=>stop(true);candidate={pointer:e.pointerId,x:e.clientX,y:e.clientY,grip:!!e.target.closest('.layer-grip'),swipe:false,ready:false};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',end,true);window.addEventListener('pointercancel',abort,true);try{row.setPointerCapture(e.pointerId);}catch{}candidate.timer=setTimeout(()=>{if(candidate)candidate.ready=true;},350);});
 row.addEventListener('lostpointercapture',e=>{if(candidate?.pointer===e.pointerId&&!layerDrag)stop(true);});
}
function cancelOpacity(){if(!opacityDraft)return;opacityDraft=null;panels();schedulePaint();}
$('layer-opacity').oninput=()=>{if(active||busy||layerDrag)return;const l=h.board.layers.find(l=>l.id===h.board.activeLayer);if(l.locked)return;if(!opacityDraft)opacityDraft={id:l.id,board:structuredClone(h.board)};const value=Number($('layer-opacity').value)/100;opacityDraft.board.layers.find(l=>l.id===opacityDraft.id).opacity=value;$('layer-opacity-value').value=Math.round(value*100)+'%';renderer.invalidate();schedulePaint();};
$('layer-opacity').onchange=()=>{if(!opacityDraft)return;const {id,board}=opacityDraft,value=board.layers.find(l=>l.id===id).opacity;opacityDraft=null;editLayer('opacity',id,value);panels();};
$('layer-opacity').addEventListener('pointercancel',cancelOpacity);window.addEventListener('blur',()=>{cancelOpacity();cancelLayerGesture?.();});$('layer-blend').onchange=()=>editLayer('blend',h.board.activeLayer,$('layer-blend').value);

function changed(next,updatePanels=false,keepSelection=false){if(next===h)return;if(!keepSelection)selected=[];h=next;status('Unsaved changes');clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,500);refresh();if(updatePanels)panels();}
function act(fn,updatePanels=true,keepSelection=false){if(blocked())return;try{changed(fn(),updatePanels,keepSelection);}catch(e){status(e.message,true);refresh();}}
const editLayer=(action,id,value)=>act(()=>layerCommand(h,action,id,value),true,action==='locked'&&id===h.board.activeLayer);
function saveNow(){clearTimeout(saveTimer);if(!h)return Promise.resolve(false);const snapshot=structuredClone(h.board);saveChain=saveChain.catch(()=>false).then(async()=>{if(saved===snapshot.revision)return true;status('Saving…');try{if(!store)throw Error('Local storage unavailable');expected=await store.save(snapshot,expected);saved=snapshot.revision;status(saved===h.board.revision?'Saved on this device':'Unsaved changes');return true;}catch(e){status('Save failed · '+e.message,true);return false;}});return saveChain;}
function sample(){try{$('sample').src=renderer.preview({id:'sample',...settings,points:[{x:16,y:30,pressure:null},{x:45,y:15,pressure:null},{x:80,y:35,pressure:null},{x:120,y:22,pressure:null},{x:165,y:28,pressure:null}]},Math.max(80,$('sample').clientWidth),56);}catch(e){status(e.message,true);}$('sample-label').textContent=settings.opacity===0?'Invisible ink (0%)':presetLabel(settings.preset)+' · '+settings.size+' · '+Math.round(settings.opacity*100)+'%';}
const u2=initU2UI({settings,renderer,$,blocked,status,sample});
for(const [id,min,max,key,divisor] of [['size',1,40,'size',1],['opacity',0,100,'opacity',100]])for(const control of [id,id+'-number'])$(control).addEventListener(control===id?'input':'change',()=>{if(blocked())return;const value=Number($(control).value);if(!Number.isFinite(value)||value<min||value>max||$(control).value===''){status('Value must be '+min+' to '+max,true);$(control).value=settings[key]*divisor;return;}settings[key]=value/divisor;$(id).value=value;$(id+'-number').value=value;u2.syncPresetSettings();sample();});
function setTool(id){if(blocked())return;tool=id;for(const name of ['pen','eraser','pan','lasso'])$(name).setAttribute('aria-pressed',String(name===id));$('move-selection').setAttribute('aria-pressed',String(id==='move'));}
for(const id of ['pen','eraser','pan','lasso'])$(id).onclick=()=>{if(blocked())return;const same=tool===id;setTool(id);if(id==='pan'){closePopovers();return;}togglePopover(id==='pen'?'brush-popover':id==='eraser'?'eraser-popover':'selection-controls',id,same);};
function selectionUI(){const n=selected.length;$('selection-count').textContent=n+' selected';let writable=true;try{editable(h.board);}catch{writable=false;}for(const id of ['move-selection','transform-selection','cut-selection','delete-selection'])$(id).disabled=!n||!writable||!!active||busy||!!pending;$('copy-selection').disabled=!n||!h.board.layers.find(l=>l.id===h.board.activeLayer).visible||blocked();$('clear-selection').disabled=!n||!!active||busy;$('paste-selection').disabled=!clipboard||!writable||!!active||busy;const box=$('selection-box'),line=$('lasso-path');try{const displayBoard=pending?.kind==='transform'?pending.preview.board:active?.moved?.board||h.board;const bounds=selected.length?selectionBounds(displayBoard,selected):null;box.toggleAttribute('hidden',!bounds);if(bounds){box.setAttribute('x',bounds.minX*view.scale+view.x);box.setAttribute('y',bounds.minY*view.scale+view.y);box.setAttribute('width',Math.max(1,bounds.width*view.scale));box.setAttribute('height',Math.max(1,bounds.height*view.scale));}}catch{box.setAttribute('hidden','');}line.toggleAttribute('hidden',!active?.lasso);if(active?.lasso)line.setAttribute('points',active.polygon.map(p=>(p.x*view.scale+view.x)+','+(p.y*view.scale+view.y)).join(' '));}
function selectionAction(kind){if(blocked()||!h)return;try{if(kind==='copy'){clipboard=copySelection(h.board,selected);status('Copied '+selected.length+' strokes · page clipboard');}else if(kind==='cut'){const nextClipboard=copySelection(h.board,selected),next=deleteSelection(h,selected);changed(next);clipboard=nextClipboard;}else if(kind==='delete')changed(deleteSelection(h,selected));else if(kind==='paste'){const before=new Set(h.board.layers.flatMap(l=>l.strokes.map(s=>s.id))),r=canvas.getBoundingClientRect(),center=toDocument(r.width/2,r.height/2,view),next=pasteSelection(h,clipboard,center.x,center.y);selected=next.board.layers.find(l=>l.id===next.board.activeLayer).strokes.filter(s=>!before.has(s.id)).map(s=>s.id);changed(next,false,true);setTool('move');}else if(kind==='clear'){selected=[];}refresh();}catch(e){status(e.message,true);refresh();}}
$('move-selection').onclick=()=>{setTool('move');if(!blocked())closePopovers();};for(const [id,kind] of [['copy-selection','copy'],['cut-selection','cut'],['paste-selection','paste'],['delete-selection','delete'],['clear-selection','clear']])$(id).onclick=()=>selectionAction(kind);
function gesturePoint(e){const p=pos(e);return toDocument(p.x,p.y,active?.frozenView||view);}
function lassoPoint(e){const p=gesturePoint(e),last=active.polygon.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)>1e-7){if(active.polygon.length>=512)throw Error('Lasso limit reached · selection unchanged');active.polygon.push(p);}}
function movePreview(e){const p=gesturePoint(e);active.dx=p.x-active.start.x;active.dy=p.y-active.start.y;active.moved=moveSelection(active.baseHistory,active.ids,active.dx,active.dy);}

function geometryUI(){
 for(const id of ['transform-scale-handle','transform-rotate-handle','shape-handle-a','shape-handle-b'])$(id).setAttribute('hidden','');
 const css=p=>({x:p.x*view.scale+view.x,y:p.y*view.scale+view.y});
 if(pending?.kind==='transform')try{const b=selectionBounds(pending.preview.board,pending.ids);if(b){const s=css({x:b.maxX,y:b.maxY}),r=css({x:b.cx,y:b.minY-30/Math.max(view.scale,.001)});for(const [id,p]of [['transform-scale-handle',s],['transform-rotate-handle',r]]){$(id).setAttribute('cx',p.x);$(id).setAttribute('cy',p.y);$(id).removeAttribute('hidden');}}}catch{}
 if(pending?.kind==='shape'){const q=pending.recognized,a=q.kind==='line'?q.points[0]:q.center,b=q.kind==='line'?q.points[1]:{x:q.center.x+q.radius,y:q.center.y},aa=css(a),bb=css(b);for(const [id,p]of [['shape-handle-a',aa],['shape-handle-b',bb]]){$(id).setAttribute('cx',p.x);$(id).setAttribute('cy',p.y);$(id).removeAttribute('hidden');}}
}
function localRecord(before){if(!pending)return;pending.localPast.push(structuredClone(before));if(pending.localPast.length>32)pending.localPast.shift();pending.localFuture=[];}
function syncTransformInputs(){if(pending?.kind!=='transform')return;const p=pending.params;$('transform-x').value=p.dx;$('transform-y').value=p.dy;$('transform-scale').value=p.scale*100;$('transform-angle').value=p.angle;}
function updateTransform(next,record=false){if(pending?.kind!=='transform')return false;const before={...pending.params},p={...pending.params,...next};try{const preview=transformSelection(pending.baseHistory,pending.ids,p);if(record)localRecord(before);pending.params=p;pending.preview=preview;syncTransformInputs();refresh();return true;}catch(e){status(e.message,true);return false;}}
function beginTransform(){if(blocked()||!selected.length)return;try{editable(h.board);selectionBounds(h.board,selected);}catch(e){status(e.message,true);return;}closePopovers();pending={kind:'transform',baseHistory:h,ids:[...selected],params:{dx:0,dy:0,scale:1,angle:0},preview:h,localPast:[],localFuture:[]};$('transform-controls').hidden=false;syncTransformInputs();status('Transform preview · Apply or Cancel');refresh();}
function applyTransform(){if(pending?.kind!=='transform')return;const q=pending;pending=null;$('transform-controls').hidden=true;if(q.preview!==q.baseHistory)changed(q.preview,false,true);else refresh();status('Transform applied');}
function cancelTransform(){if(pending?.kind!=='transform')return;pending=null;$('transform-controls').hidden=true;status('Transform cancelled');refresh();}
function syncShapeInputs(){if(pending?.kind!=='shape')return;const q=pending.recognized;$('shape-kind').textContent=q.kind==='line'?'Line':'Circle';$('shape-line-fields').hidden=q.kind!=='line';$('shape-circle-fields').hidden=q.kind!=='circle';if(q.kind==='line'){const [a,b]=q.points;$('shape-x1').value=a.x;$('shape-y1').value=a.y;$('shape-x2').value=b.x;$('shape-y2').value=b.y;}else{$('shape-cx').value=q.center.x;$('shape-cy').value=q.center.y;$('shape-radius').value=q.radius;}}
function updateShape(next,record=false){if(pending?.kind!=='shape')return false;const before=structuredClone(pending.recognized);try{const q=editRecognized(pending.recognized,next);if(record)localRecord(before);pending.recognized=q;pending.stroke={...pending.stroke,points:q.points.map(p=>({...p}))};syncShapeInputs();refresh();return true;}catch(e){status(e.message,true);return false;}}
function beginShapeDraft(done){closePopovers();const q=done.recognized;pending={kind:'shape',baseHistory:h,recognized:q,stroke:{...done.stroke,points:q.points.map(p=>({...p}))},localPast:[],localFuture:[]};$('shape-controls').hidden=false;syncShapeInputs();status('Edit '+q.kind+' · Apply or Cancel');refresh();}
function applyShape(){if(pending?.kind!=='shape')return;const q=pending;pending=null;$('shape-controls').hidden=true;try{changed(addStroke(q.baseHistory,q.stroke));status('Shape applied');}catch(e){status(e.message,true);refresh();}}
function cancelShape(){if(pending?.kind!=='shape')return;pending=null;$('shape-controls').hidden=true;status('Shape cancelled');refresh();}
function localHistory(kind){if(!pending)return false;const from=kind==='undo'?pending.localPast:pending.localFuture,to=kind==='undo'?pending.localFuture:pending.localPast;if(!from.length){status('No '+kind+' in current edit');return true;}if(pending.kind==='transform'){to.push({...pending.params});pending.params=from.pop();pending.preview=transformSelection(pending.baseHistory,pending.ids,pending.params);syncTransformInputs();}else{to.push(structuredClone(pending.recognized));pending.recognized=from.pop();pending.stroke={...pending.stroke,points:pending.recognized.points.map(p=>({...p}))};syncShapeInputs();}refresh();return true;}
function historyAction(kind){if(pending)return localHistory(kind);if(active||busy||layerDrag||opacityDraft)return false;const next=kind==='undo'?undo(h):redo(h);if(next===h){status('No '+kind+' history');return true;}changed(next);status(kind==='undo'?'Undo':'Redo');return true;}
$('transform-selection').onclick=beginTransform;$('apply-transform').onclick=applyTransform;$('cancel-transform').onclick=cancelTransform;$('apply-shape').onclick=applyShape;$('cancel-shape').onclick=cancelShape;
for(const id of ['transform-x','transform-y','transform-scale','transform-angle'])$(id).addEventListener('change',()=>{if(pending?.kind!=='transform')return;updateTransform({dx:Number($('transform-x').value),dy:Number($('transform-y').value),scale:Number($('transform-scale').value)/100,angle:Number($('transform-angle').value)},true);});
for(const id of ['shape-x1','shape-y1','shape-x2','shape-y2','shape-cx','shape-cy','shape-radius'])$(id).addEventListener('change',()=>{if(pending?.kind!=='shape')return;const q=pending.recognized;updateShape(q.kind==='line'?{x1:Number($('shape-x1').value),y1:Number($('shape-y1').value),x2:Number($('shape-x2').value),y2:Number($('shape-y2').value)}:{cx:Number($('shape-cx').value),cy:Number($('shape-cy').value),radius:Number($('shape-radius').value)},true);});
$('undo').onclick=()=>historyAction('undo');$('redo').onclick=()=>historyAction('redo');$('title').onchange=()=>act(()=>command(h,b=>b.title=$('title').value));$('add-layer').onclick=()=>editLayer('add');
for(const id of ['paper','paper-color','spacing'])$(id).onchange=()=>act(()=>command(h,b=>{b.paper.kind=$('paper').value;b.paper.color=$('paper-color').value;b.paper.spacing=Number($('spacing').value);}));
const popovers=['actions-popover','selection-controls','brush-popover','eraser-popover','colour-popover','inspector'];
function closePopovers(){if(blocked())return;for(const id of popovers)$(id).hidden=true;$('inspector').dataset.open='false';for(const id of ['actions-toggle','pen','eraser','colour-toggle','layers-toggle','panels'])$(id).setAttribute('aria-expanded','false');}
function togglePopover(id,trigger,allowClose=true){if(blocked())return;const opening=$(id).hidden||!allowClose;closePopovers();if(opening){$(id).hidden=false;$(trigger).setAttribute('aria-expanded','true');if(id==='inspector'){$('inspector').dataset.open='true';$('panels').setAttribute('aria-expanded','true');panels();}if(id==='brush-popover')sample();}}
$('actions-toggle').onclick=()=>togglePopover('actions-popover','actions-toggle');$('colour-toggle').onclick=()=>togglePopover('colour-popover','colour-toggle');$('layers-toggle').onclick=()=>togglePopover('inspector','layers-toggle');$('panels').onclick=()=>togglePopover('inspector','layers-toggle');$('close-panels').onclick=()=>{closePopovers();$('layers-toggle').focus();};
$('modifiers-toggle').onclick=()=>{if(blocked())return;$('tools').hidden=!$('tools').hidden;$('modifiers-toggle').setAttribute('aria-expanded',String(!$('tools').hidden));};
document.addEventListener('keydown',e=>{if((active||busy)&&e.key!=='Escape'&&e.target.closest('button,input,select,summary,.layer')){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('pointerdown',e=>{if(e.target.closest('#canvas')){if(layerDrag||opacityDraft){e.preventDefault();e.stopImmediatePropagation();return;}if(!active&&!busy&&popovers.some(id=>!$(id).hidden)){closePopovers();e.preventDefault();e.stopImmediatePropagation();}return;}if((active||busy)&&e.target.closest('button,input,select,summary,.layer')){e.preventDefault();e.stopImmediatePropagation();}},true);

const pos=e=>{const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
const point=e=>({...toDocument(pos(e).x,pos(e).y,view),pressure:e.pointerType==='pen'?Math.max(0,Math.min(1,e.pressure)):null});
function report(e){$('input').textContent=e.pointerType==='pen'?'Pen · reported pressure '+e.pressure.toFixed(2):e.pointerType==='touch'?'Touch · navigation only':'Mouse · pressure unavailable';}
function cancel(){if(active?.shapeTimer)clearTimeout(active.shapeTimer);if(active?.lasso)selected=active.prior;if(active?.erase)status('Eraser gesture cancelled');active=null;contacts.clear();touchTracker.cancel();clearTouchHold();refresh();}
function sweep(p){try{active.sweeps.push({a:active.last,b:p});active.last=p;active.erased=eraseGesture(active.base,active.mode,active.sweeps,active.radius);refresh();}catch(e){active=null;status(e.message,true);refresh();}}
function clearTouchHold(){clearTimeout(touchHoldTimer);touchHoldTimer=null;}
function sampledHex(p){const r=canvas.getBoundingClientRect(),x=Math.max(0,Math.min(canvas.width-1,Math.floor(p.x*canvas.width/Math.max(1,r.width)))),y=Math.max(0,Math.min(canvas.height-1,Math.floor(p.y*canvas.height/Math.max(1,r.height)))),d=canvas.getContext('2d').getImageData(x,y,1,1).data;return '#'+[d[0],d[1],d[2]].map(v=>v.toString(16).padStart(2,'0')).join('');}
function touchDown(e){if(e.pointerType!=='touch')return;e.preventDefault();e.stopImmediatePropagation();canvas.focus();const p=pos(e);contacts.set(e.pointerId,p);report(e);
 if(active){if(active.recognized&&!active.shapeModifier){active.shapeModifier=e.pointerId;status('Shape constraint active');}return;}
 if(!touchTracker.snapshot())touchBaseView={...view};const s=touchTracker.down(e.pointerId,p.x,p.y,e.timeStamp);touchPicked=null;clearTouchHold();if(s.maxCount===1&&!pending)touchHoldTimer=setTimeout(()=>{const q=touchTracker.snapshot();if(q?.candidate&&!q.moved&&q.maxCount===1&&q.active.length===1){touchPicked=sampledHex(q.active[0].current);status('Colour sampled '+touchPicked+' · release to use');}},TOUCH_LIMITS.holdMs);
}
function touchMove(e){if(e.pointerType!=='touch')return;e.preventDefault();e.stopImmediatePropagation();const p=pos(e);if(active){contacts.set(e.pointerId,p);return;}if(!contacts.has(e.pointerId))return;contacts.set(e.pointerId,p);const q=touchTracker.move(e.pointerId,p.x,p.y);if(q.crossed)clearTouchHold();const s=q.state;if(!s?.moved||s.maxCount>2)return;const pts=s.active;if(pts.length===1){const a=pts[0];view={...touchBaseView,x:touchBaseView.x+a.current.x-a.start.x,y:touchBaseView.y+a.current.y-a.start.y};}
 else if(pts.length===2){const a=pts[0],b=pts[1],oldD=Math.hypot(a.start.x-b.start.x,a.start.y-b.start.y),newD=Math.hypot(a.current.x-b.current.x,a.current.y-b.current.y),oc={x:(a.start.x+b.start.x)/2,y:(a.start.y+b.start.y)/2},nc={x:(a.current.x+b.current.x)/2,y:(a.current.y+b.current.y)/2};let v=oldD>1?zoomAt(touchBaseView,oc.x,oc.y,touchBaseView.scale*newD/oldD):{...touchBaseView};v.x+=nc.x-oc.x;v.y+=nc.y-oc.y;view=v;}refresh();}
function touchEnd(e,cancelled=false){if(e.pointerType!=='touch')return;e.preventDefault();e.stopImmediatePropagation();contacts.delete(e.pointerId);if(active?.shapeModifier===e.pointerId){active.shapeModifier=null;status('Shape constraint released');return;}if(active)return;clearTouchHold();if(cancelled){touchTracker.cancel();touchPicked=null;return;}const r=touchTracker.up(e.pointerId,e.timeStamp);if(r.finished){if(touchPicked&&r.ended?.count===1){u2.setColour(touchPicked,true);status('Colour '+touchPicked+' selected');sample();}else if(r.action)historyAction(r.action);touchPicked=null;touchBaseView=null;}refresh();}
canvas.addEventListener('pointerdown',touchDown,true);canvas.addEventListener('pointermove',touchMove,true);canvas.addEventListener('pointerup',e=>touchEnd(e),true);canvas.addEventListener('pointercancel',e=>touchEnd(e,true),true);canvas.addEventListener('lostpointercapture',e=>touchEnd(e,true),true);
function armShapeHoldAt(cssPoint){if(!active?.stroke||active.recognized)return;if(active.shapeTimer)clearTimeout(active.shapeTimer);active.shapeAnchor={...cssPoint};active.shapeTimer=setTimeout(()=>{if(!active?.stroke||active.recognized)return;const q=recognizeHeldShape(active.stroke.points,active.frozenView?.scale||view.scale);if(!q)return;active.recognized=q;active.stroke={...active.stroke,points:q.points.map(p=>({...p}))};status(q.kind==='line'?'Line recognized · release to edit':'Circle recognized · release to edit');schedulePaint();},650);}
canvas.addEventListener('pointerdown',e=>{if(!h||busy||opacityDraft||layerDrag||e.button!==0)return;canvas.focus();report(e);try{canvas.setPointerCapture(e.pointerId);}catch{}const p=pos(e);contacts.set(e.pointerId,p);if(e.pointerType==='touch')return;if(active)return;if(tool==='pan'||space){active={id:e.pointerId,pan:p};return;}try{editable(h.board);}catch(err){status(err.message,true);return;}if(tool==='lasso'){active={id:e.pointerId,lasso:true,polygon:[point(e)],prior:[...selected],frozenView:{...view}};refresh();return;}if(tool==='move'){const p=point(e),b=selectionBounds(h.board,selected);if(!b||p.x<b.minX||p.x>b.maxX||p.y<b.minY||p.y>b.maxY){status('Drag inside the selected box to move');return;}active={id:e.pointerId,move:true,baseHistory:h,ids:[...selected],start:p,frozenView:{...view},dx:0,dy:0};refresh();return;}if(tool==='eraser'){active={id:e.pointerId,erase:true,mode:$('erase-mode').value,radius:settings.size/2,base:h.board,sweeps:[],last:point(e),erased:h.board};sweep(point(e));return;}if(settings.opacity===0){status('Invisible ink (0%) · no stroke added');return;}active={id:e.pointerId,stroke:{id:crypto.randomUUID(),...settings,points:[point(e)]}};refresh();});
canvas.addEventListener('pointermove',e=>{report(e);const p=pos(e);if(e.pointerType==='touch'){if(!contacts.has(e.pointerId))return;const before=[...contacts.entries()],old=contacts.get(e.pointerId);contacts.set(e.pointerId,p);if(active)return;if(contacts.size===1){view.x+=p.x-old.x;view.y+=p.y-old.y;}else if(contacts.size===2){const a=before[0][1],b=before[1][1],now=[...contacts.values()],oldD=Math.hypot(a.x-b.x,a.y-b.y),newD=Math.hypot(now[0].x-now[1].x,now[0].y-now[1].y),center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(oldD>1)view=zoomAt(view,center.x,center.y,view.scale*newD/oldD);view.x+=(now[0].x+now[1].x)/2-center.x;view.y+=(now[0].y+now[1].y)/2-center.y;}refresh();return;}if(!active||active.id!==e.pointerId)return;if(active.pan){view.x+=p.x-active.pan.x;view.y+=p.y-active.pan.y;active.pan=p;}else if(active.erase)sweep(point(e));else if(active.lasso||active.move){try{if(active.lasso)lassoPoint(e);else movePreview(e);}catch(err){cancel();status(err.message,true);}}else{const events=e.getCoalescedEvents?.()||[e];for(const q of events.length?events:[e]){const pt=point(q);if(active.stroke.points.length>=limits.points){cancel();status('Stroke point limit reached; gesture cancelled',true);break;}active.stroke.points.push(pt);}}if(active?.stroke)schedulePaint();else refresh();});
function finish(e,cancelled=false){contacts.delete(e.pointerId);if(!active||active.id!==e.pointerId)return;if(!cancelled){if(active.lasso||active.move){try{if(active.lasso)lassoPoint(e);else movePreview(e);}catch(err){cancel();status(err.message,true);return;}}else if(active.erase)sweep(point(e));else if(active.stroke){const p=point(e),last=active.stroke.points.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)>1e-7)active.stroke.points.push(p);}}if(!active)return;const done=active;active=null;if(cancelled&&done.lasso)selected=done.prior;if(!cancelled){try{if(done.lasso){selected=selectLasso(h.board,done.polygon);status(selected.length+' strokes selected');}if(done.move&&done.moved)changed(done.moved,false,true);if(done.stroke)changed(addStroke(h,done.stroke));if(done.erase&&done.erased!==done.base)changed(command(h,b=>{b.layers=done.erased.layers;}));}catch(err){if(done.lasso)selected=done.prior;status(err.message,true);}}refresh();if(!$('inspector').hidden)panels();}
canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,true));canvas.addEventListener('lostpointercapture',e=>finish(e,true));window.addEventListener('blur',cancel);
canvas.addEventListener('wheel',e=>{e.preventDefault();if(active)return;const p=pos(e);view=zoomAt(view,p.x,p.y,view.scale*Math.exp(-e.deltaY*.002));refresh();},{passive:false});$('reset-view').onclick=()=>{if(active)return;view={x:0,y:0,scale:1};refresh();};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelLayerGesture?.();cancelOpacity();cancel();closePopovers();return;}if(e.target.closest('input,select,textarea,dialog'))return;if(e.code==='Space'){e.preventDefault();space=true;}if((e.ctrlKey||e.metaKey)&&['c','x','v'].includes(e.key.toLowerCase())){e.preventDefault();selectionAction({c:'copy',x:'cut',v:'paste'}[e.key.toLowerCase()]);}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();selectionAction('delete');}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();act(()=>e.shiftKey?redo(h):undo(h));}});window.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});
async function transition(fn){if(blocked())return;busy=true;try{if(!await saveNow())return;await fn();}catch(e){status(e.message,true);}finally{busy=false;refresh();}}
async function openBoard(id){const r=await store.load(id);await store.select(id);selected=[];h=createHistory(r.board);expected=r.dbRevision;saved=r.recovered?-1:h.board.revision;view={x:0,y:0,scale:1};status(r.recovered?'Recovered previous version · Export before continuing':'Saved on this device');refresh();panels();}
async function newBoard(){const b=createBoard();expected=await store.save(b,0);selected=[];h=createHistory(b);saved=0;view={x:0,y:0,scale:1};status('Saved on this device');refresh();panels();}
$('new').onclick=()=>transition(newBoard);$('boards').onclick=async()=>{if(blocked()||!store)return;try{const records=await store.list();$('board-list').replaceChildren();for(const r of records){const row=document.createElement('div');row.className='board-row';const btn=document.createElement('button');btn.textContent=r.current?.title||'Damaged board';btn.onclick=()=>transition(async()=>{await openBoard(r.id);$('gallery').close();});row.append(btn);$('board-list').append(row);}$('gallery').showModal();}catch(e){status(e.message,true);}};$('close-gallery').onclick=()=>{if(!blocked())$('gallery').close();};
$('export').onclick=()=>{if(blocked()||!h)return;const url=URL.createObjectURL(new Blob([JSON.stringify(h.board)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=h.board.title.replace(/[^a-z0-9_-]/gi,'_')+'.unruly.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>{if(blocked())return;$('import-file').click();};$('import-file').onchange=async()=>{const file=$('import-file').files[0];$('import-file').value='';if(!file)return;try{if(file.size>limits.bytes)throw Error('Import exceeds 8 MiB');const board=importDocument(await file.text());await transition(async()=>{const revision=await store.save(board,0);selected=[];h=createHistory(board);expected=revision;saved=0;view={x:0,y:0,scale:1};status('Imported as a new board · Saved on this device');refresh();panels();});}catch(e){status('Import rejected · '+e.message,true);}};
new ResizeObserver(()=>{refresh();sample();}).observe(canvas);window.addEventListener('beforeunload',e=>{if(active||h&&saved!==h.board.revision){e.preventDefault();e.returnValue='';}});
async function startup(){try{store=await openStore();store.db.onversionchange=()=>{store.close();store=null;status('Storage changed · reopen page',true);};const migration=await store.migrateLegacy();let last=await store.last();if(!last){const records=await store.list();last=records[0]?.id;}if(last)await openBoard(last);else if(migration.hadSources&&migration.errors.length){h=createHistory(createBoard(undefined,'Recovery workspace'));expected=0;saved=-1;refresh();panels();status('Old boards need recovery · originals intact. Export any recovered work before continuing.',true);}else await newBoard();if(migration.errors.length)status('Some old boards could not be copied; originals preserved. '+migration.errors[0].message,true);else if(migration.warnings?.length)status('Recovery warning · '+migration.warnings[0].message,true);else if(migration.copied)status('Copied '+migration.copied+' old boards · originals preserved');navigator.storage?.persist?.().catch(()=>{});}catch(e){status('Storage/recovery error · '+e.message,true);if(!h){h=createHistory(createBoard(undefined,'Recovery workspace'));refresh();panels();}}}
async function offline(){if(!('serviceWorker'in navigator)){$('offline').textContent='Offline caching unavailable';return;}try{const r=await navigator.serviceWorker.register('./sw.js');const observe=w=>w?.addEventListener('statechange',()=>{if(w.state==='redundant')$('offline').textContent='Offline setup failed · stay online';});observe(r.installing);r.addEventListener('updatefound',()=>observe(r.installing));await navigator.serviceWorker.ready;$('offline').textContent='Ready for offline use';const check=()=>{if(r.waiting){waitingWorker=r.waiting;$('update').hidden=false;}};check();r.addEventListener('updatefound',()=>r.installing?.addEventListener('statechange',check));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(requestedUpdate)location.reload();});}catch{$('offline').textContent='Offline setup failed · stay online';}}
$('update').onclick=async()=>{if(blocked()||contacts.size){status('Finish your stroke or selection gesture before updating');return;}await transition(async()=>{if(saved!==h.board.revision)return;if(waitingWorker){requestedUpdate=true;waitingWorker.postMessage({type:'ACTIVATE_UPDATE'});}});};
startup();offline();
