// Original bounded vector selection. MIT. No DOM, storage or system clipboard.
import {limits,validateBoard,editable,command,createBoard} from './model.js';
const clone=x=>structuredClone(x),finite=x=>typeof x==='number'&&Number.isFinite(x),fail=m=>{throw Error(m);};
function chosen(board,ids,write=false){validateBoard(board);if(!Array.isArray(ids)||ids.length>limits.strokes||ids.some(id=>typeof id!=='string'||!id||id.length>128)||new Set(ids).size!==ids.length)fail('Invalid selection IDs');const layer=write?editable(board):board.layers.find(l=>l.id===board.activeLayer),map=new Map(layer.strokes.map(s=>[s.id,s]));if(ids.some(id=>!map.has(id)))fail('Selection is stale or belongs to another layer');return layer.strokes.filter(s=>ids.includes(s.id));}
export function selectionBounds(board,ids){const strokes=chosen(board,ids);if(!strokes.length)return null;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const s of strokes)for(const p of s.points){minX=Math.min(minX,p.x-s.size/2);minY=Math.min(minY,p.y-s.size/2);maxX=Math.max(maxX,p.x+s.size/2);maxY=Math.max(maxY,p.y+s.size/2);}return{minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY,cx:(minX+maxX)/2,cy:(minY+maxY)/2};}
const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
const on=(p,a,b)=>Math.abs(cross(a,b,p))<=1e-7&&p.x>=Math.min(a.x,b.x)-1e-7&&p.x<=Math.max(a.x,b.x)+1e-7&&p.y>=Math.min(a.y,b.y)-1e-7&&p.y<=Math.max(a.y,b.y)+1e-7;
function segments(a,b,c,d){if(on(a,c,d)||on(b,c,d)||on(c,a,b)||on(d,a,b))return true;return (cross(a,b,c)>0)!==(cross(a,b,d)>0)&&(cross(c,d,a)>0)!==(cross(c,d,b)>0);}
export function selectLasso(board,polygon,options={}){
 const layer=editable(validateBoard(board));if(!Array.isArray(polygon)||polygon.length<3||polygon.length>512||polygon.some(p=>!p||!finite(p.x)||!finite(p.y)||Math.abs(p.x)>1e7||Math.abs(p.y)>1e7)||new Set(polygon.map(p=>p.x+','+p.y)).size<3)fail('Lasso needs a valid loop (3–512 points)');let area=0;for(let i=0;i<polygon.length;i++){const p=polygon[i],q=polygon[(i+1)%polygon.length];area+=p.x*q.y-q.x*p.y;}if(Math.abs(area)/2<1)fail('Lasso loop is too small or ambiguous');const limit=options.comparisons??200000;if(!Number.isSafeInteger(limit)||limit<1||limit>200000)fail('Invalid lasso work limit');let count=0;const check=()=>{if(++count>limit)fail('Lasso work limit reached; selection unchanged');};
 function inside(p){let yes=false;for(let i=0;i<polygon.length;i++){check();const a=polygon[i],b=polygon[(i+1)%polygon.length];if(on(p,a,b))return true;if((a.y>p.y)!==(b.y>p.y)&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)yes=!yes;}return yes;}
 return layer.strokes.filter(s=>{for(let i=0;i<s.points.length;i++){if(inside(s.points[i]))return true;if(i)for(let j=0;j<polygon.length;j++){check();if(segments(s.points[i-1],s.points[i],polygon[j],polygon[(j+1)%polygon.length]))return true;}}return false;}).map(s=>s.id);
}
export function copySelection(board,ids){const source=board.layers.find(l=>l.id===board.activeLayer);if(!source?.visible)fail('Active layer is hidden');const strokes=clone(chosen(board,ids));if(!strokes.length)fail('Nothing selected');const payload={version:1,strokes,bounds:selectionBounds(board,ids)};checkClipboard(payload);return payload;}
function checkClipboard(payload){if(!payload||payload.version!==1||!Array.isArray(payload.strokes)||!payload.strokes.length||new TextEncoder().encode(JSON.stringify(payload)).length>limits.bytes)fail('Invalid or oversized clipboard');const b=createBoard();b.layers[0].strokes=clone(payload.strokes);validateBoard(b);return {strokes:b.layers[0].strokes,bounds:selectionBounds(b,b.layers[0].strokes.map(s=>s.id))};}
export function deleteSelection(h,ids){chosen(h.board,ids,true);if(!ids.length)return h;const set=new Set(ids);return command(h,b=>{editable(b).strokes=editable(b).strokes.filter(s=>!set.has(s.id));});}
export function moveSelection(h,ids,dx,dy){chosen(h.board,ids,true);if(!finite(dx)||!finite(dy))fail('Invalid movement');if(!ids.length||dx===0&&dy===0)return h;const set=new Set(ids);return command(h,b=>{for(const s of editable(b).strokes)if(set.has(s.id))for(const p of s.points){p.x+=dx;p.y+=dy;}});}
export function pasteSelection(h,payload,x,y){editable(h.board);if(!finite(x)||!finite(y))fail('Invalid paste position');const {strokes,bounds}=checkClipboard(payload),dx=x-bounds.cx,dy=y-bounds.cy;return command(h,b=>{for(const s of strokes){s.id=crypto.randomUUID();for(const p of s.points){p.x+=dx;p.y+=dy;}}editable(b).strokes.push(...strokes);});}
