import {limits,validateBoard,migrateV1} from './model.js';
const request=r=>new Promise((ok,no)=>{r.onblocked=()=>no(Error('Storage is busy in another tab'));r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});
export async function openStore(){const r=indexedDB.open('unruly-workspace',1);r.onupgradeneeded=()=>{r.result.createObjectStore('boards',{keyPath:'id'});r.result.createObjectStore('meta');};const db=await request(r);
 const read=(store,key)=>request(db.transaction(store).objectStore(store).get(key));
 const list=()=>request(db.transaction('boards').objectStore('boards').getAll());
 async function load(id){const record=await read('boards',id);if(!record)throw Error('Saved board missing; stored data preserved');if(!Number.isSafeInteger(record.dbRevision)||record.dbRevision<1)throw Error('Invalid stored revision');let board,recovered=false;try{board=validateBoard(record.current);}catch{try{board=validateBoard(record.previous);recovered=true;}catch{throw Error('Damaged board; original data preserved');}}if(board.id!==record.id)throw Error('Stored identity mismatch');return {board:structuredClone(board),dbRevision:record.dbRevision,recovered};}
 function save(board,expectedRevision,select=true){const snapshot=structuredClone(validateBoard(board));return new Promise((ok,no)=>{const tx=db.transaction(['boards','meta'],'readwrite'),store=tx.objectStore('boards');let problem;const abort=e=>{problem=e;try{tx.abort();}catch{no(e);}};tx.oncomplete=()=>ok(expectedRevision+1);tx.onabort=()=>no(problem||tx.error||Error('Save aborted'));tx.onerror=()=>{};
 const get=store.get(snapshot.id);get.onsuccess=()=>{const old=get.result;if((old?old.dbRevision:0)!==expectedRevision){abort(Error('Conflict: another tab saved this board. Export your work before reopening.'));return;}const put=()=>{try{let previous=null;if(old){try{previous=structuredClone(validateBoard(old.current));}catch{try{previous=structuredClone(validateBoard(old.previous));}catch{abort(Error('Damaged original record; export your work'));return;}}}store.put({id:snapshot.id,dbRevision:expectedRevision+1,current:snapshot,previous});if(select)tx.objectStore('meta').put(snapshot.id,'lastBoard');}catch(e){abort(e);}};if(old)put();else{const count=store.count();count.onsuccess=()=>count.result>=limits.boards?abort(Error('Board limit reached')):put();}};});}
 async function migrateLegacy(){const result={copied:0,skipped:0,errors:[]};let legacy;
 try{if(indexedDB.databases){const ds=await indexedDB.databases();if(!ds.some(d=>d.name==='unruly-foundation'))return result;}const r=indexedDB.open('unruly-foundation');let absent=false;r.onupgradeneeded=()=>{absent=true;r.transaction.abort();};try{legacy=await request(r);}catch(e){if(absent)return result;throw e;}if(!legacy.objectStoreNames.contains('boards'))return result;const records=await request(legacy.transaction('boards').objectStore('boards').getAll());for(const record of records){try{if(await read('boards',record.id)){result.skipped++;continue;}let b;try{b=migrateV1(record.current,record.dbRevision);}catch{b=migrateV1(record.previous,record.dbRevision);}if(b.id!==record.id)throw Error('Legacy identity mismatch');await save(b,0,false);result.copied++;}catch(e){result.errors.push({id:record.id,message:e.message});}}}catch(e){result.errors.push({message:e.message});}finally{legacy?.close();}return result;}
 const select=id=>new Promise((ok,no)=>{const tx=db.transaction('meta','readwrite');tx.oncomplete=()=>ok();tx.onabort=()=>no(tx.error||Error('Selection save aborted'));tx.onerror=()=>{};try{tx.objectStore('meta').put(id,'lastBoard');}catch(e){try{tx.abort();}catch{}no(e);}});
 return {db,list,load,save,migrateLegacy,select,last:()=>read('meta','lastBoard'),close:()=>db.close()};
}
