import {brushPercentFromWidth,maxBrushWidth} from './brush-size.js';
import {EXTRA_BRUSH_PRESETS,BRUSH_PRESETS,BRUSH_CATEGORIES,getPreset,presetsFor,presetLabel} from './brushes.js';
const KEY='unruly-u2-ui-v1';
const DEFAULT_PALETTE=['#203d48','#171c24','#c14f43','#d69b28','#517a58','#4877a3','#8a63a2','#f2eee3'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {presets:x.presets&&typeof x.presets==='object'?x.presets:{},recent:Array.isArray(x.recent)?x.recent.slice(0,8):[],palette:Array.isArray(x.palette)&&x.palette.length?x.palette.slice(0,16):[...DEFAULT_PALETTE]};}catch{return {presets:{},recent:[],palette:[...DEFAULT_PALETTE]};}}
function hsvFromHex(hex,fallbackHue=0){const [r,g,b]=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=fallbackHue;if(d){h=max===r?((g-b)/d)%6:max===g?(b-r)/d+2:(r-g)/d+4;h=(h*60+360)%360;}return {h,s:max?d/max*100:0,v:max*100};}
function hexFromHsv(h,s,v){s/=100;v/=100;const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let a=[0,0,0];if(h<60)a=[c,x,0];else if(h<120)a=[x,c,0];else if(h<180)a=[0,c,x];else if(h<240)a=[0,x,c];else if(h<300)a=[x,0,c];else a=[c,0,x];return '#'+a.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('');}
function hslHex(h,s,l){s/=100;l/=100;const a=s*Math.min(l,1-l);return '#'+[0,8,4].map(n=>{const k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0');}).join('');}
export function initU2UI({settings,renderer,$,blocked,status,sample,onPresetChange=()=>{}}){
 const saved=read(),sampleCache=new Map();let family=getPreset(settings.preset)?.family||'ink',hsv=hsvFromHex(settings.color,195),draft=null;
 const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}};
 const syncControls=()=>{const percent=brushPercentFromWidth(settings.size,settings.brush);$('size').min='0';$('size-number').min='0';$('size').max='100';$('size-number').max='100';$('size').value=percent;$('size-number').value=percent;$('opacity').value=Math.round(settings.opacity*100);$('opacity-number').value=Math.round(settings.opacity*100);};
 function rememberPreset(){const p=getPreset(settings.preset);if(!p)return;saved.presets[p.id]={size:settings.size,opacity:settings.opacity};persist();}
 function renderCategories(){$('brush-categories').replaceChildren();for(const f of BRUSH_CATEGORIES){const p=BRUSH_PRESETS.find(x=>x.family===f),b=document.createElement('button');b.type='button';b.className='brush-category';b.textContent=p.category;b.dataset.active=String(f===family);b.setAttribute('aria-pressed',String(f===family));b.onclick=()=>{family=f;renderCategories();renderPresets();};$('brush-categories').append(b);}}
 function previewFor(p){if(sampleCache.has(p.id))return sampleCache.get(p.id);const stroke={id:'preview',brush:p.family,preset:p.id,color:'#203d48',size:p.defaultSize,opacity:p.defaultOpacity,points:[{x:16,y:30,pressure:.2},{x:50,y:16,pressure:.55},{x:92,y:36,pressure:1},{x:135,y:20,pressure:.65},{x:168,y:30,pressure:.35}]};const src=renderer.preview(stroke,180,56);sampleCache.set(p.id,src);return src;}
 function choosePreset(id,reset=false){if(blocked())return;rememberPreset();const p=getPreset(id);if(!p)return;family=p.family;settings.brush=p.family;settings.preset=p.id;const mem=!reset&&saved.presets[p.id];settings.size=clamp(Number(mem?.size??p.defaultSize),1,p.family==='airbrush'?160:40);settings.opacity=clamp(Number(mem?.opacity??p.defaultOpacity),0,1);syncControls();saved.presets[p.id]={size:settings.size,opacity:settings.opacity};persist();renderCategories();renderPresets();onPresetChange(p.id,reset);sample();}
 function renderPresets(){$('brush-presets').replaceChildren();$('extra-brush-presets').replaceChildren();for(const p of presetsFor(family)){const b=document.createElement('button');b.type='button';b.className='brush-preset';b.dataset.active=String(settings.preset===p.id);b.setAttribute('aria-pressed',String(settings.preset===p.id));const img=document.createElement('img');img.alt='';img.src=previewFor(p);const label=document.createElement('span');label.textContent=p.name;b.append(img,label);b.onclick=()=>choosePreset(p.id);$(EXTRA_BRUSH_PRESETS.includes(p)?'extra-brush-presets':'brush-presets').append(b);}const p=getPreset(settings.preset);$('brush-current').textContent=p?p.category+' · '+p.name:'Legacy brush';}
 $('reset-preset').onclick=()=>choosePreset(settings.preset,true);
 renderCategories();renderPresets();syncControls();

 const updateDot=()=>{$('colour-dot').style.background=settings.color;$('colour-toggle').setAttribute('aria-label','Colour '+settings.color);};
 function renderShades(){$('shade-swatches').replaceChildren();for(let i=0;i<12;i++){const l=8+i*(84/11),c=hslHex(hsv.h,Math.max(12,hsv.s*(.65+Math.abs(50-l)/140)),l),b=document.createElement('button');b.type='button';b.style.background=c;b.setAttribute('aria-label','Shade '+c);b.onclick=()=>setHex(c,true);$('shade-swatches').append(b);}}
 function renderList(id,arr,label){const root=$(id);root.replaceChildren();for(const c of arr){const b=document.createElement('button');b.type='button';b.style.background=c;b.setAttribute('aria-label',label+' '+c);b.onclick=()=>setHex(c,true);root.append(b);}}
 function syncColourControls(){$('color').value=settings.color;$('hue').value=Math.round(hsv.h);$('saturation').value=Math.round(hsv.s);$('value').value=Math.round(hsv.v);$('hue-value').value=Math.round(hsv.h)+'°';$('saturation-value').value=Math.round(hsv.s)+'%';$('value-value').value=Math.round(hsv.v)+'%';$('sv-disc').style.setProperty('--hue',hsv.h);$('hue-marker').style.transform='rotate('+(hsv.h-90)+'deg) translateX(91px)';$('sv-marker').style.left=hsv.s+'%';$('sv-marker').style.top=(100-hsv.v)+'%';updateDot();renderShades();renderList('recent-colours',saved.recent,'Recent colour');renderList('saved-palette',saved.palette,'Saved colour');sample();}
 function commitColour(){const c=settings.color.toLowerCase();saved.recent=[c,...saved.recent.filter(x=>x.toLowerCase()!==c)].slice(0,8);persist();renderList('recent-colours',saved.recent,'Recent colour');}
 function setHex(hex,commit=false){if(blocked())return;if(!/^#[0-9a-f]{6}$/i.test(hex)){status('Use a six-digit hex colour, for example #203d48',true);syncColourControls();return;}settings.color=hex.toLowerCase();hsv=hsvFromHex(settings.color,hsv.h);syncColourControls();if(commit)commitColour();}
 function setHsv(next,commit=false){if(blocked())return;hsv={h:(Number(next.h)%360+360)%360,s:clamp(Number(next.s),0,100),v:clamp(Number(next.v),0,100)};settings.color=hexFromHsv(hsv.h,hsv.s,hsv.v);syncColourControls();if(commit)commitColour();}
 function drag(kind,e){if(blocked())return;e.preventDefault();const el=e.currentTarget,box=el.getBoundingClientRect();if(!draft)draft={color:settings.color,hsv:{...hsv}};el.setPointerCapture?.(e.pointerId);const apply=ev=>{if(kind==='hue'){const x=ev.clientX-(box.left+box.width/2),y=ev.clientY-(box.top+box.height/2);setHsv({h:(Math.atan2(y,x)*180/Math.PI+90+360)%360,s:hsv.s,v:hsv.v});}else{setHsv({h:hsv.h,s:clamp((ev.clientX-box.left)/box.width*100,0,100),v:clamp((1-(ev.clientY-box.top)/box.height)*100,0,100)});}};apply(e);const move=ev=>{if(ev.pointerId===e.pointerId)apply(ev);};const done=ev=>{if(ev.pointerId!==e.pointerId)return;window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',done,true);window.removeEventListener('pointercancel',cancel,true);draft=null;commitColour();};const cancel=ev=>{if(ev.pointerId!==e.pointerId)return;window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',done,true);window.removeEventListener('pointercancel',cancel,true);const prior=draft;draft=null;if(prior){settings.color=prior.color;hsv=prior.hsv;syncColourControls();}};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',done,true);window.addEventListener('pointercancel',cancel,true);}
 $('hue-ring').addEventListener('pointerdown',e=>drag('hue',e));$('sv-disc').addEventListener('pointerdown',e=>drag('sv',e));
 $('color').onchange=()=>setHex($('color').value,true);
 for(const id of ['hue','saturation','value'])$(id).onchange=()=>setHsv({h:$('hue').value,s:$('saturation').value,v:$('value').value},true);
 $('save-colour').onclick=()=>{const c=settings.color.toLowerCase();saved.palette=[c,...saved.palette.filter(x=>x.toLowerCase()!==c)].slice(0,16);persist();renderList('saved-palette',saved.palette,'Saved colour');};
 $('clear-recents').onclick=()=>{saved.recent=[];persist();renderList('recent-colours',saved.recent,'Recent colour');};
 syncColourControls();
 return {syncPresetSettings:rememberPreset,currentPresetName:()=>presetLabel(settings.preset),setColour:(hex,commit=true)=>setHex(hex,commit)};
}
