import test from 'node:test';import assert from 'node:assert/strict';
const m=await import('../../prototypes/browser-workspace/model.js'),b=await import('../../prototypes/browser-workspace/brushes.js'),p=await import('../../prototypes/browser-workspace/pen-input.js'),s=await import('../../prototypes/browser-workspace/selection.js');
const d=()=>({size:true,opacity:true,minWidth:.08,minOpacity:.2,exponent:1.2,curve:[.2,.5,.8]});
const board=()=>{const q=m.createBoard('curve-board','CURVE fixture');q.layers[0].strokes=[{id:'curve-stroke',brush:'ink',preset:'ink-fineliner',size:20,opacity:.8,color:'#203d48',dynamics:d(),points:[{x:100,y:100,pressure:.25},{x:200,y:100,pressure:.75}]}];return q;};
test('CURVEM01 optional three finite monotonic inclusive curve values admitted',()=>{for(const curve of [[0,0,0],[1,1,1],[0,.5,1],[.2,.5,.8]]){const dynamics={...d(),curve};assert.equal(p.validateDynamics(dynamics),dynamics);const q=board();q.layers[0].strokes[0].dynamics=dynamics;assert.equal(m.validateBoard(q),q);}});
test('CURVEM02 invalid curve shape types values order and unknown fields reject atomically',()=>{const bad=[null,{},true,'curve',[],[0,.5],[0,.5,.8,1],['.2',.5,.8],[false,.5,.8],[NaN,.5,.8],[0,Infinity,1],[-.01,.5,1],[0,.5,1.01],[.6,.5,.8],[.2,.9,.8]];for(const curve of bad){const q=board();q.layers[0].strokes[0].dynamics.curve=curve;const before=structuredClone(q);assert.throws(()=>m.validateBoard(q),/curve|dynamic|pressure/i);assert.deepEqual(q,before);assert.throws(()=>m.importDocument(JSON.stringify(q)));const h=m.createHistory(board()),prior=structuredClone(h);assert.throws(()=>m.command(h,x=>{x.layers[0].strokes[0].dynamics.curve=curve;}));assert.deepEqual(h,prior);}assert.throws(()=>p.validateDynamics({...d(),curveMode:'custom'}));});
test('CURVEM03 knot response overrides exponent and no overshoot between fixed endpoints',()=>{const preset=b.getPreset('ink-fineliner');for(const curve of [[0,0,0],[1,1,1],[.2,.5,.8]])for(const exponent of [.7,1.2,2]){const dynamics={...d(),curve,exponent};for(const [input,response]of [[0,0],[.25,curve[0]],[.5,curve[1]],[.75,curve[2]],[1,1]]){assert(Math.abs(p.pressureWidth(preset,input,dynamics)-(.08+.92*response))<1e-12);assert(Math.abs(p.pressureOpacity(input,dynamics)-(.2+.8*response))<1e-12);}let last=0;for(let i=0;i<=1000;i++){const width=p.pressureWidth(preset,i/1000,dynamics);assert(width>=.08&&width<=1&&width>=last);last=width;}}});
test('CURVEM04 absent curve keeps exact old exponent formula and mouse null fullwidth',()=>{const dynamics=d();delete dynamics.curve;const preset=b.getPreset('ink-fineliner');for(const exponent of [.7,1.2,2])for(const input of [0,.1,.25,.5,.75,.9,1]){dynamics.exponent=exponent;assert.equal(p.pressureWidth(preset,input,dynamics),dynamics.minWidth+(1-dynamics.minWidth)*Math.pow(input,exponent));assert.equal(p.pressureOpacity(input,dynamics),dynamics.minOpacity+(1-dynamics.minOpacity)*Math.pow(input,exponent));}assert.equal(p.pressureWidth(preset,null,d()),1);assert.equal(p.pressureOpacity(null,d()),1);assert.equal(p.pressureWidth(preset,.5,{...d(),size:false}),1);assert.equal(p.pressureOpacity(.5,{...d(),opacity:false}),1);});
test('CURVEM05 snapshots survive import duplicate copy paste affine and history independently',()=>{const q=board(),before=structuredClone(q),curve=[.2,.5,.8],h=m.createHistory(q);const imported=m.importDocument(JSON.stringify(q));assert.deepEqual(imported.layers[0].strokes[0].dynamics.curve,curve);assert.deepEqual(m.layerCommand(h,'duplicate',q.activeLayer).board.layers[1].strokes[0].dynamics.curve,curve);const clip=s.copySelection(q,['curve-stroke']);clip.strokes[0].dynamics.curve[1]=.6;assert.deepEqual(q,before);const pasted=s.pasteSelection(h,s.copySelection(q,['curve-stroke']),400,400);assert.deepEqual(pasted.board.layers[0].strokes[1].dynamics.curve,curve);const transformed=s.transformSelection(h,['curve-stroke'],{dx:10,dy:5,scale:2,angle:30});assert.deepEqual(transformed.board.layers[0].strokes[0].dynamics.curve,curve);assert.deepEqual(m.undo(transformed).board.layers,q.layers);assert.deepEqual(m.redo(m.undo(transformed)).board.layers,transformed.board.layers);});
test('CURVEM06 partial eraser preserves curves without mutating origin and admission limits',()=>{const q=board(),before=structuredClone(q),next=m.eraseGesture(q,'partial',[{a:{x:150,y:80},b:{x:150,y:120}}],4);assert.equal(next.layers[0].strokes.length,2);for(const st of next.layers[0].strokes)assert.deepEqual(st.dynamics.curve,[.2,.5,.8]);next.layers[0].strokes[0].dynamics.curve[0]=.1;assert.deepEqual(q,before);const huge=board();huge.layers[0].strokes[0].points[1].x=1e7+1;assert.throws(()=>m.validateBoard(huge),/point|limit/i);});

test('CURVEM07 piecewise linear response midpoint values and bounded endpoints',()=>{const dynamics={...d(),curve:[.1,.6,.7]};for(const [input,expected]of [[0,0],[.125,.05],[.375,.35],[.625,.65],[.875,.85],[1,1]])assert(Math.abs(p.responsePressure(input,dynamics)-expected)<1e-12);assert.deepEqual(p.curveValues(dynamics),[.1,.6,.7]);const old=d();delete old.curve;assert.deepEqual(p.curveValues(old),[.25,.5,.75].map(x=>Math.pow(x,1.2)));});
test('CURVEM08 legacy local profile loads; invalid stored curve safely defaults',()=>{const previous=globalThis.localStorage;try{for(const curve of [[.2,.5,.8],undefined,[.8,.5,.2],[0,.5,NaN],[],null]){const dynamics=d();if(curve===undefined)delete dynamics.curve;else dynamics.curve=curve;globalThis.localStorage={getItem:()=>JSON.stringify({dynamics,mappings:{barrel:'pan',eraser:'none'}})};const cfg=p.readPenConfig();p.validateDynamics(cfg.dynamics);if(curve===undefined)assert(!Object.hasOwn(cfg.dynamics,'curve'));else if(Array.isArray(curve)&&curve.length===3&&curve[0]===.2)assert.deepEqual(cfg.dynamics.curve,curve);else assert.deepEqual(cfg.dynamics,p.DEFAULT_DYNAMICS);}}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous;}});

test('CURVEM09 new stroke and history snapshot detach mutable profile arrays',()=>{const q=m.createBoard('curve-snapshot','Snapshot'),h=m.createHistory(q),profile=d(),st={...board().layers[0].strokes[0],dynamics:profile},next=m.addStroke(h,st);profile.curve[0]=.1;assert.deepEqual(next.board.layers[0].strokes[0].dynamics.curve,[.2,.5,.8]);assert.equal(h.board.layers[0].strokes.length,0);assert.deepEqual(m.undo(next).board.layers,q.layers);assert.deepEqual(m.redo(m.undo(next)).board.layers,next.board.layers);});
