import test from 'node:test';import assert from 'node:assert/strict';
import {createBoard,createHistory,undo,redo,limits} from '../../prototypes/browser-workspace/model.js';
import {selectLasso,transformSelection,moveSelection,deleteSelection,copySelection,selectionBounds} from '../../prototypes/browser-workspace/selection.js';
const pt=(x,y)=>({x,y,pressure:.4}),stroke=(id,points)=>({id,brush:'ink',color:'#123456',size:2,opacity:.7,points});
const square=[pt(0,0),pt(100,0),pt(100,100),pt(0,100)];
function fixture(){const b=createBoard('ux2','UX2');b.layers[0].strokes=[stroke('a',[pt(10,10),pt(20,10)])];b.layers.push({...structuredClone(b.layers[0]),id:'second',name:'Second',strokes:[stroke('b',[pt(80,80),pt(90,80)])]});return b;}
const scope=b=>({layerIds:b.layers.map(l=>l.id)});
test('UX2M01 explicit layer scope, default active isolation and hostile scopes',()=>{const b=fixture();assert.deepEqual(selectLasso(b,square),['a']);assert.deepEqual(selectLasso(b,square,scope(b)),['a','b']);assert.throws(()=>selectionBounds(b,['b']));for(const layerIds of [[],['missing'],[b.activeLayer,b.activeLayer],null]){if(layerIds===null)continue;assert.throws(()=>selectLasso(b,square,{layerIds}));}assert.equal(selectionBounds(b,['a','b'],scope(b)).cx,50);});
test('UX2M02 shared pivot, layer ownership/style, atomic undo and redo',()=>{const b=fixture(),h=createHistory(b),before=structuredClone(h),next=transformSelection(h,['a','b'],{scale:2,angle:90},scope(b));assert.equal(next.past.length,1);assert.deepEqual(next.board.layers.map(l=>l.strokes.map(s=>s.id)),[['a'],['b']]);for(let i=0;i<2;i++){const old=b.layers[i].strokes[0],now=next.board.layers[i].strokes[0];assert.equal(now.size,old.size);assert.equal(now.opacity,old.opacity);for(let j=0;j<old.points.length;j++){assert(Math.abs(now.points[j].x-(50-2*(old.points[j].y-45)))<1e-7);assert(Math.abs(now.points[j].y-(45+2*(old.points[j].x-50)))<1e-7);assert.equal(now.points[j].pressure,.4);}}assert.deepEqual(undo(next).board.layers,b.layers);assert.deepEqual(redo(undo(next)).board.layers,next.board.layers);assert.deepEqual(h,before);});
test('UX2M03 one hidden or locked scoped layer rejects entire write',()=>{for(const field of ['locked','visible']){const b=fixture();b.layers[1][field]=field==='locked';const h=createHistory(b),before=structuredClone(h);for(const fn of [()=>selectLasso(b,square,scope(b)),()=>transformSelection(h,['a','b'],{scale:2},scope(b)),()=>moveSelection(h,['a','b'],1,1,scope(b)),()=>deleteSelection(h,['a','b'],scope(b))])assert.throws(fn);assert.deepEqual(h,before);}});
test('UX2M04 scoped copy/delete/move keep unrelated layers and IDs',()=>{const b=fixture(),h=createHistory(b);assert.equal(copySelection(b,['a','b'],scope(b)).strokes.length,2);const moved=moveSelection(h,['a','b'],7,-8,scope(b));assert.equal(moved.board.layers[1].strokes[0].points[0].x,87);assert.deepEqual(deleteSelection(h,['a','b'],scope(b)).board.layers.map(l=>l.strokes),[[],[]]);assert.deepEqual(deleteSelection(h,['a'],scope(b)).board.layers[1],b.layers[1]);});
test('UX2M05 100k-point board, 512-edge lasso stays within original work cap',()=>{const b=createBoard('dense','Dense');b.layers[0].strokes=[stroke('dense-stroke',Array.from({length:limits.points},(_,i)=>pt(200+i%50,200+i%31)))];const polygon=Array.from({length:512},(_,i)=>pt(500+350*Math.cos(i*2*Math.PI/512),500+350*Math.sin(i*2*Math.PI/512))),stats={};const start=performance.now();assert.deepEqual(selectLasso(b,polygon,{stats}),[]);assert(stats.comparisons<200000);console.log(JSON.stringify({fixturePoints:limits.points,polygonEdges:512,comparisons:stats.comparisons,elapsedMs:performance.now()-start}));});
function naive(points,polygon){const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),on=(p,a,b)=>Math.abs(cross(a,b,p))<=1e-7&&p.x>=Math.min(a.x,b.x)-1e-7&&p.x<=Math.max(a.x,b.x)+1e-7&&p.y>=Math.min(a.y,b.y)-1e-7&&p.y<=Math.max(a.y,b.y)+1e-7,seg=(a,b,c,d)=>on(a,c,d)||on(b,c,d)||on(c,a,b)||on(d,a,b)||((cross(a,b,c)>0)!==(cross(a,b,d)>0)&&(cross(c,d,a)>0)!==(cross(c,d,b)>0));for(let i=0;i<points.length;i++){let inside=false;for(let j=0;j<polygon.length;j++){const a=polygon[j],b=polygon[(j+1)%polygon.length];if(on(points[i],a,b))return true;if((a.y>points[i].y)!==(b.y>points[i].y)&&points[i].x<(b.x-a.x)*(points[i].y-a.y)/(b.y-a.y)+a.x)inside=!inside;if(i&&seg(points[i-1],points[i],a,b))return true;}if(inside)return true;}return false;}
test('UX2M06 exact indexed truth agrees with naive oracle for 1000 concave cases',()=>{let seed=12345;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);for(let n=0;n<1000;n++){const poly=Array.from({length:12},(_,i)=>{const r=i%2?20:60;return pt(100+r*Math.cos(i*Math.PI/6),100+r*Math.sin(i*Math.PI/6));}),points=Array.from({length:5},()=>pt(random()*240,random()*240)),b=createBoard('fuzz','Fuzz');b.layers[0].strokes=[stroke('s',points)];assert.equal(selectLasso(b,poly).length>0,naive(points,poly));}});
test('UX2M07 original comparison cap remains enforced atomically',()=>{const b=fixture(),before=structuredClone(b);assert.throws(()=>selectLasso(b,square,{comparisons:1}));assert.throws(()=>selectLasso(b,square,{comparisons:200001}));assert.deepEqual(b,before);});
