const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.UNRULY_TEST_URL||'http://127.0.0.1:4173/unruly/',out=path.join(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});let browser;const results=[];
const strokes=b=>b.layers.flatMap(l=>l.strokes);
async function ready(p){await p.waitForFunction(()=>/Saved on this device|Copied \d+ old boards|Recovery warning/.test(document.querySelector('#save')?.textContent),null,{timeout:10000});}
async function board(p){return p.evaluate(()=>new Promise((ok,no)=>{const q=indexedDB.open('unruly-workspace-v3',1);q.onerror=()=>no(q.error);q.onsuccess=()=>{const db=q.result,t=db.transaction(['boards','meta']),a=t.objectStore('boards').getAll(),m=t.objectStore('meta').get('lastBoard');t.oncomplete=()=>{db.close();ok(a.result.find(r=>r.id===m.result).current);};};}));}
async function settle(p){await p.waitForTimeout(600);}
async function run(id,fn,{width=1440,height=950,dpr=1}={}){const c=await browser.newContext({viewport:{width,height},deviceScaleFactor:dpr,hasTouch:true,acceptDownloads:true});await c.tracing.start({screenshots:true,snapshots:true});const p=await c.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)external.push(r.url());});try{await c.addInitScript(()=>{window.__u3events=[];for(const type of ['pointerdown','pointerup','gotpointercapture','lostpointercapture','pointercancel'])document.addEventListener(type,e=>__u3events.push({type,id:e.pointerId,pointerType:e.pointerType}),true);});await p.goto(base);await ready(p);const evidence=await fn(p,c);assert.deepEqual(errors,[],'uncaught errors');assert.deepEqual(external,[],'external assets');results.push({id,status:'PASS',evidence});await p.screenshot({path:path.join(out,id+'.png'),fullPage:true});}catch(e){results.push({id,status:'FAIL',message:e.stack,errors,external});await p.screenshot({path:path.join(out,id+'-failure.png'),fullPage:true}).catch(()=>{});await c.tracing.stop({path:path.join(out,id+'-trace.zip')});console.error(id,e.message);}finally{await c.tracing.stop().catch(()=>{});await c.close();}}
async function pen(p,points,{hold=false,release=true}={}){const b=await p.locator('#canvas').boundingBox(),c=await p.context().newCDPSession(p);const send=(type,xy,force=.4)=>c.send('Input.dispatchMouseEvent',{type,x:b.x+xy[0],y:b.y+xy[1],button:'left',buttons:type==='mouseReleased'?0:1,pointerType:'pen',force:type==='mouseReleased'?0:force,clickCount:1});await send('mousePressed',points[0]);for(const xy of points.slice(1))await send('mouseMoved',xy);if(hold){await p.waitForTimeout(750);await p.waitForFunction(()=>/recognized/.test(document.querySelector('#save').textContent));}if(release){await send('mouseReleased',points.at(-1));await c.detach();}return {c,send};}
async function ink(p,y=350){await pen(p,[[500,y],[530,y+2],[560,y]]);await settle(p);}
async function touch(p,n,{move=0,cancel=false,duration=0,fourth=false}={}){const b=await p.locator('#canvas').boundingBox(),c=await p.context().newCDPSession(p);let pts=Array.from({length:n},(_,i)=>({x:b.x+600+i*35,y:b.y+400,id:i+1}));await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pts});if(fourth){pts.push({x:b.x+720,y:b.y+400,id:4});await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pts});}if(move){pts=pts.map(q=>({...q,x:q.x+move}));await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:pts});}if(duration)await p.waitForTimeout(duration);if(cancel)await c.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});else {while(pts.length){pts=pts.slice(1);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:pts});}}await c.detach();}
async function change(p,id,value){await p.locator('#'+id).fill(String(value));await p.locator('#'+id).dispatchEvent('change');}
async function line(p){await pen(p,[[500,350],[540,350],[580,350],[620,350]],{hold:true});await p.locator('#shape-controls').waitFor({state:'visible'});assert.equal(await p.locator('#shape-kind').textContent(),'Line');}
async function fixture(p){await p.evaluate(async()=>{const {createBoard}=await import('./model.js'),{openStore}=await import('./storage.js'),s=await openStore(),b=createBoard('u3-fixture','U3 deterministic');b.layers[0].strokes=[{id:'u3-style',brush:'ink',preset:'ink-fineliner',color:'#123456',size:12,opacity:.7,points:[{x:500,y:350,pressure:0},{x:600,y:350,pressure:1}]}];await s.save(b,0);await s.select(b.id);s.close();});await p.reload();await ready(p);}
async function select(p){await p.locator('#lasso').click();await p.keyboard.press('Escape');await pen(p,[[470,320],[630,320],[630,380],[470,380],[470,320]]);await p.waitForFunction(()=>document.querySelector('#selection-count').textContent==='1 selected');await p.locator('#canvas').focus();await p.keyboard.press('v');await p.locator('#transform-controls').waitFor({state:'visible'});}
async function layersFixture(p){await p.evaluate(async()=>{const{createBoard}=await import('./model.js'),{openStore}=await import('./storage.js'),s=await openStore(),b=createBoard('ux2-fixture','UX2 layers');const stroke=(id,x,y)=>({id,brush:'ink',color:'#123456',size:4,opacity:.7,points:[{x,y,pressure:.2},{x:x+40,y,pressure:.8}]});b.layers[0].strokes=[stroke('lower',480,330)];b.layers.push({...structuredClone(b.layers[0]),id:'upper-layer',name:'Upper',strokes:[stroke('upper',580,380)]});await s.save(b,0);await s.select(b.id);s.close();});await p.reload();await ready(p);}
async function includeBoth(p,modifier=false){await p.locator('#layers-toggle').click();if(modifier)await p.getByRole('button',{name:'Select Upper',exact:true}).click({modifiers:['Control']});else await p.getByRole('button',{name:'Include Upper in selection',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Include Upper in selection',exact:true}).getAttribute('aria-pressed'),'true');await p.locator('#close-panels').click();}
async function groupSelect(p){await p.locator('#lasso').click();await p.keyboard.press('Escape');await pen(p,[[450,300],[650,300],[650,420],[450,420],[450,300]]);await p.waitForFunction(()=>document.querySelector('#selection-count').textContent==='2 selected');await p.locator('#quick-transform').click();}
async function twist(p,{cancel=false,partial=false}={}){const b=await p.locator('#canvas').boundingBox(),c=await p.context().newCDPSession(p),pts=[{x:b.x+500,y:b.y+500,id:1},{x:b.x+600,y:b.y+500,id:2}],end=[{x:b.x+550,y:b.y+400,id:1},{x:b.x+550,y:b.y+600,id:2}];await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pts});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:end});await p.waitForTimeout(40);if(partial){await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[end[1]]});await c.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});}else await c.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});await c.detach();}
(async()=>{browser=await chromium.launch({headless:true});
await run('UX2B01-ctrl-and-tablet-layer-scope',async p=>{await layersFixture(p);const before=await board(p);await includeBoth(p,true);await groupSelect(p);assert.deepEqual(await board(p),before);await p.locator('#cancel-transform').click();await p.locator('#layers-toggle').click();await p.getByRole('button',{name:'Include Upper in selection',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Include Upper in selection',exact:true}).getAttribute('aria-pressed'),'false');await p.getByRole('button',{name:'Include Upper in selection',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Select Layer 1',exact:true}).getAttribute('aria-pressed'),'true','drawing layer stays active');},{width:1024,height:768});
for(const[width,height]of[[1024,768],[768,1024]])await run(`UX2B02-${width}-two-finger-shared-pivot-apply-undo`,async p=>{await layersFixture(p);const before=await board(p);await includeBoth(p);await groupSelect(p);const zoom=await p.locator('#zoom').textContent();await twist(p);assert(Math.abs(Number(await p.locator('#transform-angle').inputValue())-90)<1e-5);assert(Math.abs(Number(await p.locator('#transform-scale').inputValue())-200)<1e-5);assert.equal(await p.locator('#zoom').textContent(),zoom);await settle(p);assert.deepEqual(await board(p),before);await p.locator('#undo').click();assert.equal(Number(await p.locator('#transform-angle').inputValue()),0);await p.locator('#redo').click();assert.equal(Number(await p.locator('#transform-angle').inputValue()),90);await p.locator('#apply-transform').click();await settle(p);const after=await board(p);assert.deepEqual(after.layers.map(l=>l.strokes.map(s=>s.id)),[['lower'],['upper']]);for(let i=0;i<2;i++){const a=before.layers[i].strokes[0],b=after.layers[i].strokes[0];for(let j=0;j<2;j++){assert(Math.abs(b.points[j].x-(550-2*(a.points[j].y-500)))<1e-5);assert(Math.abs(b.points[j].y-(500+2*(a.points[j].x-550)))<1e-5);assert.equal(b.points[j].pressure,a.points[j].pressure);}assert.equal(b.size,a.size);}await p.locator('#undo').click();await settle(p);assert.deepEqual((await board(p)).layers,before.layers);await p.locator('#redo').click();await settle(p);assert.deepEqual((await board(p)).layers,after.layers);},{width,height});
await run('UX2B03-pointer-cancel-and-partial-release-rollback',async p=>{await layersFixture(p);await includeBoth(p);await groupSelect(p);const before=await board(p);for(const options of[{cancel:true},{partial:true}]){await twist(p,options);assert.equal(Number(await p.locator('#transform-angle').inputValue()),0);assert.equal(Number(await p.locator('#transform-scale').inputValue()),100);assert(await p.locator('#undo').isDisabled(),'cancel adds no local history');}await p.locator('#cancel-transform').click();await settle(p);assert.deepEqual(await board(p),before);});
await run('UX2B04-locked-scope-is-atomic',async p=>{await layersFixture(p);await p.evaluate(async()=>{const{openStore}=await import('./storage.js'),s=await openStore(),r=await s.load('ux2-fixture');r.board.layers[1].locked=true;r.board.revision++;await s.save(r.board,r.dbRevision);s.close();});await p.reload();await ready(p);await includeBoth(p);const before=await board(p);await p.locator('#lasso').click();await p.keyboard.press('Escape');await pen(p,[[450,300],[650,300],[650,420],[450,420],[450,300]]);assert.equal(await p.locator('#selection-count').textContent(),'0 selected');assert.match(await p.locator('#save').textContent(),/locked or hidden/);await settle(p);assert.deepEqual(await board(p),before);});
await run('UX2B05-single-finger-and-three-finger-abort',async p=>{await fixture(p);await select(p);await touch(p,1,{move:30});assert.equal(Number(await p.locator('#transform-x').inputValue()),0);const b=await p.locator('#canvas').boundingBox(),c=await p.context().newCDPSession(p),pts=[{x:b.x+500,y:b.y+500,id:1},{x:b.x+600,y:b.y+500,id:2}];await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pts});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:pts.map(q=>({...q,x:q.x+30}))});await p.waitForTimeout(40);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...pts.map(q=>({...q,x:q.x+30})),{x:b.x+700,y:b.y+500,id:3}]});assert.equal(Number(await p.locator('#transform-x').inputValue()),0);await c.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await c.detach();assert(await p.locator('#undo').isDisabled());});
await run('UX2B06-dense-lasso-overlay-zero-artwork-replay',async p=>{await p.evaluate(async()=>{const{createBoard}=await import('./model.js'),{openStore}=await import('./storage.js'),s=await openStore(),b=createBoard('ux2-dense','Dense 100k');b.layers[0].strokes=[{id:'dense-stroke',brush:'ink',color:'#123456',size:2,opacity:.7,points:Array.from({length:100000},(_,i)=>({x:200+i%50,y:200+i%31,pressure:.4}))}];await s.save(b,0);await s.select(b.id);s.close();});await p.reload();await ready(p);await p.locator('#lasso').click();await p.keyboard.press('Escape');await p.waitForTimeout(100);await p.evaluate(()=>{window.__artReplay=0;for(const name of ['stroke','fill','drawImage','clearRect']){const original=CanvasRenderingContext2D.prototype[name];CanvasRenderingContext2D.prototype[name]=function(...args){if(this.canvas.id==='canvas')window.__artReplay++;return original.apply(this,args);};}});const points=Array.from({length:100},(_,i)=>[500+240*Math.cos(i*2*Math.PI/99),350+240*Math.sin(i*2*Math.PI/99)]),start=Date.now(),q=await pen(p,points,{release:false});await p.waitForTimeout(50);const repaint=await p.evaluate(()=>__artReplay);assert.equal(repaint,0,'lasso overlay must not replay unchanged artwork');await q.send('mouseReleased',points.at(-1));await q.c.detach();assert(!/work limit/.test(await p.locator('#save').textContent()));const metrics=await p.evaluate(async()=>{const{selectLasso}=await import('./selection.js'),{openStore}=await import('./storage.js'),s=await openStore(),r=await s.load('ux2-dense'),stats={},poly=Array.from({length:512},(_,i)=>({x:500+350*Math.cos(i*2*Math.PI/512),y:500+350*Math.sin(i*2*Math.PI/512)})),start=performance.now();selectLasso(r.board,poly,{stats});s.close();return{comparisons:stats.comparisons,selectionMs:performance.now()-start,points:100000,edges:512};});assert(metrics.comparisons<200000);return{...metrics,artworkReplaysDuringLasso:repaint,gestureElapsedMs:Date.now()-start};},{width:1024,height:768});
fs.writeFileSync(path.join(out,'layer-transform-browser-results.json'),JSON.stringify({browser:browser.version(),physical_tablet:'NOT_VERIFIED',results},null,2));await browser.close();console.log(JSON.stringify(results));process.exitCode=results.some(r=>r.status==='FAIL')?1:0;})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
