const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.UNRULY_TEST_URL||'http://127.0.0.1:4173/unruly/';const out=__dirname+'/evidence';fs.mkdirSync(out,{recursive:true});
async function ready(p){await p.waitForFunction(()=>/Saved on this device|Imported/.test(document.querySelector('#save').textContent));await p.waitForTimeout(120);}
async function settle(p){await p.waitForTimeout(650);}
async function board(p){return p.evaluate(()=>new Promise(ok=>{const q=indexedDB.open('unruly-workspace-v3');q.onsuccess=()=>{const db=q.result,t=db.transaction(['boards','meta']),a=t.objectStore('boards').getAll(),m=t.objectStore('meta').get('lastBoard');t.oncomplete=()=>{db.close();ok(a.result.find(r=>r.id===m.result).current);};};}));}
async function open(p){if(!await p.locator('#brush-popover').isVisible())await p.locator('#pen').click();if(!await p.locator('#brush-advanced').evaluate(e=>e.open))await p.locator('#brush-advanced summary').click();}
async function choose(p,family,name){if(!await p.locator('#brush-popover').isVisible())await p.locator('#pen').click();await p.locator('#brush-categories').getByRole('button',{name:family,exact:true}).click();await p.locator('#brush-presets').getByRole('button',{name,exact:true}).click();await open(p);}
async function set(p,id,value){await p.locator('#'+id).fill(String(value));await p.locator('#'+id).dispatchEvent('change');}
async function draw(p,y=150){await p.keyboard.press('Escape');const r=await p.locator('#canvas').boundingBox();await p.mouse.move(r.x+130,r.y+y);await p.mouse.down();await p.mouse.move(r.x+340,r.y+y+20,{steps:12});await p.mouse.up();await settle(p);}
async function pixels(p){await p.waitForTimeout(120);return p.locator('#canvas').evaluate(e=>e.toDataURL());}
(async()=>{const b=await chromium.launch(),results=[];try{for(const viewport of [{width:1024,height:768},{width:768,height:1024}]){const c=await b.newContext({viewport,hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await ready(p);
 const kernel=await p.evaluate(async()=>{const {createRenderer}=await import('./render.js'),{BRUSH_PRESETS,EXTRA_BRUSH_PRESETS}=await import('./brushes.js');const {DEFAULT_RECIPE}=await import('./brush-recipe.js');const r=createRenderer(document.createElement('canvas')),pts=[{x:20,y:35,pressure:0},{x:80,y:45,pressure:.5},{x:155,y:30,pressure:1}],same=[];for(const p of [...BRUSH_PRESETS,...EXTRA_BRUSH_PRESETS]){const s={id:'fixture',preset:p.id,brush:p.family,size:20,opacity:.7,color:'#234567',points:pts};if(r.preview(s,180,90)!==r.preview({...s,recipe:{...DEFAULT_RECIPE}},180,90))throw Error('Neutral recipe changed '+p.id);same.push(p.id);}const s={id:'fixture',preset:'pencil-hb',brush:'pencil',size:20,opacity:1,color:'#234567',points:pts};const original=r.preview(s,180,90);const variants=[{...DEFAULT_RECIPE,density:.2},{...DEFAULT_RECIPE,spacing:3},{...DEFAULT_RECIPE,grain:1},{...DEFAULT_RECIPE,tip:'flat'}];for(const recipe of variants){const custom={...s,recipe};if(original===r.preview(custom,180,90))throw Error('Custom setting did not affect pixels');if(r.preview(custom,180,90)!==r.preview(custom,180,90))throw Error('Nondeterministic custom recipe');}return {neutralPresets:same.length,distinctVariants:variants.length};});
 await choose(p,'Pencil','HB');await p.locator('#brush-custom-enabled').check();await set(p,'brush-density',40);await set(p,'brush-spacing',200);await set(p,'brush-grain',80);await p.locator('#size-number').fill('70');await p.locator('#size-number').dispatchEvent('input');await draw(p);const first=await board(p),s=first.layers.flatMap(l=>l.strokes).at(-1),expected={version:1,density:.4,spacing:2,grain:.8,tip:'preset'};assert.deepEqual(s.recipe,expected);const drawn=await pixels(p);
 await open(p);await set(p,'brush-density',70);assert.deepEqual(await board(p),first,'settings edits never alter saved board/history');await set(p,'brush-density',0);assert.equal(await p.locator('#brush-density').inputValue(),'70','invalid input restores validated controls');assert.deepEqual(await board(p),first);await set(p,'brush-density',40);
 await p.locator('#brush-comparison summary').click();await p.locator('#compare-capture-a').click();assert.match(await p.locator('#compare-label-a').textContent(),/custom brush/);await choose(p,'Pen','Fineliner');assert.equal(await p.locator('#brush-custom-enabled').isChecked(),false);await p.locator('#brush-custom-enabled').check();await p.locator('#brush-tip').selectOption('flat');assert.equal(await p.locator('#brush-grain').isDisabled(),true);await choose(p,'Pencil','HB');assert.equal(await p.locator('#brush-density').inputValue(),'40');assert.equal(await p.locator('#brush-grain').inputValue(),'80');
 await p.keyboard.press('Escape');await p.locator('#undo').click();await settle(p);assert.equal((await board(p)).layers.flatMap(l=>l.strokes).length,0);await p.locator('#redo').click();await settle(p);assert.equal(await pixels(p),drawn,'custom stroke undo/redo exact pixels');await p.reload();await ready(p);assert.equal(await pixels(p),drawn,'custom stroke reload exact pixels');assert.deepEqual((await board(p)).layers,first.layers);await choose(p,'Pencil','HB');assert.equal(await p.locator('#brush-custom-enabled').isChecked(),true);assert.equal(await p.locator('#brush-grain').inputValue(),'80');await p.locator('#brush-recipe-reset').click();assert.equal(await p.locator('#brush-custom-enabled').isChecked(),false);assert.deepEqual((await board(p)).layers,first.layers);await choose(p,'Pen','Fineliner');assert.equal(await p.locator('#brush-custom-enabled').isChecked(),true,'reset leaves other preset custom controls');await p.locator('#brush-recipe-reset').click();
 await p.keyboard.press('Escape');await p.locator('#import-file').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(first))});await settle(p);assert.deepEqual((await board(p)).layers[0].strokes[0].recipe,expected);assert.equal(await pixels(p),drawn,'custom JSON import exact pixels');
 // Real pen cancellation must discard tentative custom input and leave saved board intact.
 await choose(p,'Pencil','HB');await p.locator('#brush-custom-enabled').check();await set(p,'brush-grain',90);await p.keyboard.press('Escape');const prior=await board(p),r=await p.locator('#canvas').boundingBox(),cdp=await c.newCDPSession(p);await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:r.x+160,y:r.y+260,pointerType:'pen',force:.3,button:'left',buttons:1,clickCount:1});await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:r.x+260,y:r.y+280,pointerType:'pen',force:.8,button:'left',buttons:1});assert.notEqual(await pixels(p),drawn,'tentative custom pen stroke is actually rendered before cancellation');await p.locator('#canvas').evaluate(el=>el.dispatchEvent(new PointerEvent('pointercancel',{pointerId:2,pointerType:'pen',bubbles:true})));await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:r.x+260,y:r.y+280,pointerType:'pen',force:0,button:'left',buttons:0,clickCount:1});await settle(p);assert.deepEqual(await board(p),prior,'cancelled custom stroke cannot commit');await cdp.detach();assert.deepEqual(errors,[]);results.push({viewport,status:'PASS',kernel});await open(p);await p.screenshot({path:out+'/b02-'+viewport.width+'.png',fullPage:true});await c.close();}
 // Corrupt device recipe storage must fall back safely without corrupting boards.
 const c=await b.newContext(),p=await c.newPage();await c.addInitScript(()=>localStorage.setItem('unruly-brush-recipes-v1',JSON.stringify({'ink-fineliner':{version:99,density:1,spacing:1,grain:0,tip:'flat'},unknown:{}})));await p.goto(base);await ready(p);await open(p);assert.equal(await p.locator('#brush-custom-enabled').isChecked(),false);await c.close();fs.writeFileSync(out+'/recipe-browser-results.json',JSON.stringify({results,physicalDevice:'NOT_VERIFIED'}));console.log(results);
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
