import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_RECIPE,validateRecipe,applyRecipe} from '../../prototypes/browser-workspace/brush-recipe.js';
import {BRUSH_PRESETS,EXTRA_BRUSH_PRESETS,getPreset,replayWork,effectivePreset} from '../../prototypes/browser-workspace/brushes.js';
import * as m from '../../prototypes/browser-workspace/model.js';import * as q from '../../prototypes/browser-workspace/selection.js';
const recipe=extra=>({...DEFAULT_RECIPE,...extra}),stroke=(extra={})=>({id:'recipe-stroke',brush:'pencil',preset:'pencil-6b',size:10,opacity:.7,color:'#123abc',points:[{x:0,y:0,pressure:0},{x:100,y:0,pressure:1}],recipe:recipe({density:.4,spacing:2,grain:.8}),...extra});
function board(s=stroke()){const b=m.createBoard('recipe-board','Recipe fixture');b.layers[0].strokes=[s];return b;}
test('B02M01 every immutable preset retains identity for absent and neutral recipe',()=>{for(const p of [...BRUSH_PRESETS,...EXTRA_BRUSH_PRESETS]){assert.equal(applyRecipe(p,undefined),p);assert.equal(applyRecipe(p,recipe()),p);assert(Object.isFrozen(p));}});
test('B02M02 malformed versions, keys and finite limits reject',()=>{for(const r of [null,[],{},recipe({version:2}),recipe({density:0}),recipe({density:1.01}),recipe({spacing:.49}),recipe({spacing:3.01}),recipe({grain:-.1}),recipe({grain:1.01}),recipe({tip:'unknown'}),recipe({density:NaN}),recipe({spacing:Infinity}),recipe({extra:1}),recipe({density:'1'})])assert.throws(()=>validateRecipe(r,'pencil'));});
test('B02M03 grain only on original pencil tips; unknown families reject',()=>{for(const f of ['ink','marker','airbrush','unknown'])assert.throws(()=>validateRecipe(recipe({grain:.1}),f));assert.throws(()=>validateRecipe(recipe({grain:1,tip:'flat'}),'pencil'));assert.equal(validateRecipe(recipe({grain:1}),'pencil').grain,1);});
test('B02M04 density and spacing affect exact budget independently',()=>{const s=stroke({size:10,points:[{x:0,y:0,pressure:null},{x:100,y:0,pressure:null}],recipe:recipe({density:.5,spacing:2})});const p=effectivePreset(s);assert.equal(p.particles,14);assert.equal(p.stepFactor,.36);assert.deepEqual(replayWork(s),{dabs:29,particles:406});assert.equal(getPreset('pencil-6b').particles,28);});
test('B02M05 continuous ink becomes budgeted stamps for changed spacing or tip',()=>{const s=stroke({brush:'ink',preset:'ink-fineliner',recipe:recipe()});assert.deepEqual(replayWork(s),{dabs:0,particles:0});for(const r of [recipe({spacing:2}),recipe({tip:'flat'}),recipe({tip:'round'})]){s.recipe=r;assert(replayWork(s).dabs>1);assert.equal(replayWork(s).particles,replayWork(s).dabs);}});
test('B02M06 dab boundary counts first stamp; overflow leaves source/history untouched',()=>{const s=stroke({brush:'ink',preset:'ink-fineliner',size:1,recipe:recipe({tip:'round'}),points:[{x:0,y:0,pressure:null},{x:9999.5,y:0,pressure:null}]});assert.deepEqual(replayWork(s),{dabs:20000,particles:20000});m.validateBoard(board(s));const h=m.createHistory(m.createBoard('empty')),prior=structuredClone(h);s.points[1].x=10000;assert.throws(()=>m.addStroke(h,s),/replay/);assert.deepEqual(h,prior);});
test('B02M07 particle boundary is enforced separately from dabs',()=>{const s=stroke({preset:'pencil-charcoal',size:1,recipe:recipe(),points:[{x:0,y:0,pressure:null},{x:9999.5,y:0,pressure:null}]});assert.equal(replayWork(s).particles,600000);m.validateBoard(board(s));s.points[1].x=10000;assert.throws(()=>m.validateBoard(board(s)),/replay|particle/);});
test('B02M08 recipes reject absent, mismatched and unknown presets',()=>{for(const changes of [{preset:undefined},{preset:'unknown'},{preset:'ink-fineliner'},{recipe:undefined}])assert.throws(()=>m.validateBoard(board(stroke(changes))));const s=stroke();delete s.preset;assert.throws(()=>m.validateBoard(board(s)));});
test('B02M09 v1/v2 imports cannot introduce recipes',()=>{const s=stroke();delete s.preset;const v2=board(s);v2.version=2;delete v2.layers[0].blend;assert.throws(()=>m.importDocument(JSON.stringify(v2)));const v1={version:1,id:'old',title:'Legacy',revision:0,strokes:[s]};assert.throws(()=>m.importDocument(JSON.stringify(v1)));});
test('B02M10 import, copy/paste, duplicate and transform preserve independent recipe snapshots',()=>{const b=board(),r=structuredClone(b.layers[0].strokes[0].recipe),imported=m.importDocument(JSON.stringify(b));assert.deepEqual(imported.layers[0].strokes[0].recipe,r);const clip=q.copySelection(b,['recipe-stroke']);let h=m.createHistory(b);h=q.pasteSelection(h,clip,200,20);assert.deepEqual(h.board.layers[0].strokes[1].recipe,r);clip.strokes[0].recipe.grain=0;assert.deepEqual(h.board.layers[0].strokes[1].recipe,r);h=q.transformSelection(h,['recipe-stroke'],{scale:1.5,angle:45});assert.deepEqual(h.board.layers[0].strokes[0].recipe,r);h=m.layerCommand(h,'duplicate',h.board.activeLayer);assert.deepEqual(h.board.layers[1].strokes[0].recipe,r);});
test('B02M11 partial erase retains recipes and exact undo/redo metadata',()=>{const b=board(stroke({size:2})),erased=m.eraseGesture(b,'partial',[{a:{x:50,y:-10},b:{x:50,y:10}}],4);assert.equal(erased.layers[0].strokes.length,2);for(const s of erased.layers[0].strokes)assert.deepEqual(s.recipe,b.layers[0].strokes[0].recipe);let h=m.createHistory(b);h=m.command(h,x=>x.layers=erased.layers);const u=m.undo(h);assert.deepEqual(u.board.layers,b.layers);assert.deepEqual(m.redo(u).board.layers,erased.layers);});
test('B02M12 flat-tip corners lie strictly inside nominal brush radius at every rotation',()=>{for(let angle=0;angle<360;angle+=3){const a=angle*Math.PI/180;for(const x of [-.45,.45])for(const y of [-.18,.18]){const rx=x*Math.cos(a)-y*Math.sin(a),ry=x*Math.sin(a)+y*Math.cos(a);assert(Math.hypot(rx,ry)<.5);}}});

test('B02M13 custom solid tips discard inherited scatter particle budgets',()=>{for(const tip of ['round','flat']){const s=stroke({brush:'airbrush',preset:'airbrush-cloud',size:1,recipe:recipe({tip}),points:[{x:0,y:0,pressure:null},{x:9999.5,y:0,pressure:null}]});assert.deepEqual(replayWork(s),{dabs:20000,particles:20000});m.validateBoard(board(s));s.points[1].x=10000;assert.throws(()=>m.validateBoard(board(s)),/replay/);}});
test('B02M14 particle-only overflow rejects atomically below the dab cap',()=>{const s=stroke({brush:'airbrush',preset:'airbrush-cloud',size:1,recipe:recipe(),points:[{x:0,y:0,pressure:null},{x:8332.5,y:0,pressure:null}]});assert.deepEqual(replayWork(s),{dabs:16666,particles:599976});m.validateBoard(board(s));s.points[1].x=8333;assert.deepEqual(replayWork(s),{dabs:16667,particles:600012});const h=m.createHistory(m.createBoard('particle-limit')),prior=structuredClone(h);assert.throws(()=>m.addStroke(h,s),/particle/);assert.deepEqual(h,prior);});
