const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.UNRULY_TEST_URL||'http://127.0.0.1:4173/unruly/',out=path.join(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});let browser;const results=[];
async function ready(p){await p.waitForFunction(()=>/Saved on this device|Copied \d+ old boards|Recovery warning/.test(document.querySelector('#save')?.textContent));}
async function run(id,fn,dpr=1){const c=await browser.newContext({viewport:{width:1024,height:768},deviceScaleFactor:dpr,hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.goto(base);await ready(p);const evidence=await fn(p,c);assert.deepEqual(errors,[]);results.push({id,status:'PASS',evidence});}catch(e){results.push({id,status:'FAIL',error:e.stack,errors});await p.screenshot({path:path.join(out,id+'-failure.png')}).catch(()=>{});console.error(id,e.message);}finally{await c.close();}}
async function setup(p){await p.evaluate(async()=>{
 const m=await import('./model.js'),f=await import('./render.js'),raw=await import('./canvas2d-renderer.js'),rs=await import('./raster.js');
 const create=()=>{const c=document.createElement('canvas');c.style.cssText='position:fixed;left:0;top:0;width:256px;height:192px;visibility:hidden;pointer-events:none';document.body.append(c);return c;};
 const a=create(),z=create(),r=f.createRenderer(a),direct=raw.createCanvas2DRenderer(z);
 const b=m.createBoard('perf2','Renderer contract');b.paper.kind='plain';b.layers=Array.from({length:3},(_,i)=>({id:'l'+i,name:'Layer '+i,visible:true,locked:false,opacity:.6+i*.1,blend:'normal',strokes:[{id:'s'+i,brush:'ink',preset:'ink-fineliner',color:['#ec583c','#456789','#53aa88'][i],size:10,opacity:.7,points:[{x:45,y:55+i*15,pressure:0},{x:190,y:100,pressure:1}]}]}));
 const data=new Uint8ClampedArray(16*16*4);for(let i=0;i<data.length;i+=4)data.set([70,110,160,160],i);b.version=4;b.layers[1].strokes.push(rs.rasterStroke(data,16,16,110,80,'raster'));b.activeLayer='l2';
 const live={id:'live',brush:'ink',preset:'ink-fineliner',color:'#193256',size:6,opacity:.8,points:[{x:35,y:90,pressure:.1},{x:160,y:85,pressure:.9}]},view={x:0,y:0,scale:1};
 const check=(v,msg)=>{if(!v)throw Error(msg);};
 function equal(){const x=a.getContext('2d').getImageData(0,0,a.width,a.height).data,y=z.getContext('2d').getImageData(0,0,z.width,z.height).data;check(x.length===y.length&&x.every((v,i)=>v===y[i]),'boundary changed pixels');}
 window.boundary={m,f,raw,b,live,view,a,z,r,direct,equal,check};
});}
(async()=>{browser=await chromium.launch({headless:true});
for(const dpr of [1,2])await run('PERF2B01-pixels-dpr'+dpr,async p=>{await setup(p);return p.evaluate(()=>{const {m,b,live,view,r,direct,equal,check}=boundary;let cases=0;for(const blend of m.blends)for(const active of ['l0','l2']){b.activeLayer=active;b.layers[2].blend=blend;b.revision++;for(const stroke of [null,live]){const before=JSON.stringify(b);r.render(b,view,stroke);direct.render(b,view,stroke);equal();check(JSON.stringify(b)===before,'document mutated');check(r.surfaces.length===5,'surface count');check(r.getDiagnostics().lastFrame.backingBytes<=80*1024*1024,'budget');cases++;}}return{cases,dpr:devicePixelRatio,comparison:'exact facade versus extracted accepted Canvas2D backend'};});},dpr);
await run('PERF2B02-helpers-invalidate-and-recover',async p=>{await setup(p);return p.evaluate(()=>{const {b,live,view,r,direct,equal,check}=boundary;const before=JSON.stringify(b),methods=[];r.render(b,view,live);check(r.render(b,view,live).mode==='retained-hit','warm cache');
 for(const [name,args]of [['preview',[live]],['thumbnail',[b.layers[0]]],['magnify',[{x:70,y:70}]],['snapshotLayer',[b.layers[0],10,{x:70,y:70}]]]){const old=r.getDiagnostics();r[name](...args);const next=r.getDiagnostics();check(next.epoch===old.epoch+1&&next.reason===name&&next.lastFrame===null,'helper invalidation '+name);check(r.render(b,view,live).mode==='retained-miss','helper must invalidate '+name);direct.renderReference(b,view,live);equal();methods.push(name);}
 let rejected=false;try{r.snapshotLayer(b.layers[0],2000,{x:70,y:70});}catch(e){rejected=/Smudge layer exceeds/.test(e.message);}check(rejected,'oversize snapshot rejected');check(r.getDiagnostics().reason==='snapshotLayer-failed'&&r.getDiagnostics().lastFrame===null,'failure invalidation');check(r.render(b,view,live).mode==='retained-miss','recover after failure');direct.renderReference(b,view,live);equal();check(JSON.stringify(b)===before,'helpers mutated board');r.invalidate('opacity-preview');check(r.getDiagnostics().reason==='opacity-preview','caller reason');return{methods,failureRecovery:true,documentUnchanged:true};});});
await run('PERF2B03-revision-view-reference-and-diagnostics',async p=>{await setup(p);return p.evaluate(()=>{const {b,live,r,direct,equal,check}=boundary;const old=r.getDiagnostics();check(old.lastFrame===null,'initial diagnostics');const v={x:0,y:0,scale:1};r.render(b,v,live);const snapshot=r.getDiagnostics();check(Object.isFrozen(snapshot)&&Object.isFrozen(snapshot.lastFrame.region)&&Object.isFrozen(snapshot.lastFrame.visibleLayerIds),'immutable diagnostics');for(const change of [()=>{b.revision++;},()=>{v.scale=1.3;v.x=12;},()=>{b.activeLayer='l0';}]){change();const metrics=r.render(b,v,live);check(metrics.mode!=='retained-hit','changed inputs invalidate cache');direct.renderReference(b,v,live);equal();}check(snapshot.lastFrame.activeLayer==='l2'&&snapshot.lastFrame.view.scale===1,'snapshot alias');check(r.getDiagnostics().lastFrame.replayReason==='visible-upper-layers','upper-layer policy');r.renderReference(b,v,live);direct.renderReference(b,v,live);equal();check(r.getDiagnostics().lastFrame.mode==='reference','reference path');for(const backend of ['webgpu','rust']){let rejected=false;try{boundary.f.createRenderer(null,{backend});}catch{rejected=true;}check(rejected,'unsupported backend');}return{reference:true,immutableSnapshots:true,unsupportedBackendsRejected:true};});});
await run('PERF2B04-offline-module-graph',async(p,c)=>{await p.evaluate(()=>navigator.serviceWorker.ready);if(!await p.evaluate(()=>!!navigator.serviceWorker.controller)){await p.reload();await ready(p);}const cached=await p.evaluate(async()=>{const keys=await caches.keys(),key=keys.find(k=>k.endsWith('v3-20261011-perf3a-1')),cache=await caches.open(key);return Promise.all(['render.js','canvas2d-renderer.js','render-contract.js'].map(async name=>({name,cached:!!await cache.match(new URL(name,location.href))})));});assert(cached.every(x=>x.cached));await c.setOffline(true);await p.reload();await ready(p);const backend=await p.evaluate(async()=>{const {createRenderer}=await import('./render.js');return createRenderer(document.createElement('canvas')).getDiagnostics().backend;});assert.equal(backend,'canvas2d');return{cached,offlineReload:true,backend};});
fs.writeFileSync(path.join(out,'render-boundary-results.json'),JSON.stringify({browser:browser.version(),physicalTablet:'NOT_VERIFIED',results},null,2));await browser.close();console.log(JSON.stringify(results));process.exitCode=results.some(x=>x.status!=='PASS')?1:0;
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
