const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=path.join(__dirname,'evidence'),results=[];fs.mkdirSync(out,{recursive:true});
const base=process.env.UNRULY_TEST_URL||'http://127.0.0.1:4173/unruly/';
async function ready(p){await p.waitForFunction(()=>/Saved on this device/.test(document.querySelector('#save')?.textContent));}
async function board(p){return p.evaluate(()=>new Promise((ok,no)=>{const q=indexedDB.open('unruly-workspace-v3',1);q.onerror=()=>no(q.error);q.onsuccess=()=>{const db=q.result,t=db.transaction(['boards','meta']),a=t.objectStore('boards').getAll(),m=t.objectStore('meta').get('lastBoard');t.oncomplete=()=>{db.close();ok(a.result.find(r=>r.id===m.result).current);};};}));}
async function set(p,n){await p.locator('#size-number').fill(String(n));await p.locator('#size-number').dispatchEvent('change');}
async function draw(p,y){const b=await p.locator('#canvas').boundingBox();await p.mouse.move(b.x+90,b.y+y);await p.mouse.down();await p.mouse.move(b.x+220,b.y+y,{steps:6});await p.mouse.up();await p.waitForTimeout(650);}
async function choose(p,f,name){await p.locator('#pen').click();await p.locator('#brush-categories').getByRole('button',{name:f,exact:true}).click();await p.getByRole('button',{name,exact:true}).click();await p.keyboard.press('Escape');}
(async()=>{const browser=await chromium.launch({headless:true});try{for(const viewport of [{width:1024,height:768},{width:768,height:1024}]){const context=await browser.newContext({viewport}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await ready(p);
for(const [family,name,max] of [['Pen','Fineliner',40],['Pencil','HB',40],['Marker','Round',40],['Airbrush','Soft',160]]){await choose(p,family,name);assert.equal(await p.locator('#size').getAttribute('min'),'0');assert.equal(await p.locator('#size-number').getAttribute('max'),'100');for(const n of [0,40,100]){await set(p,n);assert.equal(await p.locator('#size').inputValue(),String(n));await draw(p,100+n);const s=(await board(p)).layers.flatMap(l=>l.strokes).at(-1);const expected=Math.round((1+(max-1)*(n/100)**2)*100)/100;assert.equal(s.size,expected,'stored document width for '+family+' '+n+'%');assert(s.points.every(q=>q.pressure===null),'mouse input never fabricates pressure');}}
await set(p,90);await draw(p,350);const before=await board(p),canvas=await p.locator('#canvas').evaluate(e=>e.toDataURL());await p.reload();await ready(p);assert.deepEqual((await board(p)).layers,before.layers,'reload preserves every stored width and pressure');await p.waitForTimeout(100);assert.equal(await p.locator('#canvas').evaluate(e=>e.toDataURL()),canvas,'reload preserves exact rendered pixels');await choose(p,'Airbrush','Soft');assert.equal(await p.locator('#size-number').inputValue(),'90','remembered preset size restored when reselected after reload');await choose(p,'Pen','Fineliner');assert.equal(await p.locator('#size-number').inputValue(),'100','preset remembers previous percent width');assert.deepEqual((await board(p)).layers,before.layers,'switching brush never rewrites saved strokes');assert.deepEqual(errors,[]);results.push({viewport,status:'PASS',checks:'family endpoints,40-percent mapping, mouse null pressure, preset memory, persistence, exact replay'});await p.screenshot({path:path.join(out,'size-percent-'+viewport.width+'.png')});await context.close();}
fs.writeFileSync(path.join(out,'size-percent-browser-results.json'),JSON.stringify({results,physicalPen:'NOT_VERIFIED'},null,2));console.log(JSON.stringify(results));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
