const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.UNRULY_TEST_URL||'http://127.0.0.1:4173/unruly/',out=__dirname+'/evidence';fs.mkdirSync(out,{recursive:true});
const ready=p=>p.waitForFunction(()=>/Saved on this device|Imported/.test(document.querySelector('#save').textContent));
const settle=async p=>{await p.waitForTimeout(700);};
async function board(p){return p.evaluate(()=>new Promise(ok=>{const q=indexedDB.open('unruly-workspace-v3');q.onsuccess=()=>{const db=q.result,t=db.transaction(['boards','meta']),a=t.objectStore('boards').getAll(),m=t.objectStore('meta').get('lastBoard');t.oncomplete=()=>{db.close();ok(a.result.find(r=>r.id===m.result).current);};};}));}
const pixels=async p=>{await p.waitForTimeout(100);return p.locator('#canvas').evaluate(e=>e.toDataURL());};
async function seed(p){const fixture=await p.evaluate(async()=>{const m=await import('./model.js'),b=m.createBoard('smudge-source','Smudge QA');const stroke=(id,x,color)=>({id,brush:'ink',preset:'ink-fineliner',color,size:40,opacity:1,points:[{x,y:200,pressure:null},{x,y:235,pressure:null}]});b.layers[0].strokes=[stroke('red',220,'#cc3311'),stroke('blue',260,'#2244cc')];b.layers.push({id:'other',name:'Other layer',visible:true,locked:false,opacity:.5,blend:'normal',strokes:[{...stroke('green',400,'#22aa44'),size:20}]});return b;});await p.locator('#import-file').setInputFiles({name:'source.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await settle(p);return board(p);}
async function range(p,id,value){await p.locator('#'+id).evaluate((e,v)=>{e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));},value);}
async function open(p){await p.locator('#smudge').click();if(!await p.locator('#smudge-popover').isVisible())await p.locator('#smudge').click();}
async function drag(p,y=215){const r=await p.locator('#canvas').boundingBox();await p.mouse.move(r.x+220,r.y+y);await p.mouse.down();await p.mouse.move(r.x+310,r.y+y,{steps:12});await p.mouse.up();await settle(p);}
(async()=>{const b=await chromium.launch(),results=[];try{for(const viewport of [{width:1024,height:768},{width:768,height:1024}]){const c=await b.newContext({viewport,hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await ready(p);const original=await seed(p),before=await pixels(p);
 await open(p);assert.equal(await p.locator('#smudge-brush option').count(),20,'same catalog as paint');await p.locator('#smudge-brush').selectOption('ink-fineliner');await p.locator('#smudge-round').click();await range(p,'smudge-size',55);await range(p,'smudge-strength',100);await p.keyboard.press('Escape');await drag(p);const first=await board(p),after=await pixels(p);assert.equal(first.version,4);assert.equal(first.layers[0].strokes[0].brush,'raster');assert.notEqual(after,before,'smudge changes actual pigment pixels');assert.deepEqual(first.layers[1],original.layers[1],'other layer remains byte-identical');assert.equal(first.layers[0].opacity,original.layers[0].opacity);assert.equal(first.layers[0].blend,original.layers[0].blend);
 await p.locator('#undo').click();await settle(p);assert.deepEqual((await board(p)).layers,original.layers);assert.equal(await pixels(p),before,'undo restores original vector pixels exactly');await p.locator('#redo').click();await settle(p);assert.equal(await pixels(p),after,'redo exact raster pixels');await p.reload();await ready(p);assert.equal(await pixels(p),after,'reload exact pixels');assert.deepEqual((await board(p)).layers,first.layers);
 await p.locator('#import-file').setInputFiles({name:'smudged.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(first))});await settle(p);assert.equal(await pixels(p),after,'JSON roundtrip exact raster pixels');const prior=await board(p);
 await open(p);assert.equal(await p.locator('#smudge-strength').inputValue(),'100');assert.equal(await p.locator('#smudge-brush').inputValue(),'ink-fineliner');await range(p,'smudge-strength',0);await p.keyboard.press('Escape');await drag(p);assert.deepEqual(await board(p),prior,'zero strength makes no board/history change');await open(p);await range(p,'smudge-strength',100);await p.keyboard.press('Escape');const r=await p.locator('#canvas').boundingBox();await p.mouse.move(r.x+250,r.y+215);await p.mouse.down();await p.mouse.move(r.x+300,r.y+245,{steps:8});await p.keyboard.press('Escape');await p.mouse.up();await settle(p);assert.deepEqual(await board(p),prior,'Escape discards raster preview');assert.equal(await pixels(p),after,'cancel restores exact pixels');
 // Finger paint uses the same document-space smudge path; a second finger cancels it.
 const cdp=await c.newCDPSession(p);const touch=(id,x,y)=>({id,x:r.x+x,y:r.y+y,radiusX:3,radiusY:3,force:.8});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,245,215)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,275,235)]});await p.waitForTimeout(100);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,275,235),touch(2,340,280)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,310,250),touch(2,385,300)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle(p);assert.deepEqual(await board(p),prior,'second-finger navigation never commits tentative smudge');await p.locator('#reset-view').click();
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,250,215)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,310,215)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle(p);const finger=await board(p);assert.ok(finger.revision>prior.revision,'single finger commits actual smudge');await cdp.detach();
 // Hold transfers paint settings; tool controls never change existing raster history.
 await p.locator('#pen').click();await p.locator('#brush-categories').getByRole('button',{name:'Pencil',exact:true}).click();await p.locator('#brush-presets').getByRole('button',{name:'HB',exact:true}).click();await p.keyboard.press('Escape');await p.locator('#smudge').hover();await p.mouse.down();await p.waitForTimeout(600);await p.mouse.up();assert.equal(await p.locator('#smudge-brush').inputValue(),'pencil-hb');assert.equal(await p.locator('#smudge').getAttribute('aria-pressed'),'true');assert.deepEqual((await board(p)).layers,finger.layers);await p.locator('#smudge-reset').click();assert.equal(await p.locator('#smudge-brush').inputValue(),'airbrush-soft');await p.screenshot({path:out+'/b03-'+viewport.width+'.png',fullPage:true});
 await p.evaluate(()=>navigator.serviceWorker.ready);if(!await p.evaluate(()=>!!navigator.serviceWorker.controller)){await p.reload();await ready(p);}await c.setOffline(true);await p.reload();await ready(p);assert.deepEqual(await p.evaluate(async()=>{const files=['./raster.js','./smudge.js','./smudge-ui.js'];return Promise.all(files.map(async f=>(await fetch(f)).ok));}),[true,true,true]);assert.deepEqual((await board(p)).layers,finger.layers);assert.deepEqual(errors,[]);results.push({viewport,status:'PASS',physicalDevice:'NOT_VERIFIED'});await c.close();}
 fs.writeFileSync(out+'/smudge-browser-results.json',JSON.stringify(results));console.log(results);
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
