// Independent U1 browser oracle; real Canvas2D/IDB, isolated QA origin.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.UNRULY_TEST_URL||'http://127.0.0.1:4173/unruly/',out=path.join(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});let browser;const results=[];
async function ready(p){await p.waitForFunction(()=>/Saved on this device|Copied \d+ old boards|Recovery warning|Some old boards could not be copied|Old boards need recovery|Storage\/recovery error/.test(document.querySelector('#save')?.textContent),null,{timeout:10000});}
async function saved(p){await p.waitForTimeout(550);await p.waitForFunction(()=>/Saved on this device/.test(document.querySelector('#save')?.textContent),null,{timeout:10000});}
async function run(id,fn,viewport={width:1440,height:950},seed){const ctx=await browser.newContext({viewport,acceptDownloads:true});await ctx.addInitScript(()=>{window.__u1CanvasCreates=0;window.__u1ThumbEncodes=0;const create=document.createElement;document.createElement=function(tag,...args){if(String(tag).toLowerCase()==='canvas')window.__u1CanvasCreates++;return create.call(this,tag,...args);};const encode=HTMLCanvasElement.prototype.toDataURL;HTMLCanvasElement.prototype.toDataURL=function(...args){window.__u1ThumbEncodes++;return encode.apply(this,args);};});await ctx.tracing.start({screenshots:true,snapshots:true});const p=await ctx.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)external.push(r.url());});try{if(seed){await p.goto(new URL('/__qa/bootstrap',base).href);await seed(p,ctx);}await p.goto(base);await ready(p);const evidence=await fn(p,ctx);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await p.screenshot({path:path.join(out,id+'.png'),fullPage:true});results.push({id,status:'PASS',evidence});}catch(e){results.push({id,status:'FAIL',message:e.stack,errors,external});await p.screenshot({path:path.join(out,id+'-failure.png'),fullPage:true}).catch(()=>{});await ctx.tracing.stop({path:path.join(out,id+'-trace.zip')});console.error(id,e.message);}finally{await ctx.tracing.stop().catch(()=>{});await ctx.close();}}
async function seedLegacy(p,{collision=false,damaged=false,sameID=false,damagedAll=false}={}){await p.evaluate(async({collision,damaged,sameID,damagedAll})=>{
 const open=(name)=>new Promise((ok,no)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>{r.result.createObjectStore('boards',{keyPath:'id'});r.result.createObjectStore('meta');};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});
 const v2={version:2,id:'qa-old',title:'V2 <img src=x onerror=window.__xss=1>',revision:7,activeLayer:'qa-l',layers:[{id:'qa-l',name:'Old',visible:true,locked:false,opacity:.4,strokes:[{id:'qa-s',brush:'ink',color:'#4080c0',size:12,opacity:.6,points:[{x:20,y:30,pressure:null},{x:50,y:60,pressure:.4}]}]}],paper:{kind:'plain',color:'#faf8f3',spacing:24,seed:173}};
 const v1={version:1,id:sameID?'qa-old':'qa-foundation',title:'Foundation',revision:2,strokes:[{id:'qa-fs',color:'#c08040',size:12,points:[{x:10,y:20,pressure:0},{x:30,y:40,pressure:1}]}]};
 const values=[['unruly-workspace',{id:v2.id,dbRevision:3,current:damaged||damagedAll?{bad:true}:v2,previous:damagedAll?{bad:true}:v2}],['unruly-foundation',{id:v1.id,dbRevision:4,current:v1,previous:null}]];
 const snapshots={};for(const [name,record] of values){const db=await open(name);await new Promise((ok,no)=>{const t=db.transaction(['boards','meta'],'readwrite');t.objectStore('boards').put(record);t.objectStore('meta').put(record.id,'lastBoard');t.oncomplete=ok;t.onabort=()=>no(t.error);});snapshots[name]=JSON.stringify([record,record.id]);db.close();}sessionStorage.setItem('qa-u1-sources',JSON.stringify(snapshots));if(collision){const q=indexedDB.open('unruly-workspace-v3',1);const target=await new Promise((ok,no)=>{q.onupgradeneeded=()=>{q.result.createObjectStore('boards',{keyPath:'id'});q.result.createObjectStore('meta');q.result.createObjectStore('migrations',{keyPath:'key'});};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error);});const b=structuredClone(v2);b.version=3;b.title='Existing v3 target';b.layers[0].blend='normal';await new Promise((ok,no)=>{const tx=target.transaction(['boards','meta'],'readwrite');tx.objectStore('boards').put({id:b.id,dbRevision:1,current:b,previous:null});tx.objectStore('meta').put(b.id,'lastBoard');tx.oncomplete=ok;tx.onabort=()=>no(tx.error);});target.close();}
 },{collision,damaged,sameID,damagedAll});}
async function storageProbe(p){return p.evaluate(async()=>{const {openStore}=await import('./storage.js');const s=await openStore();const all=await s.list(),maps=await new Promise((ok,no)=>{const q=s.db.transaction('migrations').objectStore('migrations').getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error);});const selected=await s.last(),names=(await indexedDB.databases()).map(d=>d.name);s.close();return {all,maps,selected,names};});}
async function unchangedSources(p){assert.equal(await p.evaluate(async()=>{const before=JSON.parse(sessionStorage.getItem('qa-u1-sources'));for(const name of Object.keys(before)){const db=await new Promise(ok=>{const r=indexedDB.open(name);r.onsuccess=()=>ok(r.result);});const record=await new Promise(ok=>{const r=db.transaction('boards').objectStore('boards').getAll();r.onsuccess=()=>ok(r.result[0]);});const last=await new Promise(ok=>{const r=db.transaction('meta').objectStore('meta').get('lastBoard');r.onsuccess=()=>ok(r.result);});db.close();if(JSON.stringify([record,last])!==before[name])return false;}return true;}),true,'legacy boards/meta byte-identical');}
(async()=>{browser=await chromium.launch({headless:true});
for(const [name,viewport]of Object.entries({desktop:{width:1440,height:950},tablet:{width:1024,height:768},phone:{width:390,height:844}}))await run('UB01-'+name,async p=>{
 const before=await p.locator('#canvas').boundingBox();for(const selector of ['#layers-toggle','#modifiers-toggle']){await p.locator(selector).click();assert.deepEqual(await p.locator('#canvas').boundingBox(),before,'opening overlay never moves stage');await p.locator(selector).click();assert.deepEqual(await p.locator('#canvas').boundingBox(),before);}
 await p.locator('#layers-toggle').click();await p.locator('#add-layer').click();await saved(p);const q=await storageProbe(p);const current=q.all.find(r=>r.id===q.selected).current;const rows=p.locator('#layer-list [data-layer-id]');assert.equal(await rows.count(),2);assert.deepEqual(await rows.evaluateAll(rs=>rs.map(r=>r.dataset.layerId)),current.layers.map(l=>l.id).reverse());for(const row of await rows.all())assert((await row.boundingBox()).height>=56,'56px layer row');for(const button of await p.locator('header button:visible,#tools button:visible,#inspector button:visible').all()){const box=await button.boundingBox();assert(box.width>=44&&box.height>=44,'44px action target '+await button.getAttribute('aria-label'));}assert.equal(await p.getByRole('button',{name:/smudge|transform/i}).count(),0,'no enabled undelivered tools');const widths=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,inner:innerWidth}));assert(widths.scroll<=widths.inner,'no horizontal viewport overflow');return {viewport,canvas:before};
},viewport);
await run('UB02-captured-pen-rejects-controls-dismiss-consumed',async p=>{
 const probe=async()=>{const q=await storageProbe(p);return q.all.find(r=>r.id===q.selected).current;};const original=await probe();
 await p.locator('#layers-toggle').click();const box=await p.locator('#canvas').boundingBox(),cdp=await p.context().newCDPSession(p);
 const send=(type,x,y,buttons)=>cdp.send('Input.dispatchMouseEvent',{type,x:box.x+x,y:box.y+y,button:'left',buttons,pointerType:'pen',force:buttons?.5:0,clickCount:1});
 // First pen tap dismisses the layer overlay; no artwork may be committed.
 await send('mousePressed',box.width*.5,box.height*.5,1);await send('mouseReleased',box.width*.5,box.height*.5,0);await p.waitForTimeout(600);assert.deepEqual(await probe(),original,'outside-dismiss tap consumed');
 await send('mousePressed',box.width*.5,box.height*.5,1);const expanded=await p.locator('#layers-toggle').getAttribute('aria-expanded');await p.locator('#layers-toggle').evaluate(e=>e.click());assert.equal(await p.locator('#layers-toggle').getAttribute('aria-expanded'),expanded,'live pen rejects popover toggle');await p.locator('#add-layer').evaluate(e=>e.click());await p.locator('#layer-opacity').evaluate(e=>{e.value='20';e.dispatchEvent(new Event('change',{bubbles:true}));});await send('mouseMoved',box.width*.5+30,box.height*.5+20,1);await send('mouseReleased',box.width*.5+40,box.height*.5+30,0);await saved(p);await p.waitForTimeout(600);const after=await probe();assert.equal(after.layers.length,1);assert.equal(after.layers[0].opacity,1);assert.equal(after.layers[0].strokes.length,1);assert.equal(after.revision,original.revision+1);await cdp.detach();
});
await run('UB08-thumbnails-scratch-bound-and-no-penmove',async p=>{
 const count=()=>p.evaluate(()=>({canvases:window.__u1CanvasCreates+document.querySelectorAll('canvas').length,encodes:window.__u1ThumbEncodes}));assert.equal((await count()).canvases,5);
 const result=await p.evaluate(async()=>{const m=await import('./model.js'),{openStore}=await import('./storage.js'),s=await openStore(),b=m.createBoard('qa-thumbs','32 layer thumbnail stress');b.layers=Array.from({length:32},(_,i)=>({id:'qa-tl'+i,name:'Layer '+i,visible:true,locked:false,opacity:1,blend:'normal',strokes:[{id:'qa-ts'+i,brush:'ink',color:'#4080c0',size:12,opacity:1,points:[{x:40,y:50,pressure:null},{x:80,y:90,pressure:.4}]}]}));b.activeLayer=b.layers.at(-1).id;await s.save(b,0);await s.select(b.id);s.close();return b.id;});await p.reload();await saved(p);await p.locator('#layers-toggle').click();const imgs=p.locator('#layer-list img');assert.equal(await imgs.count(),32);const dims=await imgs.evaluateAll(xs=>xs.map(x=>({w:x.naturalWidth,h:x.naturalHeight})));assert(dims.every(d=>d.w===80&&d.h===48));assert(dims.reduce((n,d)=>n+d.w*d.h*4,0)<=512*1024);assert.equal((await count()).canvases,5);
 await p.locator('#layers-toggle').click();const before=await count(),box=await p.locator('#canvas').boundingBox(),c=await p.context().newCDPSession(p);const send=(type,x,y,buttons)=>c.send('Input.dispatchMouseEvent',{type,x:box.x+x,y:box.y+y,button:'left',buttons,pointerType:'pen',force:buttons?.6:0,clickCount:1});await send('mousePressed',box.width*.5,box.height*.5,1);await p.waitForTimeout(50);const start=await count();for(let i=1;i<8;i++)await send('mouseMoved',box.width*.5+i*3,box.height*.5+i*2,1);await p.waitForTimeout(80);assert.equal((await count()).encodes,start.encodes,'penmove must not encode thumbnails');assert.equal((await count()).canvases,5);await send('mouseReleased',box.width*.5+24,box.height*.5+16,0);await c.detach();await saved(p);return {board:result,dimensions:dims,before,start};
});
await run('UB10-keyboard-grip-opacity-single-history',async p=>{
 const current=async()=>{const q=await storageProbe(p);return q.all.find(r=>r.id===q.selected).current;};await p.locator('#layers-toggle').click();await p.locator('#add-layer').click();await saved(p);await p.locator('#add-layer').click();await saved(p);let b=await current(),ids=b.layers.map(l=>l.id),mid=ids[1];await p.locator('[data-layer-id="'+mid+'"] .layer-select').click();await saved(p);b=await current();const baseRevision=b.revision;await p.locator('[data-layer-id="'+mid+'"] .layer-grip').focus();await p.keyboard.press('ArrowUp');await saved(p);let after=await current();assert.equal(after.activeLayer,mid);assert.deepEqual(after.layers.map(l=>l.id),[ids[0],ids[2],mid]);assert.equal(after.revision,baseRevision+1);await p.locator('#undo').click();await saved(p);assert.deepEqual((await current()).layers.map(l=>l.id),ids);
 const beforeOpacity=await current();await p.locator('#layer-opacity').evaluate(e=>{for(const v of ['75','60','42']){e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));}e.dispatchEvent(new Event('change',{bubbles:true}));});await saved(p);after=await current();assert.equal(after.layers.find(l=>l.id===mid).opacity,.42);assert.equal(after.revision,beforeOpacity.revision+1);await p.locator('#undo').click();await saved(p);assert.equal((await current()).layers.find(l=>l.id===mid).opacity,1);
 const beforeDrag=await current(),grip=await p.locator('[data-layer-id="'+mid+'"] .layer-grip').boundingBox(),bottom=await p.locator('[data-layer-id="'+ids[0]+'"]').boundingBox();await p.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await p.mouse.down();await p.mouse.move(grip.x+grip.width/2,bottom.y+bottom.height-2,{steps:8});await p.mouse.up();await saved(p);after=await current();assert.equal(after.activeLayer,mid);assert.deepEqual(after.layers.map(l=>l.id),[mid,ids[0],ids[2]]);assert.equal(after.revision,beforeDrag.revision+1);await p.locator('#undo').click();await saved(p);assert.deepEqual((await current()).layers.map(l=>l.id),ids);
});
await run('UB11-malformed-import-retains-artwork',async p=>{const q=await storageProbe(p),original=q.all.find(r=>r.id===q.selected).current;for(const kind of ['blend','preset']){const bad=structuredClone(original);if(kind==='blend')bad.layers[0].blend='shade';else bad.layers[0].strokes=[{id:'malicious-preset',brush:'ink',presetId:'hb',color:'#4080c0',size:12,opacity:1,points:[{x:30,y:40,pressure:1}]}];await p.locator('#import-file').setInputFiles({name:kind+'.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await p.waitForFunction(()=>document.querySelector('#save').dataset.error==='true');const after=await storageProbe(p);assert.equal(after.all.length,1);assert.deepEqual(after.all[0].current,original);assert.equal(after.selected,original.id);} });
await run('UB12-punctuated-layer-ID-keyboard-safe-and-text-scale',async p=>{
 const id='qa-quote"][data-x="legacy';await p.evaluate(async id=>{const m=await import('./model.js'),{openStore}=await import('./storage.js'),s=await openStore(),b=m.createBoard('qa-hostile-id','Quoted ID fixture');b.layers.push({id,name:'Quoted legacy ID',visible:true,locked:false,opacity:1,blend:'normal',strokes:[]});b.activeLayer=id;await s.save(b,0);await s.select(b.id);s.close();},id);await p.reload();await saved(p);await p.locator('#layers-toggle').click();const row=p.locator('#layer-list [data-layer-id]').filter({has:p.locator('.layer-name',{hasText:'Quoted legacy ID'})});await row.locator('.layer-grip').focus();await p.keyboard.press('ArrowDown');await saved(p);const q=await storageProbe(p),b=q.all.find(r=>r.id===q.selected).current;assert.equal(b.layers[0].id,id);assert.equal(b.activeLayer,id);assert.equal(await p.evaluate(()=>document.activeElement?.closest('[data-layer-id]')?.dataset.layerId),id,'focus preserves punctuated ID');await p.evaluate(()=>{document.documentElement.style.fontSize='200%';for(const name of document.querySelectorAll('.layer-name'))name.style.fontSize='24px';});const boxes=await p.locator('#layer-list [data-layer-id]').evaluateAll(rs=>rs.map(r=>({h:r.getBoundingClientRect().height,scroll:r.scrollHeight})));assert(boxes.every(r=>r.h>=56&&r.h>=r.scroll),'rows grow with doubled text without clipping');return {id,boxes};
});
await run('UB15-locked-layer-retains-usable-copy-with-write-guards',async p=>{
 await p.evaluate(async()=>{const m=await import('./model.js'),{openStore}=await import('./storage.js'),s=await openStore(),b=m.createBoard('qa-lock-copy','Locked copy workflow');b.layers[0].strokes=[{id:'qa-copy-stroke',brush:'ink',color:'#4080c0',size:12,opacity:1,points:[{x:180,y:200,pressure:0},{x:280,y:200,pressure:1}]}];await s.save(b,0);await s.select(b.id);s.close();});await p.reload();await saved(p);await p.locator('#lasso').click();await p.keyboard.press('Escape');const box=await p.locator('#canvas').boundingBox(),c=await p.context().newCDPSession(p),points=[[150,170],[310,170],[310,230],[150,230],[150,170]];await c.send('Input.dispatchMouseEvent',{type:'mousePressed',x:box.x+points[0][0],y:box.y+points[0][1],button:'left',buttons:1,pointerType:'pen',force:.5,clickCount:1});for(const [x,y]of points.slice(1,-1))await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:box.x+x,y:box.y+y,button:'left',buttons:1,pointerType:'pen',force:.5});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:box.x+points.at(-1)[0],y:box.y+points.at(-1)[1],button:'left',buttons:0,pointerType:'pen',force:0,clickCount:1});await c.detach();await p.waitForFunction(()=>document.querySelector('#selection-count').textContent==='1 selected');await p.locator('#layers-toggle').click();await p.getByRole('button',{name:'Actions Layer 1',exact:true}).click();await p.getByRole('button',{name:'Lock Layer 1',exact:true}).click();await saved(p);assert.equal(await p.locator('#selection-count').textContent(),'1 selected','protective lock preserves existing selected IDs so Copy is usable');await p.locator('#lasso').click();assert(await p.locator('#copy-selection').isEnabled());for(const id of ['cut-selection','delete-selection','paste-selection'])assert(await p.locator('#'+id).isDisabled(),id);await p.locator('#copy-selection').click();await p.waitForFunction(()=>/Copied 1 strokes/.test(document.querySelector('#save').textContent));assert(await p.locator('#paste-selection').isDisabled());const q=await storageProbe(p),b=q.all.find(r=>r.id==='qa-lock-copy').current;assert.equal(b.layers[0].locked,true);assert.equal(b.layers[0].strokes.length,1);assert.equal(b.layers[0].strokes[0].id,'qa-copy-stroke');await p.locator('#layers-toggle').click();await p.getByRole('button',{name:'Actions Layer 1',exact:true}).click();assert(await p.getByRole('button',{name:'Unlock Layer 1',exact:true}).isEnabled());await p.getByRole('button',{name:'Unlock Layer 1',exact:true}).click();await saved(p);assert.equal(await p.locator('#selection-count').textContent(),'1 selected');
});
await run('UB03-independent-eight-mode-pixels-and-retained',async p=>p.evaluate(async()=>{
 const m=await import('./model.js'),r=await import('./render.js');const c=document.createElement('canvas');c.style.cssText='width:96px;height:96px;position:fixed;left:0;top:0;pointer-events:none;opacity:0';document.body.append(c);const renderer=r.createRenderer(c),view={x:0,y:0,scale:1};
 const rgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255),back=rgb('#4080c0'),front=rgb('#c08040');
 const f={normal:(b,s)=>s,multiply:(b,s)=>b*s,screen:(b,s)=>b+s-b*s,overlay:(b,s)=>b<=.5?2*b*s:1-2*(1-b)*(1-s),darken:Math.min,lighten:Math.max,difference:(b,s)=>Math.abs(b-s),exclusion:(b,s)=>b+s-2*b*s};
 const stroke=(id,color)=>({id,brush:'ink',color,size:40,opacity:1,points:[{x:48,y:48,pressure:null}]});const evidence=[];
 for(const mode of Object.keys(f)){const b=m.createBoard('pixel-'+mode);b.paper.color='#4080c0';b.layers[0].strokes=[];b.layers[0].opacity=.5;b.layers[0].blend=mode;b.layers[0].strokes=[stroke('qa-dot','#c08040'),stroke('qa-overlap','#c08040')];renderer.renderReference(b,view);const pixel=Array.from(c.getContext('2d').getImageData(Math.floor(c.width/2),Math.floor(c.height/2),1,1).data);const want=back.map((v,i)=>Math.round(255*(v*.5+f[mode](v,front[i])*.5)));for(let i=0;i<3;i++)if(Math.abs(pixel[i]-want[i])>2)throw Error(mode+' channel'+i+' '+pixel[i]+' expected '+want[i]+' layer alpha must apply once');if(pixel[3]!==255)throw Error('opaque result');
 const live=stroke('qa-live','#c08040');renderer.render(b,view,live);renderer.render(b,view,live);const retained=Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data);renderer.renderReference(b,view,live);const full=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let i=0;i<full.length;i++)if(full[i]!==retained[i])throw Error(mode+' retained mismatch byte '+i);if(renderer.surfaces.length!==5)throw Error('five surfaces');for(const surface of renderer.surfaces)if(surface.getContext('2d').globalCompositeOperation!=='source-over')throw Error(mode+' leaked composite state');evidence.push({mode,pixel,want});}return evidence;
}));
await run('UB04-v2-foundation-read-only-retry',async p=>{
 await unchangedSources(p);const first=await storageProbe(p);assert(first.names.includes('unruly-workspace-v3'));assert(!first.names.includes('unruly-workspace-v2'),'no intermediate v2 DB');assert.equal(first.all.length,2);assert.equal(first.maps.length,2);for(const r of first.all){assert.equal(r.current.version,3);assert(r.current.layers.every(l=>l.blend==='normal'));}const selected=first.all.find(r=>r.id===first.selected);assert.equal(selected.current.title,'V2 <img src=x onerror=window.__xss=1>');assert.equal(await p.evaluate(()=>window.__xss),undefined);
 await p.evaluate(async id=>{const {openStore}=await import('./storage.js');const s=await openStore(),q=await s.load(id);q.board.title='Edited migrated target';q.board.revision++;await s.save(q.board,q.dbRevision);await s.migrateLegacy();await s.migrateLegacy();s.close();},selected.id);const after=await storageProbe(p);assert.equal(after.all.length,2);assert.equal(after.maps.length,2);assert.equal(after.all.find(r=>r.id===selected.id).current.title,'Edited migrated target');await unchangedSources(p);return {names:first.names,mappings:first.maps};
},{width:1440,height:950},p=>seedLegacy(p));
await run('UB05-source-ID-collision-durable-mapping',async p=>{const q=await storageProbe(p);assert.equal(q.all.length,3);assert.equal(new Set(q.all.map(r=>r.id)).size,3);assert.equal(q.maps.length,2);assert.equal(new Set(q.all.map(r=>r.current.title)).size,3);assert.equal(q.all.find(r=>r.id==='qa-old').current.title,'Existing v3 target');assert.equal(q.selected,'qa-old');await unchangedSources(p);await p.reload();await ready(p);assert.deepEqual((await storageProbe(p)).maps,q.maps);await unchangedSources(p);return q.maps;},{width:1440,height:950},p=>seedLegacy(p,{collision:true}));
await run('UB06-damaged-current-previous-fallback-warning',async p=>{const q=await storageProbe(p);assert.equal(q.all.length,2);assert(q.all.some(r=>r.current.title.startsWith('V2')));assert(/recover|damag|previous|warning/i.test(await p.locator('#save').textContent()),'fallback warning explicit');await unchangedSources(p);},{width:1440,height:950},p=>seedLegacy(p,{damaged:true}));
await run('UB13-stable-source-dedup-prefer-valid-v2',async p=>{const q=await storageProbe(p);assert.equal(q.all.length,1,'same stable source ID copied only once');assert.equal(q.maps.length,1);assert.equal(q.all[0].current.title,'V2 <img src=x onerror=window.__xss=1>');assert.equal(q.selected,q.all[0].id);await unchangedSources(p);await p.reload();await ready(p);assert.equal((await storageProbe(p)).all.length,1);},{width:1440,height:950},p=>seedLegacy(p,{sameID:true}));
await run('UB14-damaged-v2-foundation-fallback-explicit',async p=>{const q=await storageProbe(p);assert.equal(q.all.length,1);assert.equal(q.maps.length,2,'fallback aliases both source mappings atomically');assert(q.maps.every(m=>m.targetID===q.all[0].id));assert.equal(q.all[0].current.title,'Foundation');assert(/recover|warning|newer|older|v2/i.test(await p.locator('#save').textContent()));await unchangedSources(p);await p.reload();await ready(p);const after=await storageProbe(p);assert.deepEqual(after.maps,q.maps);assert.equal(after.all.length,1);await unchangedSources(p);},{width:1440,height:950},p=>seedLegacy(p,{sameID:true,damagedAll:true}));
await run('UB07-quota-atomic-mapping-resume',async p=>{
 const first=await storageProbe(p);assert.equal(first.all.length,first.maps.length,'target/map atomic under quota');assert(first.all.length<2);assert(/preserved|failed|could not|error/i.test(await p.locator('#save').textContent()),'partial migration explicit');await unchangedSources(p);
 await p.evaluate(async()=>{IDBObjectStore.prototype.put=window.__qaPut;const {openStore}=await import('./storage.js');const s=await openStore();await s.migrateLegacy();s.close();});const after=await storageProbe(p);assert.equal(after.all.length,2);assert.equal(after.maps.length,2);await unchangedSources(p);return {initial:first.all.length,after:after.all.length};
},{width:1440,height:950},async(p,ctx)=>{await seedLegacy(p);await ctx.addInitScript(()=>{window.__qaPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...args){if(this.transaction.db.name==='unruly-workspace-v3'&&this.name==='migrations')throw new DOMException('QA migration map quota','QuotaExceededError');return window.__qaPut.call(this,value,...args);};});});
fs.writeFileSync(path.join(out,'u1-browser-results.json'),JSON.stringify({browser:browser.version(),synthetic_input:true,physical_pen:'NOT_VERIFIED',results},null,2));await browser.close();console.log(JSON.stringify(results));process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
