// Independent requirement-derived U1 tests. No application internals duplicated.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const m=await import(new URL('../../prototypes/browser-workspace/model.js',import.meta.url).href);
const modes=['normal','multiply','screen','overlay','darken','lighten','difference','exclusion'];
const stroke=(id='qa-stroke')=>({id,brush:'ink',color:'#4080c0',size:12,opacity:.6,points:[{x:10,y:20,pressure:null},{x:30,y:40,pressure:0},{x:50,y:60,pressure:1}]});
const board=()=>{const b=m.createBoard('qa-u1','QA U1');b.layers[0].strokes=[stroke()];return b;};
const histories=()=>{let h=m.createHistory(board());h=m.layerCommand(h,'add');h=m.layerCommand(h,'add');return h;};
const expectAtomicReject=(h,fn)=>{const before=structuredClone(h);assert.throws(fn);assert.deepEqual(h,before);};
test('UM01 new schema v3 and exact bounded blends',()=>{const b=board();assert.equal(b.version,3);assert.equal(b.layers[0].blend,'normal');for(const blend of modes){const q=structuredClone(b);q.layers[0].blend=blend;assert.equal(m.validateBoard(q),q);}for(const blend of ['shade','source-over','NORMAL','',null,{},7]){const q=structuredClone(b);q.layers[0].blend=blend;assert.throws(()=>m.validateBoard(q));}});
test('UM02 unknown preset fields never silently render as legacy',()=>{for(const key of ['preset','presetId']){const b=board();b.layers[0].strokes[0][key]='hb';assert.throws(()=>m.validateBoard(b),key);assert.throws(()=>m.importDocument(JSON.stringify(b)),key);}});
test('UM03 real v2 import upgrades normal preserving pixels and remaps every identity',()=>{const b=board();b.version=2;for(const l of b.layers)delete l.blend;const before=structuredClone(b);const q=m.importDocument(JSON.stringify(b));assert.deepEqual(b,before);assert.equal(q.version,3);assert.equal(q.layers[0].blend,'normal');assert.notEqual(q.id,b.id);assert.notEqual(q.layers[0].id,b.layers[0].id);assert.notEqual(q.layers[0].strokes[0].id,b.layers[0].strokes[0].id);assert.equal(q.activeLayer,q.layers[0].id);assert.deepEqual(q.layers[0].strokes[0].points,b.layers[0].strokes[0].points);assert.equal(q.revision,0);const bad=structuredClone(b);bad.layers[0].strokes[0].presetId='hb';assert.throws(()=>m.importDocument(JSON.stringify(bad)));});
test('UM04 add inserts immediately above active middle, disk stays bottom-first',()=>{let h=histories();const ids=h.board.layers.map(l=>l.id);h=m.layerCommand(h,'select',ids[1]);const prior=h.past.length;h=m.layerCommand(h,'add');assert.deepEqual(h.board.layers.map(l=>l.id),[ids[0],ids[1],h.board.activeLayer,ids[2]]);assert.equal(h.past.length,prior+1);h=m.undo(h);assert.deepEqual(h.board.layers.map(l=>l.id),ids);assert.equal(h.board.activeLayer,ids[1]);});
test('UM05 duplicate locked layer unlocked new IDs preserved style pressure one undo',()=>{let h=m.createHistory(board());const id=h.board.activeLayer;h=m.layerCommand(h,'opacity',id,.42);h=m.layerCommand(h,'blend',id,'multiply');h=m.layerCommand(h,'locked',id,true);const original=structuredClone(h.board.layers[0]),prior=h.past.length;h=m.layerCommand(h,'duplicate',id);const q=h.board.layers[1];assert.notEqual(q.id,id);assert.equal(h.board.activeLayer,q.id);assert.equal(q.locked,false);assert.equal(q.opacity,.42);assert.equal(q.blend,'multiply');assert.notEqual(q.strokes[0].id,original.strokes[0].id);assert.deepEqual({...q.strokes[0],id:original.strokes[0].id},original.strokes[0]);assert.equal(h.past.length,prior+1);h=m.undo(h);assert.deepEqual(h.board.layers,[original]);});
test('UM06 protective lock rejects content properties/delete but permits metadata/stack',()=>{let h=histories();const id=h.board.activeLayer;h=m.layerCommand(h,'locked',id,true);for(const [action,value] of [['delete'],['opacity',.3],['blend','screen']])expectAtomicReject(h,()=>m.layerCommand(h,action,id,value));expectAtomicReject(h,()=>m.addStroke(h,stroke('new-stroke')));expectAtomicReject(h,()=>m.eraseGesture(h.board,'whole',[{a:{x:20,y:30},b:{x:40,y:50}}],10));for(const [action,value] of [['visible',false],['name','Locked <img>'],['down'],['up']])h=m.layerCommand(h,action,id,value);assert.equal(h.board.activeLayer,id);assert.equal(h.board.layers.find(l=>l.id===id).locked,true);});
test('UM07 last layer deletion rejected even unlocked',()=>{const h=m.createHistory(board());expectAtomicReject(h,()=>m.layerCommand(h,'delete',h.board.activeLayer));});
test('UM08 no-op boundary reorders/properties produce no history; valid reorder one undo',()=>{let h=histories(),id=h.board.activeLayer;assert.equal(m.layerCommand(h,'up',id),h);assert.equal(m.layerCommand(h,'opacity',id,1),h);assert.equal(m.layerCommand(h,'blend',id,'normal'),h);const before=h.board.layers.map(l=>l.id),prior=h.past.length;h=m.layerCommand(h,'reorder',id,0);assert.equal(h.board.activeLayer,id);assert.deepEqual(h.board.layers.map(l=>l.id),[id,...before.slice(0,-1)]);assert.equal(h.past.length,prior+1);assert.equal(m.layerCommand(h,'reorder',id,0),h);h=m.undo(h);assert.deepEqual(h.board.layers.map(l=>l.id),before);});
test('UM09 capacity rejection atomically preserves IDs input and history',()=>{const b=board();b.layers=Array.from({length:32},(_,i)=>({...structuredClone(b.layers[0]),id:'qa-layer-'+i,strokes:i===0?[stroke()]:[]}));b.activeLayer=b.layers[0].id;const h=m.createHistory(b);for(const action of ['add','duplicate'])expectAtomicReject(h,()=>m.layerCommand(h,action,h.board.activeLayer));const q=board();q.layers[0].strokes=Array.from({length:1001},(_,i)=>stroke('qa-s'+i));const hh=m.createHistory(q);expectAtomicReject(hh,()=>m.layerCommand(hh,'duplicate',hh.board.activeLayer));});
test('UM10 malformed reorder and locked layer import cannot poison history',()=>{const h=histories();for(const target of [-1,32,NaN,Infinity,.5,'0',null])expectAtomicReject(h,()=>m.layerCommand(h,'reorder',h.board.activeLayer,target));for(const opacity of [-.01,1.01,NaN,Infinity,'0'])expectAtomicReject(h,()=>m.layerCommand(h,'opacity',h.board.activeLayer,opacity));});
test('UM11 unsupported blend assignment rejects visibly and resets scratch state',async()=>{
 const contexts=[];const make=()=>{let mode='source-over';const ctx={globalAlpha:1,setTransform(){},clearRect(){},fillRect(){},drawImage(){},save(){},restore(){},beginPath(){},arc(){},fill(){},moveTo(){},lineTo(){},stroke(){},createRadialGradient(){return {addColorStop(){}}},get globalCompositeOperation(){return mode;},set globalCompositeOperation(value){if(value==='source-over')mode=value;}};contexts.push(ctx);return {width:1,height:1,getContext:()=>ctx,getBoundingClientRect:()=>({width:96,height:96}),toDataURL:()=>''};};
 const oldDocument=globalThis.document,oldWindow=globalThis.window;try{globalThis.document={createElement:make};globalThis.window={devicePixelRatio:1};const r=await import(new URL('../../prototypes/browser-workspace/render.js',import.meta.url).href+'?u1-unsupported-blend');const renderer=r.createRenderer(make()),b=board();b.layers[0].strokes=[];b.layers[0].blend='multiply';assert.throws(()=>renderer.renderReference(b),/blend|support/i);assert(contexts.every(c=>c.globalCompositeOperation==='source-over'&&c.globalAlpha===1));}finally{globalThis.document=oldDocument;globalThis.window=oldWindow;}
});
