const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),crypto=require('crypto');
const file=__dirname+'/unruly-preview.html', sha=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const results=[], errors=[], requests=[];
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
async function check(id,fn){try{await fn();results.push({id,status:'PASS'});}catch(e){results.push({id,status:'FAIL',error:e.message});}}
function ok(b,msg){if(!b)throw Error(msg);}
for(const [name,width,height] of [['desktop',1440,1000],['tablet',820,1180],['mobile',390,844]]){
 const context=await browser.newContext({viewport:{width,height},offline:true,acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>errors.push({name,error:e.message}));page.on('request',r=>{if(!r.url().startsWith('file:'))requests.push(r.url());});await page.goto('file://'+file);await page.waitForTimeout(100);
 await check(name+':offline-init',async()=>{ok(await page.locator('#canvas').isVisible(),'canvas missing');ok(await page.evaluate(()=>layers.length===3&&layers[1].items.length>0),'seed missing');});
 if(name==='mobile')await check(name+':drawer',async()=>{ok(!await page.locator('#inspector').isVisible(),'drawer initially visible');await page.locator('#inspect').click();ok(await page.locator('#inspector').isVisible(),'drawer did not open');ok(await page.locator('#inspect').getAttribute('aria-expanded')==='true','aria state');await page.locator('#inspect').click();});
 await check(name+':layout',async()=>{ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'horizontal overflow');const b=await page.locator('#export').boundingBox();ok(b.x>=0&&b.x+b.width<=width,'export clipped');});
 const b=await page.locator('#canvas').boundingBox();const x=b.x+b.width*.5,y=b.y+b.height*.7;
 await check(name+':mouse-draw-undo-redo',async()=>{await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+40,y+20,{steps:8});await page.mouse.up();ok(await page.evaluate(()=>layers[0].items.length===1),'stroke not committed');await page.locator('#undo').click();ok(await page.evaluate(()=>layers[0].items.length===0),'undo not restored');await page.locator('#redo').click();ok(await page.evaluate(()=>layers[0].items.length===1),'redo not restored');});
 await check(name+':pan-zoom',async()=>{const old=await page.evaluate(()=>({...view}));await page.locator('[data-tool=hand]').click();await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+20,y+30);await page.mouse.up();ok(await page.evaluate(o=>Math.abs(view.x-o.x-20)<1&&Math.abs(view.y-o.y-30)<1,old),'pan translation');await page.locator('#in').click();ok(await page.evaluate(o=>view.z>o.z,old),'zoom unchanged');await page.locator('#home').click();});
 if(name==='mobile')await page.locator('#inspect').click();
 await page.locator('[data-panel=layers]').click();
 await check(name+':layers-visibility-opacity',async()=>{await page.locator('#add').click();ok(await page.evaluate(()=>layers.length===4&&active===4),'add failed');await page.locator('[aria-label="Hide Ink layer 4"]').click();ok(await page.evaluate(()=>layers[0].visible===false),'hide failed');await page.locator('[aria-label="Show Ink layer 4"]').click();await page.locator('#layer-opacity').evaluate(e=>{e.value='35';e.dispatchEvent(new Event('change',{bubbles:true}));});ok(await page.evaluate(()=>layers[0].opacity===.35),'opacity failed');});
 await check(name+':HSL-paper',async()=>{await page.locator('[data-panel=colour]').click();await page.locator('#hue').evaluate(e=>{e.value='210';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#sat').evaluate(e=>{e.value='70';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#light').evaluate(e=>{e.value='55';e.dispatchEvent(new Event('input',{bubbles:true}));});ok(await page.locator('#colour-value').textContent()==='hsl(210 70% 55%)','HSL output mismatch');const w=await page.locator('#wheel').boundingBox();await page.mouse.click(w.x+w.width*.85,w.y+w.height*.5);ok(await page.evaluate(()=>hue===0&&sat>60),'wheel failed');await page.locator('[data-panel=brush]').click();await page.locator('#paper').selectOption('white');ok(await page.evaluate(()=>paper==='white'),'paper failed');});
 if(name==='mobile')await page.locator('#inspect').click();
 await check(name+':PNG',async()=>{const dl=page.waitForEvent('download');await page.locator('#export').click();const d=await dl;const p=await d.path();const data=fs.readFileSync(p);ok(data.slice(1,4).toString()==='PNG','not PNG');const dim=[data.readUInt32BE(16),data.readUInt32BE(20)], expected=await page.evaluate(()=>[canvas.width,canvas.height]);ok(JSON.stringify(dim)===JSON.stringify(expected),'not current canvas dimensions');});
 if(name==='desktop'){
 await check('desktop:pressure-pointer',async()=>{await page.locator('[data-tool=pen]').click();const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1,pointerType:'pen',force:.2});await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:x+30,y:y+5,button:'left',buttons:1,pointerType:'pen',force:.8});await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:x+30,y:y+5,button:'left',clickCount:1,pointerType:'pen',force:0});ok(await page.evaluate(()=>{const s=layers[0].items.at(-1);return s&&s.pressure&&s.points.some(p=>p.p<.4)&&s.points.some(p=>p.p>.6)}),'pressure not recorded');});
 await check('desktop:erase-active-layer-only',async()=>{await page.locator('[data-panel=layers]').click();await page.locator('#add').click();await page.locator('[data-tool=pen]').click();await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+30,y+5);await page.mouse.up();const counts=await page.evaluate(()=>layers.map(l=>l.items.length));await page.locator('[data-tool=erase]').click();await page.mouse.click(x+15,y+2);const after=await page.evaluate(()=>layers.map(l=>l.items.length));ok(after[0]===0&&after.slice(1).every((v,i)=>v===counts[i+1]),'eraser crossed layer or failed');});
 await check('desktop:hidden-layer-draw-blocked',async()=>{await page.locator('[aria-label="Hide Ink layer 5"]').click();await page.locator('[data-tool=pen]').click();await page.mouse.click(x,y);ok(await page.evaluate(()=>layers[0].items.length===0),'hidden layer drew');});
 }
 await check(name+':refresh-reset-no-storage',async()=>{await page.reload();await page.waitForTimeout(80);ok(await page.evaluate(()=>layers.length===3&&active===3&&layers[0].items.length===0&&paper==='dots'),'state persisted');ok(await page.evaluate(()=>localStorage.length===0&&sessionStorage.length===0),'storage used');});
 await page.screenshot({path:'/tmp/unruly-qa-'+name+'.png'});await context.close();
}
await browser.close();const output={sha256:sha,results,errors,requests};console.log(JSON.stringify(output,null,2));fs.writeFileSync(__dirname+'/QA_PREVIEW.md','# UNRULY quarantined UX preview QA\n\nFresh isolated same-model adversary fallback; Claude on the local laptop is unavailable in this runtime. Browser-only checks; native engine and native pen feel are outside this checkpoint.\n\nCommand: `node whiteboard-preparation/prototypes/ux-preview/qa-preview.cjs`\n\nSource SHA256: `'+sha+'`\n\nChromium, headless, offline context. Desktop 1440×1000; tablet 820×1180; mobile 390×844. UI actions plus observable in-memory state assertions; pen input through Chromium DevTools Input with force 0.2 → 0.8.\n\n```json\n'+JSON.stringify(output,null,2)+'\n```\n\nScreenshots: `/tmp/unruly-qa-desktop.png`, `/tmp/unruly-qa-tablet.png`, `/tmp/unruly-qa-mobile.png`. They are runtime evidence, not deliverable assets. Refresh reset is intentional. No release/native-QA claim.\n');})();
